### ISSUE TITLE
Unable to install node-libcurl

### ISSUE THREAD

**Issue by sridharspeaks** [JCMais/node-libcurl#10]
Hi,

I am also getting a similar error and seriously got strucked here.

npm WARN package.json express-json@1.0.0 No repository field.
npm WARN engine node-libcurl@0.1.3: wanted: {"node":">= 0.8.0 && < 0.11.0"} (current: {"node":"0.10.36","npm":"1.4.28"})

node-libcurl@0.1.3 install /usr/local/node/ayla/node_modules/node-libcurl
node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
Cannot find curl's header file.

npm ERR! node-libcurl@0.1.3 install: node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@0.1.3 install script.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-431.17.1.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-libcurl"
npm ERR! cwd /usr/local/node/ayla
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

Just wanted to check if there is any solution available. Also may be due to this erorr, I am unable to do npm install node-curl.

Here is my curl version details
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

and here is my npm install --loglevel verbose. It appears that I haven't placed any package.json as I dont maintain any specific version dependencies. Does this cause a problem?

npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '--loglevel',
npm verb cli   'verbose' ]
npm info using npm@1.4.28
npm info using node@v0.10.36
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/usr/local/node/ayla/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 2.6.32-431.17.1.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "--loglevel" "verbose"
npm ERR! cwd /usr/local/node/ayla
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /usr/local/node/ayla/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm verb exit [ 34, true ]
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/node/ayla/npm-debug.log
npm ERR! not ok code 0

**Comment by JCMais** [comment]
> It appears that I haven't placed any package.json as I dont maintain any specific version dependencies. Does this cause a problem?

Yes, it does. You need a package.json file even if you are not publishing your project anywhere else, that is because npm get the dependencies from the file itself, run ``npm init`` inside the directory of your project, it will guide you through the creation of such file.

After the file is created you can run `npm install node-libcurl --save --loglevel verbose`, the ``--save`` flag add node-libcurl to your dependencies in the package.json.

**Comment by sridharspeaks** [comment]
I did added package.json as per your suggestion. However, I am still getting the same error...
Also, my main intention is to install node-curl which is also triggering some simillar error. Hope these two libraries are having something in common for build failure due to my environment. I could able to instal successfully node-curl in my mac but not here in this linux machine.

[root@host1 ayla]# npm install node-libcurl --save --loglevel verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   'node-libcurl',
npm verb cli   '--save',
npm verb cli   '--loglevel',
npm verb cli   'verbose' ]
npm info using npm@1.4.28
npm info using node@v0.10.36
npm WARN package.json ayla@1.0.0 No description
npm WARN package.json ayla@1.0.0 No repository field.
npm WARN package.json ayla@1.0.0 No README data
npm WARN package.json express-json@1.0.0 No repository field.
npm verb readDependencies using package.json deps
npm verb cache add [ 'node-libcurl', null ]
npm verb cache add name=undefined spec="node-libcurl" args=["node-libcurl",null]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: 'node-libcurl',
npm verb parsed url   path: 'node-libcurl',
npm verb parsed url   href: 'node-libcurl' }
npm verb lock node-libcurl /root/.npm/c4bad0d6-node-libcurl.lock
npm verb addNamed [ 'node-libcurl', '' ]
npm verb addNamed [ null, '*' ]
npm verb lock node-libcurl@ /root/.npm/c29d924f-node-libcurl.lock
npm verb request where is /node-libcurl
npm verb request registry https://registry.npmjs.org/
npm verb request id cd0ac59fd227d1dc
npm verb url raw /node-libcurl
npm verb url resolving [ 'https://registry.npmjs.org/', './node-libcurl' ]
npm verb url resolved https://registry.npmjs.org/node-libcurl
npm verb request where is https://registry.npmjs.org/node-libcurl
npm info trying registry request attempt 1 at 14:25:53
npm verb etag "2OWMX5YYT70JCVTKZ8SV2OEDL"
npm http GET https://registry.npmjs.org/node-libcurl
npm http 304 https://registry.npmjs.org/node-libcurl
npm verb etag https://registry.npmjs.org/node-libcurl from cache
npm verb addNamed [ 'node-libcurl', '0.1.3' ]
npm verb addNamed [ '0.1.3', '0.1.3' ]
npm verb lock node-libcurl@0.1.3 /root/.npm/6763a3ed-node-libcurl-0-1-3.lock
npm info install node-libcurl@0.1.3 into /usr/local/node/ayla
npm info installOne node-libcurl@0.1.3
npm WARN engine node-libcurl@0.1.3: wanted: {"node":">= 0.8.0 && < 0.11.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm verb node_modules/node-libcurl unbuild
npm verb tar unpack /root/.npm/node-libcurl/0.1.3/package.tgz
npm verb lock tar:///usr/local/node/ayla/node_modules/node-libcurl /root/.npm/8c728c45-e-ayla-node-modules-node-libcurl.lock
npm verb lock tar:///root/.npm/node-libcurl/0.1.3/package.tgz /root/.npm/9a536f86-m-node-libcurl-0-1-3-package-tgz.lock
npm info preinstall node-libcurl@0.1.3
npm verb readDependencies using package.json deps
npm verb readDependencies using package.json deps
npm verb cache add [ 'bindings@~1.2.0', null ]
npm verb cache add name=undefined spec="bindings@~1.2.0" args=["bindings@~1.2.0",null]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: 'bindings@~1.2.0',
npm verb parsed url   path: 'bindings@~1.2.0',
npm verb parsed url   href: 'bindings@~1.2.0' }
npm verb cache add name="bindings" spec="~1.2.0" args=["bindings","~1.2.0"]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: '~1.2.0',
npm verb parsed url   path: '~1.2.0',
npm verb parsed url   href: '~1.2.0' }
npm verb addNamed [ 'bindings', '~1.2.0' ]
npm verb addNamed [ null, '>=1.2.0-0 <1.3.0-0' ]
npm verb lock bindings@~1.2.0 /root/.npm/b6dd1de3-bindings-1-2-0.lock
npm verb request where is /bindings
npm verb request registry https://registry.npmjs.org/
npm verb url raw /bindings
npm verb url resolving [ 'https://registry.npmjs.org/', './bindings' ]
npm verb url resolved https://registry.npmjs.org/bindings
npm verb request where is https://registry.npmjs.org/bindings
npm info trying registry request attempt 1 at 14:25:53
npm verb etag "BJGP1201ZXLWX88VO1W0N0YSR"
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings
npm verb etag https://registry.npmjs.org/bindings from cache
npm verb addNamed [ 'bindings', '1.2.1' ]
npm verb addNamed [ '1.2.1', '1.2.1' ]
npm verb lock bindings@1.2.1 /root/.npm/e9060511-bindings-1-2-1.lock
npm info install bindings@1.2.1 into /usr/local/node/ayla/node_modules/node-libcurl
npm info installOne bindings@1.2.1
npm verb node_modules/node-libcurl/node_modules/bindings unbuild
npm verb tar unpack /root/.npm/bindings/1.2.1/package.tgz
npm verb lock tar:///usr/local/node/ayla/node_modules/node-libcurl/node_modules/bindings /root/.npm/e8ec0a13-de-libcurl-node-modules-bindings.lock
npm verb lock tar:///root/.npm/bindings/1.2.1/package.tgz /root/.npm/479db54d-t-npm-bindings-1-2-1-package-tgz.lock
npm info preinstall bindings@1.2.1
npm verb readDependencies using package.json deps
npm verb readDependencies using package.json deps
npm verb about to build /usr/local/node/ayla/node_modules/node-libcurl/node_modules/bindings
npm info build /usr/local/node/ayla/node_modules/node-libcurl/node_modules/bindings
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   '/usr/local/node/ayla/node_modules/node-libcurl/node_modules' ]
npm info linkStuff bindings@1.2.1
npm verb linkBins bindings@1.2.1
npm verb linkMans bindings@1.2.1
npm verb rebuildBundles bindings@1.2.1
npm info install bindings@1.2.1
npm info postinstall bindings@1.2.1
npm verb about to build /usr/local/node/ayla/node_modules/node-libcurl
npm info build /usr/local/node/ayla/node_modules/node-libcurl
npm verb linkStuff [ false, false, false, '/usr/local/node/ayla/node_modules' ]
npm info linkStuff node-libcurl@0.1.3
npm verb linkBins node-libcurl@0.1.3
npm verb linkMans node-libcurl@0.1.3
npm verb rebuildBundles node-libcurl@0.1.3
npm verb rebuildBundles [ 'bindings' ]
npm info install node-libcurl@0.1.3

> node-libcurl@0.1.3 install /usr/local/node/ayla/node_modules/node-libcurl
> node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild

Cannot find curl's header file.

npm verb unsafe-perm in lifecycle false
npm info node-libcurl@0.1.3 Failed to exec install script
npm ERR! node-libcurl@0.1.3 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@0.1.3 install script.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-431.17.1.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-libcurl" "--save" "--loglevel" "verbose"
npm ERR! cwd /usr/local/node/ayla
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm verb exit [ 1, true ]
npm verb node_modules/node-libcurl unbuild
npm info preuninstall node-libcurl@0.1.3
npm info uninstall node-libcurl@0.1.3
npm verb true,/usr/local/node/ayla/node_modules,/usr/local/node/ayla/node_modules unbuild node-libcurl@0.1.3
npm info postuninstall node-libcurl@0.1.3
npm ERR! not ok code 0

**Comment by JCMais** [comment]
> Cannot find curl's header file.

Install the libcurl header files, from what I can tell, you are running CentOs, so: `sudo apt-get install libcurl4-gnutls-dev`

**Comment by sridharspeaks** [comment]
Thank you very much for your help This really worked for me but I tried it using yum install libcurl-devel.x86_64.

Thank you very much once again for your help.

**Comment by JCMais** [comment]
Glad I could help!
