### ISSUE TITLE
Question: Any way to get URLs in redirect chain?

### ISSUE THREAD

**Issue by gschier** [JCMais/node-libcurl#100]
I know there is `curl.getInfo(Curl.info.EFFECTIVE_URL)` to get the resulting URL of the request (last one in the chain) but do you know of any way to do this for each step in a redirect chain besides resolving the `Location` header of each?

**Comment by JCMais** [comment]
Hi @gschier,

libcurl doesn't have any other way to do that besides parsing the `Location` header.

**Comment by gschier** [comment]
I was afraid of that. Not a huge deal, just a bit of a hassle to implement. Thanks @JCMais!
