### ISSUE TITLE
Update curl-for-windows to 7.54

### ISSUE THREAD

**Issue by gschier** [JCMais/node-libcurl#101]
Hey @JCMais.

How much work is it to update curl-for-windows to 7.54? There is a fix in 7.53 related to NTLM authentication that I would like to get access to.

It looks like the [last one](https://github.com/JCMais/curl-for-windows/commit/96e4fff75c13503bb263de750c125320b437e8ab) was just a submodule update? 

Let me know if this is something you want to do and if there is anything I can do to help.

**Comment by JCMais** [comment]
Hi @gschier.

Basically, yeah, that latest update was that easy, but sometimes some more work is needed. This is what I do:

1. Download the tarball of the new version (in your case: [curl-7_54_1.zip](https://github.com/curl/curl/archive/curl-7_54_1.zip)) and unzip it somewhere
2. Use a directory diff tool (I use [beyond compare](https://www.scootersoftware.com/) and heavily recommend it) and compare:
  * The `lib` folder from both versions, the current one being pointed by the submodule, and the one you downloaded.
  * Same than above, but now for the `src` folder, modifying the correspondent gyp entry: https://github.com/JCMais/curl-for-windows/blob/master/curl.gyp#L52

**Comment by JCMais** [comment]
`curl-for-windows` has just been updated to use `curl-7.54.0`.

The `develop` branch currently has the new options that were added by that version.

Project was stalled because I was having some computer issues, this has been resolved, and I will be able to get a new release on npm the following days.

**Comment by gschier** [comment]
Awesome, thanks @JCMais! Looking forward to the release 😄

**Comment by gschier** [comment]
@JCMais question. It looks like my CI builds started pulling in 7.55.0 even though I didn't change my [pinned version](https://github.com/getinsomnia/node-libcurl/tree/d3ee4d436a174c2bd5f2dc89b165257a5cac32ea) of a fork of `node-libcurl`. The reason I ask is that some users have been reporting hanging requests after a recent release.

Do you know what this could have been caused by? I noticed that your CI uploads new RELEASE files on every commit. Could it have been that you overwrote the release files with the latest unpublished build?

![image](https://user-images.githubusercontent.com/587576/29385047-32d846e4-828b-11e7-975e-48f9c1808008.png)

**Comment by gschier** [comment]
Oh, I think it's actually due to the `curl-for-windows` submodule pointing to `master` instead of a hash.

**Comment by JCMais** [comment]
@gschier binaries are only uploaded for tags builds, since then a release is created on GitHub.

The issue is exactly the one you mentioned on your latest comment, which is actually something I didn't payed attention. When I created it I didn't know you could use a commit hash instead of only the branch name.

Windows users will always download the latest version from the curl-for-windows module.

**Comment by gschier** [comment]
Ya, I realized that after. I tried pinning the submodule to a commit, but that didn't work. I think the submodule fetch script ignores that somehow. I ended up forking `curl-for-windows` and updating the submodule to point to my fork instead. Working again now 😄

**Comment by JCMais** [comment]
@gschier is adding the SHA1 hash to .gitmodules working? I don't see any docs about it on git.

**Comment by JCMais** [comment]
The best thing to do here would be to instead of using this submodule, to clone the repo directly, and use tags instead.

The only thing needed would be to add a file saying which tag to checkout, and adapt the script to retrieve the tag from this file and checkout the repo.

**Comment by gschier** [comment]
Yes, it is valid to use a hash as the branch, but you don't have to modify this manually. Git will automatically update the `.gitmodules` file for you if you do the following:

1. `cd` into the submodule folder (`cd deps/curl-for-windows`)
2. Checkout whatever you want (`git checkout d6b96338836273d15627d5b79c65a148e5dfbe73`)
3. `cd` back into project root (`cd ../..`)
4. `git status` will now show the submodule change
5. `git add -A && git commit -m "Update submodule"` will correctly update the `.gitmodules` file

**Comment by gschier** [comment]
As a Git side note. I'm pretty sure branches/tags/hashes can be used interchangeably in most git operations, which is why it's valid it `.gitmodules` but not specifically documented. I'm guessing a tag would also work in there.

**Comment by JCMais** [comment]
I will try that, now that I finally got the build to pass.

**Comment by gschier** [comment]
Nice :)

**Comment by JCMais** [comment]
Didn't worked for me, what is the git version you are using?

```
>git submodule update --remote
fatal: Needed a single revision
Unable to find current origin/6b9bc5a4fe5ebfb884a0ea7fe0329923cd4b774c revision in submodule path 'curl
```

I think I will go with the solution above.

**Comment by gschier** [comment]
Oh, that hash was from my fork. You can pull a specific hash from `git log`.

**Comment by JCMais** [comment]
The test submodule above was one pointing at the curl project, so the hash is theirs https://github.com/curl/curl/tree/6b9bc5a4fe5ebfb884a0ea7fe0329923cd4b774c

**Comment by gschier** [comment]
On a laptop now...

I've never used `git submodule update --remote`, but that command gives me the same error you got. What are you trying to do with that command?

**Comment by gschier** [comment]
Found some info here, but I don't really understand it. I've always done the cd-and-pull method, which seems to work fine. Maybe `update --remote` only works on branches and not commits?
