### ISSUE TITLE
linux setup error 404

### ISSUE THREAD

**Issue by tuncaybahadir** [JCMais/node-libcurl#102]
Hi,
When I try to install the machine with node version v8.0.0 and npm 5.0.0, I get the following errors. Could you help ?

node-libcurl@1.1.0 install /root/node_modules/node-libcurl
node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/root/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@8.0.0 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/root/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v57-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.1.0 and node@8.0.0 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v57-linux-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
Could not run curl-config, please make sure libcurl dev package is installed.
Output: /bin/sh: 1: curl-config: not found

gyp: Call to 'node "/root/node_modules/node-libcurl/tools/curl-config.js"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "/usr/local/bin/node" "/root/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/root/node_modules/node-libcurl/lib/binding"
gyp ERR! cwd /root/node_modules/node-libcurl
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error

**Comment by JCMais** [comment]
`Could not run curl-config, please make sure libcurl dev package is installed.`

You need the dev packages of libcurl installed on your machine.

If you are using debian/ubuntu, you can install them by running `apt-get install libcurl4-dev-openssl`

**Comment by JCMais** [comment]
timing out
