### ISSUE TITLE
Use CURLOPT_READFUNCTION with stream

### ISSUE THREAD

**Issue by gschier** [JCMais/node-libcurl#106]
Hey @JCMais,

I'm trying to replace Curl's multipart form building with my own (build request body manually, then use [CURLOPT_READFUNCTION](https://curl.haxx.se/libcurl/c/CURLOPT_READFUNCTION.html)). However, there is one snag. 

Originally, I built the entire body into a `Buffer`, which worked great.  However, buffers have a max size of about 2GB so it fails beyond that. I have since converted it to be a stream, but there is one problem. A stream may not return data every time `read()` is called.

The following snippet illustrates the problem. When the callback is called, there may be no data available from the stream (maybe the file system is slow), but returning `0` will cause the upload to terminate.

```javascript
let uploadedBytes = 0;
curl.setOpt(Curl.option.READFUNCTION, (buffer: Buffer, foo, bar) => {
  if (uploadedBytes >= multipartBodyLength) {
    // We have uploaded the whole thing. Nothing left.
    return 0;
  }

  const data = multipartBody.read(buffer.length / 2);

  if (!data) {
    // This might NOT actually be the end of the stream
    // but returning 0 here ends the upload.
    return 0;
  }

  const bytes = data.copy(buffer);
  uploadedBytes += bytes;
  return bytes;
});
```

Do you know of an easy way to upload an extremely large amount of binary data? A potential workaround that I'm considering is writing the whole stream to the filesystem, using `CURLOPT_READDATA` to send it, then deleting the file immediately after.

Thanks!

**Comment by JCMais** [comment]
You got me here, I think your solution is going to work.

I don't think Curl has any other way to upload large files.

**Comment by gschier** [comment]
Dang, well thanks anyway! 😄 

I ended up implementing with a temp file and it seems to be working pretty well 👍
