### ISSUE TITLE
curl.setProgressCallback does not work!

### ISSUE THREAD

**Issue by xietao1233** [JCMais/node-libcurl#107]
curlProgressCallback is not be called, and set NOPROGRESS is 0, will occur  a assertion failed "object->internalFieldCount()>0"

**Comment by JCMais** [comment]
Node/js version and  node-libcurl version?

Sorry about the long delay, only saw your issue now.

**Comment by JCMais** [comment]
Can you still reproduce this @xietao1233 ? If yes, can you share a reproducible code sample?
