### ISSUE TITLE
Handle response headers with same name

### ISSUE THREAD

**Issue by gschier** [JCMais/node-libcurl#108]
Right now response headers are stored in an Object, meaning that multiple headers by the same name (except `Set-Cookie`) are not handled. Is there a reason for this? It would be awesome to do this for all headers. 

I believe NodeJS handles this by storing individual headers as Strings and only converting them to Arrays if there are more than one. See [http docs](https://nodejs.org/api/http.html#http_response_getheaders)

https://github.com/JCMais/node-libcurl/blob/2e0e0ae192d13785ebef111de22d6e1cc1239349/lib/Curl.js#L774-L785

**Comment by JCMais** [comment]
According to the HTTP RFC, a client should not send duplicated headers, https://tools.ietf.org/html/rfc7230#section-3.2.2, `Set-Cookie` is the only exception.

I know not all clients respect this, but since this is something too specific, it would be better to simple use your own logic to parse them.

You can do that by enabling the `NO_HEADER_PARSING` /feature.

```
//...
curl.enable(Curl.features.NO_HEADER_PARSING);
```

After you enable that, the headers arg passed to the end event is going to be a Buffer, with the raw data.

**Comment by gschier** [comment]
It looks like it's fairly common for `WWW-Authenticate` to be returned as multiple headers: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.47

I would be happy to submit a PR for this, as it seems like it would only take a few lines of code, but I'm worried because this would mean breaking the current API. What are your thoughts on changing the header object to mirror the NodeJS format?

P.S. I'm also perfectly fine implementing the header parsing logic on my end.

**Comment by JCMais** [comment]
I'm fine with it, in reality I after looking into it (https://nodejs.org/api/http.html#http_message_headers), I appreciate it more than what we have currently.

> but I'm worried because this would mean breaking the current API

I can release a new major for that one.

**Comment by gschier** [comment]
Sweet, I'll put together a PR right now.

**Comment by gschier** [comment]
Hmm, I may actually need to do the custom parsing on my end anyway because I need to be able to preserve case. NodeJS converts all header names to lowercase so that it doesn't end up with something confusing like this:

```js
{
  'WWW-Authenticate': ['value 1', 'value 2'],
  'www-authenticate': 'value 3'
}
```

**Comment by JCMais** [comment]
No problem, I will do some rewrites the following month when I get some free time, so I will include this on it.

let me know if the custom parsing fixes it for you.

**Comment by gschier** [comment]
Yep, I already implemented it on my end and it's working great. Thanks for the tip about disabling header parsing.

**Comment by JCMais** [comment]
I've decided to not include this on the addon itself, library users can change this behavior easily by using their own header parser.

**Comment by gschier** [comment]
I agree with this decision 🙂 👍 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
