### ISSUE TITLE
support Node.js 8 V8 version 5.8 / Node.js 9 V8 version 5.9 API

### ISSUE THREAD

**Issue by john30** [JCMais/node-libcurl#110]
no gyp for these V8 versions available and Windows build from source fails due to deprecation of v8.h ForceSet()

**Comment by JCMais** [comment]
Hi @john30 , thanks for the report. I already know what the issue is, I will try to fix this weekend.

**Comment by john30** [comment]
great, thanks!

**Comment by AntonioMIN** [comment]
when i run npm install node-libcurl --save and debug application
`Error: A dynamic link library (DLL) initialization routine failed.
\\?\c:\workspace\MYELECTRONPROJECT\node_modules\node-libcurl\lib\binding\node_libcurl.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\workspace\MYELECTRONPROJECT\node_modules\node-libcurl\lib\Easy.js:40:29)
    at Object.<anonymous> (c:\workspace\MYELECTRONPROJECT\node_modules\node-libcurl\lib\Easy.js:280:3)`
Here the error.
I am working on Windows 10 64bit.

**Comment by JCMais** [comment]
@AntonioMIN node version?

**Comment by AntonioMIN** [comment]
@JCMais i am using node v8.9.4.

**Comment by JCMais** [comment]
Everyone, try the latest version, `node-libcurl@1.3.0`

**Comment by AntonioMIN** [comment]
3479 verbose Windows_NT 10.0.16299
3480 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-libcurl" "--save"
3481 verbose node v8.9.4
3482 verbose npm  v5.6.0
3483 error code ELIFECYCLE
3484 error errno 1
3485 error node-libcurl@1.3.0 install: `node-pre-gyp install --fallback-to-build`
3485 error Exit status 1
3486 error Failed at the node-libcurl@1.3.0 install script.
3486 error This is probably not a problem with npm. There is likely additional logging output above.
3487 verbose exit [ 1, true ]

here my log messages.

**Comment by JCMais** [comment]
Can you paste the whole output somewhere or send it to me over e-mail? My e-mail is on my Github profile.

**Comment by john30** [comment]
same here with node v9.5.0

**Comment by john30** [comment]
sorry for my previous comment, I had no python in the path and consequently the build from source failed.
1.3.0 works fine for me now with node v9.5.0

**Comment by JCMais** [comment]
Soon I will fix the CI jobs and we will have built binaries for Node.js 9

**Comment by john30** [comment]
unfortunately, there is one issue remaining:
```
npm ERR! path C:\temp\project\node_modules\node-libcurl\node_modules\abbrev
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\temp\project\node_modules\node-libcurl\node_modules\abbrev' -> 'C:\temp\project\node_modules\node-libcurl\node_modules\.abbrev.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
...
```
This is the same for node v9.5.0 and v9.40 but only occurs under certain conditions and not all the time. I can't find the reason why it does not work sometimes though...
Have you recognized a similar behaviour?

**Comment by JCMais** [comment]
huh, never saw this error

Probably related? https://github.com/mapbox/node-sqlite3/issues/866

**Comment by john30** [comment]
I don't know. I tried pretty much everything stated in there and the last most-of-the-time working way was to delete the package.json, package-lock.json, remove the node_modules dir, install node-libcurl only, then bring back the packages.json and finally run npm install.
