### ISSUE TITLE
Way to specify http verb / more verb options

### ISSUE THREAD

**Issue by samjross** [JCMais/node-libcurl#111]
I've been using node-libcurl to successfully interact with my Dynamics NAV Soap services, couldn't get any other node.js packages to work seamlessly with the ntlm authentication.

Problem is that one of the Dynamics NAV apis requires sending an HTTP MERGE request, but I can't find any way to make a MERGE instead of POST/GET.

**Comment by JCMais** [comment]
You probably want to check this option https://curl.haxx.se/libcurl/c/CURLOPT_CUSTOMREQUEST.html

**Comment by samjross** [comment]
Thanks.

For some reason when I do `curl.setOpt(Curl.option.CUSTOMREQUEST, "MERGE");`, NTLM authentication stops working. I get a response back from the server, 

> Could not validate the client concurrency token required by the service. Please provide a valid token in the client request.

This doesn't happen with get/post requests to the same server using the same settings.

**Comment by JCMais** [comment]
Sorry, but this is probably something on libcurl itself and not on this binding, can you try to execute the request directly using curl from command line and see if it works?

**Comment by JCMais** [comment]
Timing out, feel free to reopen if have more information.
