### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by ChiaraMartignano** [JCMais/node-libcurl#113]
Hi,

I'm trying to install node-libcurl on Windows. Apparently I get some issues with curl-for-windows installation. I have all the prerequisites, both Python 2.7 and Visual Studio above 2015.

Here's the output in verbose mode:

node-libcurl@1.3.0 install C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl
node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\Users\\Chiar\\SISMEL\\back\\node_modules\\node-libcurl\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@9.5.0 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\lib\binding\node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v1.3.0/node_libcurl-v1.3.0-node-v59-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v1.3.0/node_libcurl-v1.3.0-node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.3.0/node_libcurl-v1.3.0-node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.3.0 and node@9.5.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v1.3.0/node_libcurl-v1.3.0-node-v59-win32-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'clean' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.5.0 | win32 | x64
gyp verb command clean []
gyp verb clean removing "build" directory
gyp info ok
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=C:\\Users\\Chiar\\SISMEL\\back\\node_modules\\node-libcurl\\lib\\binding\\node_libcurl.node',
gyp verb cli   '--module_name=node_libcurl',
gyp verb cli   '--module_path=C:\\Users\\Chiar\\SISMEL\\back\\node_modules\\node-libcurl\\lib\\binding',gyp verb cli   '--python=/C:/Python27/python.exe',
gyp verb cli   '--msvs_version=2015' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.5.0 | win32 | x64
gyp verb command configure []
gyp verb check python checking for Python executable "/C:/Python27/python.exe" in the PATH
gyp verb `which` failed Error: not found: /C:/Python27/python.exe
gyp verb `which` failed     at getNotFoundError (C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  /C:/Python27/python.exe { Error: not found: /C:/Python27/python.exe
gyp verb `which` failed     at getNotFoundError (C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: /C:/Python27/python.exe\n    at getNotFoundError (C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\which\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\which\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "/C:/Python27/python.exe". checking python launcher
gyp verb check python launcher python executable found: "C:\\Users\\Chiar\\.windows-build-tools\\python27\\python.exe"
gyp verb check python version `C:\Users\Chiar\.windows-build-tools\python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.5.0
gyp verb command install [ '9.5.0' ]
gyp verb install input version string "9.5.0"
gyp verb install installing version: 9.5.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.5.0
gyp verb build dir attempting to create "build" dir: C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\build
gyp verb build dir "build" dir needed to be created? C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\Chiar\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Chiar\\SISMEL\\back\\node_modules\\node-libcurl\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Chiar\\.node-gyp\\9.5.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Chiar\\.node-gyp\\9.5.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Chiar\\.node-gyp\\9.5.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Chiar\\SISMEL\\back\\node_modules\\node-libcurl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Chiar\\SISMEL\\back\\node_modules\\node-libcurl\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Error: Command failed: cd curl-for-windows && git submodule update --init && python configure.py
Submodule 'build/gyp' (https://chromium.googlesource.com/external/gyp) registered for path 'build/gyp'
Submodule 'curl' (https://github.com/curl/curl.git) registered for path 'curl'
Submodule 'libssh2' (https://github.com/libssh2/libssh2.git) registered for path 'libssh2'
Submodule 'zlib' (https://github.com/madler/zlib.git) registered for path 'zlib'
Cloning into 'C:/Users/Chiar/SISMEL/back/node_modules/node-libcurl/curl-for-windows/build/gyp'...
Cloning into 'C:/Users/Chiar/SISMEL/back/node_modules/node-libcurl/curl-for-windows/curl'...
Cloning into 'C:/Users/Chiar/SISMEL/back/node_modules/node-libcurl/curl-for-windows/libssh2'...
Cloning into 'C:/Users/Chiar/SISMEL/back/node_modules/node-libcurl/curl-for-windows/zlib'...
  File "configure.py", line 99
    print 'Error running GYP'
                            ^
SyntaxError: Missing parentheses in call to 'print'

gyp: Call to 'node "C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl/tools/retrieve-win-deps.js"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Chiar\\SISMEL\\back\\node_modules\\node-libcurl\\lib\\binding\\node_libcurl.node" "--module_name=node_libcurl" "--module_path=C:\\Users\\Chiar\\SISMEL\\back\\node_modules\\node-libcurl\\lib\\binding" "--python=/C:/Python27/python.exe" "--msvs_version=2015"
gyp ERR! cwd C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\lib\binding\node_libcurl.node --module_name=node_libcurl --module_path=C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\lib\binding --python=/C:/Python27/python.exe --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Chiar\\SISMEL\\back\\node_modules\\node-libcurl\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl
node-pre-gyp ERR! node -v v9.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\lib\binding\node_libcurl.node --module_name=node_libcurl --module_path=C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\lib\binding --python=/C:/Python27/python.exe --msvs_version=2015' (1)
npm verb lifecycle node-libcurl@1.3.0~install: unsafe-perm in lifecycle true
npm verb lifecycle node-libcurl@1.3.0~install: PATH: C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Chiar\SISMEL\back\node_modules\node-libcurl\node_modules\.bin;C:\Users\Chiar\SISMEL\back\node_modules\.bin;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\LyX 2.2\Perl\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Program Files\nodejs\;C:\Users\Chiar\.windows-build-tools\python27\;C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Chiar\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\Chiar\AppData\Roaming\npm\node_modules\.bin;C:\Users\Chiar\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Chiar\AppData\Local\Programs\Python\Python36-32\;C:\Ruby23\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Chiar\AppData\Local\Microsoft\WindowsApps;C:\Users\Chiar\AppData\Local\Microsoft\WindowsApps;C:\Users\Chiar\AppData\Roaming\npm
npm verb lifecycle node-libcurl@1.3.0~install: CWD: C:\Users\Chiar\SISMEL\back\node_modules\node-libcurlnpm info lifecycle node-libcurl@1.3.0~install: Failed to exec install script
npm verb unlock done using C:\Users\Chiar\AppData\Roaming\npm-cache\_locks\staging-fe338ca579fb711d.lock for C:\Users\Chiar\SISMEL\back\node_modules\.staging
npm verb stack Error: node-libcurl@1.3.0 install: `node-pre-gyp install --fallback-to-build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
npm verb stack     at EventEmitter.emit (events.js:160:13)
npm verb stack     at ChildProcess.<anonymous> (C:\Users\Chiar\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:160:13)
npm verb stack     at maybeClose (internal/child_process.js:943:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npm verb pkgid node-libcurl@1.3.0
npm verb cwd C:\Users\Chiar\SISMEL\back
npm verb Windows_NT 10.0.16299
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Chiar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "--verbose"
npm verb node v9.5.0
npm verb npm  v5.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-libcurl@1.3.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chiar\AppData\Roaming\npm-cache\_logs\2018-02-05T17_18_53_844Z-debug.log

Tell me if you need more info.

Thanks for your help!

**Comment by JCMais** [comment]
That is a strange error,
```
SyntaxError: Missing parentheses in call to 'print'
```

Parentheses are only required on Python 3. Do you have it installed?

**Comment by ChiaraMartignano** [comment]
I have both versions installed, the 2.7 and the 3.6.

**Comment by JCMais** [comment]
The script that retrieves the Windows dependenceis is using it.

https://github.com/JCMais/node-libcurl/blob/develop/tools/retrieve-win-deps.js#L79-L81

I think you can overwrite the PATH variable before running npm install, to point to the python 2.7 path first.

```
SET PATH=C:\my-path-to-python;%PATH%
npm install node-libcurl
```

**Comment by ChiaraMartignano** [comment]
Ok, I'll try and I'll let you know. Thanks!

**Comment by ChiaraMartignano** [comment]
It worked! Thank you! :)

**Comment by Varelion** [comment]
> The script that retrieves the Windows deps is using the 3.6 binaries.
> 
> https://github.com/JCMais/node-libcurl/blob/develop/tools/retrieve-win-deps.js#L79-L81
> 
> I think you can overwrite the PATH variable before running npm install, to point to the python 2.7 path first.
> 
> ```
> SET PATH=C:\my-path-to-python;%PATH%
> npm install node-libcurl
> ```

Sorry for necroposting, but this saved me after hours of work. THANKS!
