### ISSUE TITLE
Unable to use with electron-rebuild

### ISSUE THREAD

**Issue by Acidic9** [JCMais/node-libcurl#114]
I understand this issue is not with node-libcurl, and more about [electron-rebuild](https://github.com/electron/electron-rebuild), I am just mainly looking for some help.

I am running Windows 10 64bit.

To replicate my issue, in gitbash terminal, I enter the following commands...

```bash
npm init -y                             # Successfully initializes

npm install node-libcurl                # Successfully builds with `node-pre-gyp install --fallback-to-build`

npm install --save-dev electron-rebuild # Fails
```

The output of the last command (install electron-rebuild) is the following...

```bash
$ npm install --save-dev electron-rebuild

npm WARN tst@1.0.0 No description
npm WARN tst@1.0.0 No repository field.

npm ERR! path C:\Users\Arise\tst\node_modules\node-libcurl\node_modules\abbrev
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Arise\tst\node_modules\node-libcurl\node_modules\abbrev' -> 'C:\Users\Arise\tst\node_modules\node-libcurl\node_modules\.abbrev.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Arise\AppData\Roaming\npm-cache\_logs\2018-02-20T13_06_13_960Z-debug.log
```

---

After tackling this issue for quite some time, I made a golang program within `node_modules/node-libcurl` to read every single npm module inside of the text file `node_modules/node-libcurl/yarn.lock` and merge it into a single `npm install ...` command to be run inside the `node_modules/node-libcurl` directory.

I am not super familiar with how npm/nodejs works and I have no idea what `yarn.lock` is, but it contains a list of many modules inside it, so I thought installing everything I see could do the trick.

After installing all the modules listed in `yarn.lock` and running `npm install --save-dev electron-rebuild` inside my root folder (not inside `node_modules/node-libcurl`), I'm stuck at the following output:

```bash
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN downloader@1.0.0 No description
npm WARN downloader@1.0.0 No repository field.

npm ERR! path C:\Users\Arise\Documents\Programming\JS\Electron\downloader\node_modules\node-libcurl\node_modules\node-pre-gyp\node_modules\nopt
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Arise\Documents\Programming\JS\Electron\downloader\node_modules\node-libcurl\node_modules\node-pre-gyp\node_modules\nopt' -> 'C:\Users\Arise\Documents\Programming\JS\Electron\downloader\node_modules\node-libcurl\node_modules\node-pre-gyp\node_modules\.nopt.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Arise\AppData\Roaming\npm-cache\_logs\2018-02-20T13_16_54_329Z-debug.log
```

**Comment by JCMais** [comment]
`yarn.lock` should not influence the install of this library, so I don't think it's related to it.

Yarn is just another package manager for the Node ecosystem, the other one is npm. It's a matter of personal preference.

About that problem 
```
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Arise\tst\node_modules\node-libcurl\node_modules\abbrev' -> 'C:\Users\Arise\tst\node_modules\node-libcurl\node_modules\.abbrev.DELETE'
```

I have saw it other times, and most of the time it's on Windows, I will try to check it for more details.


But here are some issues about that problem:

https://github.com/npm/npm/issues/17444

https://github.com/mapbox/node-sqlite3/issues/866


If you can, I would recommend trying `yarn` and see if it works with it: https://yarnpkg.com/pt-BR/

**Comment by Acidic9** [comment]
Thank you very much @JCMais, I found my solution here: https://github.com/npm/npm/issues/17444#issuecomment-321851320

Just had to delete package-lock.json, then run `npm install --save-dev electron-rebuild` and it worked!
