### ISSUE TITLE
Missing Release 1.3.0

### ISSUE THREAD

**Issue by msosas** [JCMais/node-libcurl#116]
Hi, I'm seeing that in https://www.npmjs.com/package/node-libcurl says that the latest release is 1.3.0 as the pictures shows:
![image](https://user-images.githubusercontent.com/8659222/36850526-d433afc4-1d45-11e8-9655-c56916ee1ab7.png)

But at GitHub, the latest release seems to be 1.2.0
![image](https://user-images.githubusercontent.com/8659222/36850583-fb4aa13a-1d45-11e8-8c53-5ff9832bacb2.png)

**Comment by JCMais** [comment]
I will release a new version soon, `v1.3` is basically the same than `v1.2`, there were just code style changes.

**Comment by msosas** [comment]
Actually, the problem I was facing was that if I include the compatible character within the package.json (like  ^1.2.0), npm tried to download 1.3.0 version and then fail, due to it doesn't find it.
`node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.3.0/node_libcurl-v1.3.0-node-v57-linux-x64.tar.gz `.
I workaround, for me in this case,  could be removing the "^" character. 
Thanks!

**Comment by JCMais** [comment]
I just checked, this error should not impact on the usage of the library, it's just because the binaries for this version were not released, so the binary would need to be compiled from source.

**Comment by JCMais** [comment]
Have made a new release just in case this was still an issue.
