### ISSUE TITLE
how to make post request for given curl ?

### ISSUE THREAD

**Issue by Vikkee-Singh** [JCMais/node-libcurl#118]
curl -v -H "Content-Type: application/x-www-form-urlencoded" -k -E "example.pem" -d "user_type=user_credentials&scope=testidauth+exampleservices&client_id=exampleclient.11000703613" "https://test.examplesolutions.com.au/TEST_exampleSecurityTokenServiceUserCertificate/connect/token"

**Comment by JCMais** [comment]
add `--libcurl` to the `cURL` command and it will output a C file with the code necessary to reproduce the request, if you open that file, you just need to check the calls to `curl_easy_setopt` and make the necessary adjustments to call them using this library.
