### ISSUE TITLE
Fastest and most efficient away to do requests?

### ISSUE THREAD

**Issue by osxpinot** [JCMais/node-libcurl#121]
Hello,

I have a use case where speed is of the utmost importance. I was wondering about things like socket sharing. To be efficient, is it necessary to use Multi or will Curl suffice? I believe I read the author commenting that Curl is an abstraction of Multi. Any special flags I should set for socket reuse or any other way to optimize speed?

**Comment by JCMais** [comment]
Curl uses Multi, yes.

I don't think there is any specific setting that could make the it run faster. What you can do, is disable the data parsing that we are doing currently, that could create some latency if the request is really big and you are parsing it again. Example:


```
var Curl = require( 'node-libcurl' ).Curl,
    curl = new Curl();

curl.setOpt( Curl.option.URL, 'http://www.google.com.b );
curl.setOpt( Curl.option.FOLLOWLOCATION, true );

// Enable the NO_DATA_PARSING bitmask, this basically means that
// the data will be returned to the end callback without any conversion.
curl.enable( Curl.feature.NO_DATA_PARSING );

function errorCallback( error, errCode ) {
    console.log( error, errCode );
    this.close();
}

function endCallback( statusCode, body, headers ) {
    // Since we enabled NO_DATA_PARSING, body will be a Buffer object here, and not a string.
    this.close();
}

curl.on( 'error', errorCallback );
curl.on( 'end', endCallback );
curl.perform();
```
