### ISSUE TITLE
SOCKS proxy connections are blocking

### ISSUE THREAD

**Issue by curiouslybrown** [JCMais/node-libcurl#122]
This is a know bug in curl: https://curl.haxx.se/docs/knownbugs.html#SOCKS_proxy_connections_are_done

The event loop will be blocked until the SOCKS connection has been made. However, I just so happen to be running a SOCKS proxy in nodejs, so the blocking nature prevents curl from ever being able to connect to my SOCKS proxy. I will be putting the proxy server in a separate process, but are there any ideas to alleviate this issue in the scope of this module?

**Comment by JCMais** [comment]
I cannot think of any way around that besides running the server on another process.
