### ISSUE TITLE
nodejs 10 " SSL_CTX_new:library has no ciphers "

### ISSUE THREAD

**Issue by meabed** [JCMais/node-libcurl#123]
after upgrade to nodejs 10
I alway get this error 

```
* Connected to google.com (0.0.0.0) port 443 (#0)
* SSL: couldn't create a context: error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers
* Closing connection 0
```
When i downgrade to node 9 it works fine.

```
root@510775b8fa59:/# openssl version
OpenSSL 1.0.2g  1 Mar 2016

root@510775b8fa59:/# curl --version
curl 7.59.0 (x86_64-pc-linux-gnu) libcurl/7.59.0 OpenSSL/1.0.2o zlib/1.2.8 librtmp/2.3
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

root@510775b8fa59:/# node --version
v10.0.0
```

looking through the curl options https://curl.haxx.se/libcurl/c/CURLOPT_SSL_CTX_FUNCTION.html

but its not implemented in https://github.com/JCMais/node-libcurl/blob/develop/src/Curl.cc#L166

any idea what could be the fix :) 

Thanks

**Comment by JCMais** [comment]
> When i downgrade to node 9 it works fine.

Can you put the versions like you did for node 10?

I will try to look into that the following week. I suspect it's related to a recent change on libcurl, https://github.com/curl/curl/issues/2276, but I might be wrong here.

**Comment by Meabed** [comment]
any chance you this will be solved?

**Comment by Meabed** [comment]
I have upgraded to openssl 1.1.0h and it works fine 
```
root@ba5bf05284e4:/tmp/Workspace/node-libcurl# curl --version
curl 7.60.0 (x86_64-pc-linux-gnu) libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.8 librtmp/2.3
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
```

```
root@ba5bf05284e4:/tmp/Workspace/node-libcurl# /usr/local/bin/openssl version
OpenSSL 1.1.0h  27 Mar 2018
```

```
root@ba5bf05284e4:/tmp/Workspace/node-libcurl# node examples/ssl.js
* Rebuilt URL to: https://www.google.com/
*   Trying 216.239.38.120...
* TCP_NODELAY set
* Connected to www.google.com (216.239.38.120) port 443 (#0)
* ALPN, offering http/1.1
* error setting certificate verify locations:
  CAfile: /tmp/Workspace/node-libcurl/examples/cacert.pem
  CApath: none
* Closing connection 0
```

**Comment by JCMais** [comment]
Hi, sorry for the delay to answer, could not find time to look into that but I'm glad that you found a solution. Will leave this issue open for some time so other people can find it easier..

**Comment by Meabed** [comment]
No Worries, i think its an issue in the way i compiled openssl and build curl
I will verify and post the update here in the issue, also i will post dockerfile for the compile options.

Thanks

**Comment by simonzsolt** [comment]
I had this error when working on Ubuntu 17, with node 9 on a specific URL (google.com worked though).  I found this wiki article on OpenSSL (https://wiki.openssl.org/index.php/Library_Initialization) and some old bug reports form 2008 on Debian systems and openssl library. I compiled node-libcurl against NSS and that resolved  problem with the URL.

**Comment by JCMais** [comment]
@Meabed can you let me know if this error persists with the latest version?

**Comment by Meabed** [comment]
@JCMais Everything is working well as expected.
I have made docker image with custom build from both Openssl and Curl.
[Docker Curl](https://github.com/me-io/docker-images/blob/master/curl/Dockerfile) - [Docker Openssl](https://github.com/me-io/docker-images/blob/master/openssl/Dockerfile)

For testing node-libcurl build below the steps to reply:
- Run docker container 
```docker run -u 0 -it meio/ubuntu:16.04-openssl-1.1.0i-curl-7.61.0 /bin/bash```  
- Download the test script on the container [here](https://rawgit.com/Meabed/32b3a79d6f48b28edbf65652bf9d43a3/raw/e3474c94cee4635b9c3685c22ba365afca56cfba/node-libcurl-ubuntu.sh) 
```wget -O n.sh https://rawgit.com/Meabed/32b3a79d6f48b28edbf65652bf9d43a3/raw/e3474c94cee4635b9c3685c22ba365afca56cfba/node-libcurl-ubuntu.sh```
- Run the script and watch the output 
```bash n.sh```
- Below the screen shot of the result 
<img width="1592" alt="screen shot 2018-08-23 at 3 34 01 am" src="https://user-images.githubusercontent.com/45731/44496645-69767700-a686-11e8-81fd-e31d55bf334c.png">

### note: if you install `npm i node-libcurl` without --build-from-source, it will use old version of curl which i think its bundled with the binary.
@JCMais maybe you should use the system curl if its available?

**Comment by JCMais** [comment]
@Meabed the prebuilt binaries are compiled with shared libraries

Probably the libs for the old libcurl version installed are having precedence over the new ones.

The prebuilts are always built with the latest version of libcurl at the time they are created, this takes into consideration the fact that libcurl versions are ABI compatible between themselves. The last major bump was on `7.16` which is not supported by this addon.

But still, I think it makes more sense to build the prebuilt binaries with static libraries instead, and leave shared ones only for `build-from-source`, but for that to work I need to allow the addon to be built with support for static builds.

**Comment by JCMais** [comment]
I've improved how the addon is built, now the prebuilt binaries are using static libraries instead of shared ones. For building from source, there is now the possibility to pass directly the path to the `curl-config`, or to specify the libraries / include dirs to use when building, see the Readme for details.

Those changes are currently only available on `node-libcurl@next`.

**Comment by meabed** [comment]
Thats awesome! thank you 👍
