### ISSUE TITLE
Login after Get request

### ISSUE THREAD

**Issue by niemes** [JCMais/node-libcurl#124]
Hi :),

I would like to know how can i post with the same curl object after a get request.

I try to login to my tumblr account using node libcurl, but i dont understand how to perform() multiple times after the first get request.

- get request to catch the form key in the body
- post the form to log in.
- redirect to the dashboard.
- get request etc... body

How to make a post request with the informations found in the first get request still alive.

Thx for your help ^^.

I'm using this exemple in php : [tumblr-messages](https://github.com/drJeckyll/tumblr-chat-messages-downloader/blob/master/tumblr.php)

**Comment by JCMais** [comment]
timing out
