### ISSUE TITLE
I am unable install in mac OSX

### ISSUE THREAD

**Issue by prasannavsa** [JCMais/node-libcurl#129]
node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.3.2/node_libcurl-v1.3.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.3.2 and node@10.4.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/JCMais/node-libcurl/releases/download/v1.3.2/node_libcurl-v1.3.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.3.2 and node@10.4.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! configure error

**Comment by JCMais** [comment]
Hi, there are no prebuilt binaries for node 10 yet, you need the develop version of libcurl installed locally to build from source (which it tries to do if it does not find a prebuilt binary). Most OSX should have those by default if you have xcode installed.

Can you try `npm add node-libcurl --build-from-source` and post here the results?

**Comment by maximandrewz** [comment]
@JCMais I have the same issue and it is building with `npm install node-libcurl --build-from-source`. But it would be great to have it without this flag as when you push it to the could it is not always possible to provide flags.

**Comment by JCMais** [comment]
Prebuilt binaries are now available for Node.js 10
