### ISSUE TITLE
Install fails on OSX 10.10.2

### ISSUE THREAD

**Issue by ZacheryPD** [JCMais/node-libcurl#13]
When using NPM to install the package, I get this error...  

``` 
[TheGrisk@Zachery-DeLong-DC] NodeJSCurl $ npm update
minimist@0.0.8 node_modules/http-server/node_modules/portfinder/node_modules/mkdirp/node_modules/minimist
minimist@0.0.10 node_modules/http-server/node_modules/optimist/node_modules/minimist
qs@2.3.3 node_modules/http-server/node_modules/union/node_modules/qs
[TheGrisk@Zachery-DeLong-DC] NodeJSCurl $ npm install node-libcurl
/
> node-libcurl@0.3.0 install /Users/TheGrisk/Development/tmp/NodeJSCurl/node_modules/node-libcurl
> node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild

Cannot find curl's header file.
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-libcurl"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.3.0 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libcurl@0.3.0 install script 'node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/TheGrisk/Development/tmp/NodeJSCurl/npm-debug.log
```

Has anyone else seen this issue?

**Comment by JCMais** [comment]
> Cannot find curl's header file.

Make sure you have libcurl devel package installed.

**Comment by babaskate** [comment]
I'm getting, an error, but different from above:

npm http GET https://registry.npmjs.org/node-libcurl
npm http 304 https://registry.npmjs.org/node-libcurl
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings

> node-libcurl@0.3.0 install /Users/ababaian/dev/sandbox/grunt-tenon/node_modules/node-libcurl
> node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild

  CXX(target) Release/obj.target/node-libcurl/src/node-libcurl.o
c++: error: unrecognized command line option '-stdlib=libc++'
make: *** [Release/obj.target/node-libcurl/src/node-libcurl.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ababaian/dev/sandbox/grunt-tenon/node_modules/node-libcurl
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! node-libcurl@0.3.0 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libcurl@0.3.0 install script.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "node-libcurl" "--save"
npm ERR! cwd /Users/ababaian/dev/sandbox/grunt-tenon
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.10
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ababaian/dev/sandbox/grunt-tenon/npm-debug.log
npm ERR! not ok code 0

**Comment by JCMais** [comment]
@babaskate you probably need to update gcc.

**Comment by babaskate** [comment]
I'm using gcc version 4.8.3 on Mac 10.9.5. Which version are you compiling with?  thanks.

**Comment by ZacheryPD** [comment]
@JCMais That's exactly what it was, thanks!  I totally forgot my machine had been re-provisioned and my  installed libraries were gone...  whoops...

**Comment by JCMais** [comment]
@babaskate Strange, the gcc you have looks good. Unfortunately I don't have a Mac to test what is going on.

On Debian 7 running gcc 4.7.2 I'm building just fine.

**Comment by JCMais** [comment]
Closing this as the issue was fixed.
If you still have some problem @babaskate, open a new issue.
