### ISSUE TITLE
build error Windows / Node.js 10 V8 version 6.4

### ISSUE THREAD

**Issue by john30** [JCMais/node-libcurl#132]
no gyp for this V8 version available and Windows build from source fails even though git.exe is in PATH:

> Error: Command failed: git clone --branch curl-7_57_0 https://github.com/JCMais/curl-for-windows.git
> Cloning into 'curl-for-windows'...
> fatal: BUG: initial ref transaction called with existing refs

However, a manual execution of the same command works just fine, but the build can't be completed anyway

**Comment by JCMais** [comment]
I need to do some testing on Node 10, didn't had time yet, probably will have some this weekend

**Comment by fortecasa** [comment]
Hello! Any update on this?

**Comment by JCMais** [comment]
Can you try again? I've added prebuilt binaries for Node 10.

**Comment by herly-js** [comment]
good job, i will try it again. thank you thank you.

**Comment by herly-js** [comment]
![image](https://user-images.githubusercontent.com/27951150/44070788-59b4fdca-9fb8-11e8-926f-c5f8aa1a8495.png)

**Comment by john30** [comment]
thanks for the binaries, I didn't have time yet to test on Node 10 though

**Comment by JCMais** [comment]
great
