### ISSUE TITLE
FTP list date parsing

### ISSUE THREAD

**Issue by john30** [JCMais/node-libcurl#133]
does not work for e.g. "Jun 25 12:01"

**Comment by JCMais** [comment]
Hi, thanks for reporting, do you have some code that can reproduce this issue?

You can use some public ftp servers to test.

**Comment by john30** [comment]
here is a little sample js code:
```
"use strict";
exports.__esModule = true;
var node_libcurl_1 = require("node-libcurl");
var test = function (host) {
    var handle = new node_libcurl_1.Easy();
    handle.setOpt(node_libcurl_1.Curl.option.FAILONERROR, true);
    handle.setOpt(node_libcurl_1.Curl.option.URL, "ftp://" + host + "/*");
    handle.setOpt(node_libcurl_1.Curl.option.WILDCARDMATCH, true);
    handle.setOpt(node_libcurl_1.Curl.option.CHUNK_BGN_FUNCTION, function (fileInfo) {
        if (fileInfo) {
            console.log('fileInfo.fileName', fileInfo.fileName);
            console.log('fileInfo.time', fileInfo.time);
            console.log('fileInfo.strings.time', fileInfo.strings ? fileInfo.strings.time : undefined);
        }
        return node_libcurl_1.Curl.chunk.BGN_FUNC_SKIP;
    });
    console.log('perform');
    var code = handle.perform();
    console.log('result code', code);
    handle.close();
};
test('ftp.rz.uni-wuerzburg.de');
```

the output currently produces this (selected lines only):
```
$ node test.js
perform
fileInfo.fileName MIRROR
fileInfo.time 1970-01-01T00:00:00.000Z
fileInfo.strings.time Jan 21  2017
...
fileInfo.fileName test
fileInfo.time 1970-01-01T00:00:00.000Z
fileInfo.strings.time Feb  9 14:34
...
result code 0
```
Expected result would be for "Feb  9 14:34" to be converted to the corresponding Date in 2018 and "Jan 21  2017" to January 21st 2017, both instead of fileInfo.time being "1970-01-01T00:00:00.000Z".

**Comment by JCMais** [comment]
Thanks for the code, I will be taking a look into that this week

**Comment by JCMais** [comment]
The addon is receiving `0` as time from libcurl, I've opened an issue there to get more info on why this is happening.

**Comment by JCMais** [comment]
Per https://github.com/curl/curl/issues/3829#issuecomment-488585976 this known, and not something that is expected to change anytime soon on libcurl, so my suggestion is to parse the date available on `strings.time`.

I'm not going to add this logic on the addon itself because it's more easily done on Javascript.

**Comment by john30** [comment]
ok thanks for your feedback
