### ISSUE TITLE
Installing on amazonlinux fails

### ISSUE THREAD

**Issue by lightcap** [JCMais/node-libcurl#134]
I'm trying to install node-libcurl in an amazonlinux docker container. `libcurl` and `libcurl-devel` are both installed. But the build process is bailing trying to link `libcurl-gnutls`. That package doesn't seem to be available for amazonlinux. 

For reference sake I'm using amazonlinux because I'm building `node-libcurl` to run on an AWS Lambda container.

Here's the relevant error:

```
> node-libcurl@1.3.2 install /cts-monitor-serverless/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build

[node-libcurl] Success: "/cts-monitor-serverless/node_modules/node-libcurl/lib/binding/node_libcurl.node" is installed via remote

> node-libcurl@1.3.2 postinstall /cts-monitor-serverless/node_modules/node-libcurl
> node scripts/postinstall

node-libcurl WARN Could not finish postinstall
node-libcurl ERR! Error: Command failed: node "/cts-monitor-serverless/node_modules/node-libcurl/lib/Curl.js"
module.js:604
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/cts-monitor-serverless/node_modules/node-libcurl/lib/Curl.js:28:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
```

**Comment by lightcap** [comment]
Also, I did try the solution in #128 but it didn't seem to help in my case.

**Comment by lightcap** [comment]
Okay, so running the `npm -i node-libcurl --build-from-source` on Node 8.10 (Lambda's latest version) it fails with:

```
bash-4.2# node -v
v8.11.3
bash-4.2# npm i node-libcurl --build-from-source
npm WARN eslint-config-airbnb-base@12.1.0 requires a peer of eslint@^4.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.12.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.
npm WARN cts-monitor-serverless@1.0.0 No repository field.

npm ERR! path /cts-monitor-serverless/node_modules/node-libcurl/node_modules/node-pre-gyp/node_modules/.http-signature.DELETE/node_modules/.bin
npm ERR! code ENOTEMPTY
npm ERR! errno -39
npm ERR! syscall rename
npm ERR! ENOTEMPTY: directory not empty, rename '/cts-monitor-serverless/node_modules/node-libcurl/node_modules/node-pre-gyp/node_modules/.http-signature.DELETE/node_modules/.bin' -> '/cts-monitor-serverless/node_modules/node-libcurl/node_modules/node-pre-gyp/node_modules/http-signature/node_modules/.bin'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-02T22_32_53_896Z-debug.log```

So, bottom line is that `--build-with-source` seems to work on Node 6.10, but fails on 8.10. 

Any thoughts? They both initially fail on install with the same error pointing to `libcurl-gnutls`. But then 6.10 can recover with `--build-from-source`.

**Comment by lightcap** [comment]
Actually, they will build on both platforms. The problem seems to be that if I don't `rm -rf node_modules/node-libcurl` after attempting a `npm install node-libcurl` and before trying `npm install node-libcurl --build-from-source` I get the error in the previous comment.

Removing the directory seems to clean things up and allow for the `--build-from-source`.

Is that expected? Or am I doing something wrong?

**Comment by JCMais** [comment]
Nop that is not expected, npm probably is not cleaning correctly the package before reinstalling. It's a good idea to always remove the package before reinstalling.

I will keep that open so I can remember to take a look into that later on, thanks for reporting.

**Comment by koskokos2** [comment]
prebuilt binding is built on TravisCI that is apparently Debian-based, so on non-Debian based repos like AMI or CentOS it may be required to do following:
`cd /usr/lib64 && ln -s libcurl.so.4 libcurl-gnutls.so.4`

It helped me to fix the same problem on CentOS 7.

**Comment by JCMais** [comment]
The prebuilt version of the addon is now static linked against their dependencies. This is fixed on `develop` branch and on `node-libcurl@next` version, which is going to become `v2` the following week.
