### ISSUE TITLE
npm install node-libcurl problem

### ISSUE THREAD

**Issue by Bek81** [JCMais/node-libcurl#14]
Hi,

I'm having a problem when installing the package. Previously this problem not occurred: about 1 month ago. Can you Help me, pls. It's really important and I hurry that works in PRODUCTION.

Tnx and regards.

p.s.: you can see the log below.
---------------------------

npm WARN engine node-libcurl@0.3.0: wanted: {"node":">= 0.8.0"} (current: {"node":"0.13.0-pre","npm":"2.7.4"})

> node-libcurl@0.3.0 install /var/www/kinder/microsite/backend/node_modules/node-libcurl
> node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild

Cannot find curl's header file.
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.13.0-pre
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.3.0 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@0.3.0 install script 'node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/kinder/microsite/backend/npm-debug.log
[Exit 1]

**Comment by JCMais** [comment]
> Cannot find curl's header file.
You need to install the libcurl devel packages.

Also,
> "node":"0.13.0-pre"
You are running node 0.13, which is not production ready, and this library is not tested with.

**Comment by Bek81** [comment]
Ok,
Thank you a lot JCMais!
