### ISSUE TITLE
What is correct way of using node-libcurl on macOS?

### ISSUE THREAD

**Issue by koskokos2** [JCMais/node-libcurl#144]
After cloning this repo and running tests I'm getting:

`module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: dlopen(/Users/$CURRENT_MAC_USER/Documents/node-libcurl/lib/binding/node_libcurl.node, 1): Library not loaded: /Users/travis/lib/libcurl.4.dylib`

As prebuilt library points to " /Users/travis/lib/libcurl.4.dylib". Here is output of otool -L:
`otool -L /Users/$CURRENT_MAC_USER/Documents/node-libcurl/lib/binding/node_libcurl.node
/Users/$CURRENT_MAC_USER/Documents/node-libcurl/lib/binding/node_libcurl.node:
	/opt/local/lib/libcurl.4.dylib (compatibility version 10.0.0, current version 10.0.0)
	/opt/local/lib/libidn2.0.dylib (compatibility version 4.0.0, current version 4.4.0)
	/opt/local/lib/libssh2.1.dylib (compatibility version 2.0.0, current version 2.1.0)
	/opt/local/lib/libpsl.5.dylib (compatibility version 9.0.0, current version 9.1.0)
	/opt/local/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)`

Of course after running "npm i --build-from-source" fixes it. But is there any reason to supply prebuilt library that will fail? And it is quite difficult to integrate into projects as just including node-libcurl into package.json is not enough and I need to run "npm i node-libcurl --build-from-source" explicitly. Am I'm getting something wrong and there is easy way to fix it? If not I would rather stop providing prebuilt library on mac and let it just build it from source by default or link statically or point node_libcurl.node to location where macports installed libcurl lives "/opt/local/lib/libcurl.4.dylib" (using install_name_tool)

**Comment by JCMais** [comment]
I've reopened https://github.com/JCMais/node-libcurl/issues/43  to track this.
