### ISSUE TITLE
Using libcurl while iterating an object has odd behavior.

### ISSUE THREAD

**Issue by AlexFrazer** [JCMais/node-libcurl#15]
```
_.each({
  "Node.js": {
    filename: somefilenamehere,
    url: someurlhere
  },
  "Electron Shell": {
    filename: somefilenamehere
    url: someurlhere
  }
}, function (requirement, name) {
  // pretty much a carbon copy of the progress bar example.
});
```

The output doesn't seem to work as expected.

<img src="https://i.stack.imgur.com/h1wmp.png" />

This is probably something I'm doing wrong, but what's the fix for this?

**Comment by JCMais** [comment]
Did you fixed the issue? I saw that you pushed some fixes to the script file.

**Comment by AlexFrazer** [comment]
yeah, needed the library's version of `-L` actually, was getting a redirect

**Comment by JCMais** [comment]
nice. Most of the libcurl options, so take a look at their docs http://curl.haxx.se/libcurl/c/curl_easy_setopt.html. I probably should add this to the Readme later, and the unsupported options too.

Closing, feel free to reopen it if the problem reappears.
