### ISSUE TITLE
Electron Windows and Mac

### ISSUE THREAD

**Issue by do-web** [JCMais/node-libcurl#152]
I have an electron app, i build the electron app on Mac, so the App works fine on Mac. 
I installed the extension from source because otherwise it is not working on Mac "npm install node-libcurl --build-from-source"

But now if i build the electron App for Windows the App is not working i get an error:

```
Error: \\?\C:\Users\IEUser\AppData\Local\Temp\8b7afd99-12e4-43ec-8c1e-d9a4523fbb46.tmp.node is not a valid Win32 application\\?\C:\Users\IEUser\AppData\Local\Temp\8b7afd99-12e4-43ec-8c1e-d9a4523fbb46.tmp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18
```

So it seems in the windows electron build there is no windows version of the node-libcurl module. So how i can solve the problem to get a build on mac for both systems?

**Comment by JCMais** [comment]
I don't think you can do that, you must have a Windows system available to do the build, you can try [appveyor](https://www.appveyor.com/) or installing a Windows VM on Mac.

**Comment by JCMais** [comment]
@do-web I'm closing this since there was no answer for a long period of time, in case you found a solution, feel free to post it here so it can help other users, in case you are still having problems, let me know.
