### ISSUE TITLE
Https requests in Windows

### ISSUE THREAD

**Issue by Martini-man** [JCMais/node-libcurl#160]
Olá JCMais,
´
I installed this in nodejs in windows and it works for http links but not for https ones.

I also have a mac and it works perfectly there.

Any idea why?

I tried already with nodejs x86 and x64 and have issues with both.

Also Curl.option.SSL_VERIFYHOST, 0 and Curl.option.SSL_VERIFYPEER, 0 don't help either.

Obrigado!

**Comment by JCMais** [comment]
@Martini-man sorry for taking too long to answer, I had completely missed this issue.

What version of node.js and this package were you using?

There is a current issue with node.js 10 that causes a segmentation fault when accessing anything with TLS on Windows. I trying to fix it right now.

**Comment by JCMais** [comment]
This was probably caused because of the segfault on newer versions of node, which is fixed on `develop` and on `node-libcurl@next`.
