### ISSUE TITLE
npm install --build-from-source breaks npm

### ISSUE THREAD

**Issue by rriggs** [JCMais/node-libcurl#161]
After installing with "npm install --build-from-source node-libcurl" on RHEL7 Linux (because I need OpenSSL), I can no longer install any other modules without first deleting node-libcurl and removing it from packages.json.

```
$ npm install --save client-sessions
npm ERR! path $PRJ/node_modules/node-libcurl/node_modules/abbrev
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '$PRJ/node_modules/node-libcurl/node_modules/abbrev' -> '$PRJ/node_modules/node-libcurl/node_modules/.abbrev.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     $USER/.npm/_logs/2019-02-05T19_54_37_287Z-debug.log

```

**Comment by JCMais** [comment]
@rriggs sorry for the long delay on answering this, missed the notification for this issue. Are you still having problems?

What version of npm, node.js and of the addon are you using?

**Comment by rriggs** [comment]
node 8.9.4, npm 5.6.0 and node-libcurl-1.3.3

**Comment by JCMais** [comment]
@rriggs I've tried again to reproduce this but no luck, can you try updating your version of npm?

**Comment by JCMais** [comment]
closing this for now, let me know if you still have issues
