### ISSUE TITLE
Building node-libcurl for electron on windows

### ISSUE THREAD

**Issue by king-alpha** [JCMais/node-libcurl#167]
Hi, I'm using a windows machine (x64) and I'm trying to get node-libcurl to work for my electron application, I followed the install command given in the documentation which is `npm install node-libcurl --runtime=electron --target=1.0.2 --disturl=https://atom.io/download/atom-shell --arch=x64 --save` and replaced the target version with the target version of electron that I was building for (in this case it was 2.0.17) and this is the error I keep getting any time I run the install command. `fatal error LNK1106: invalid file or disk full: cannot seek to 0x 29851C [D:\Code\share\node_modules\node-libcurl\build\node_libcurl.vcxproj]`
please, can anyone help me out on this?
![Screenshot (181)](https://user-images.githubusercontent.com/36765257/56358486-933f5980-6193-11e9-8fc3-62f08425f39b.png)

**Comment by JCMais** [comment]
@king-alpha looks like your disk is full, or almost full.

**Comment by king-alpha** [comment]
I'm sorry but my disk is not close to full at all. I still have 451 GB of space free. But I was able to get the installation to work after a long night of tweaking some values around and realised it only got installed when I changed the electron version to 4.0.0 but then my electron application couldn't run. I ll send a shot of the error soon

**Comment by king-alpha** [comment]
![Screenshot (182)](https://user-images.githubusercontent.com/36765257/57063740-13c48680-6c79-11e9-9280-d139340b7044.png)
I'm guessing electron was not expecting a dynamically linked library. But I'm really not sure of this error.

**Comment by JCMais** [comment]
@king-alpha could you provide a small sample code that reproduces this issue? Or the steps you took.

**Comment by king-alpha** [comment]
`const { app, ipcMain } = require('electron');
const { Curl } = require('node-libcurl'); //app crushes here

const { statusCode, data, headers } = await curl.get('http://www.google.com')`

**Comment by JCMais** [comment]
can you try the latest `next` version @king-alpha?

Tested it here and seems to work. Btw there are prebuilt binaries for electron now

**Comment by king-alpha** [comment]
Ow then I'm going to try the prebuilt binaries and get back to you with the feedback. But I'm not sure of what you mean by "next" version

**Comment by JCMais** [comment]
@king-alpha oh sorry about that, I meant `node-libcurl@next`, it's a prerelease version of v2.

Keep in mind it contains some breaking changes, check the [`README.md`](https://github.com/JCMais/node-libcurl/blob/0b35dac/README.md) on the develop branch.

**Comment by king-alpha** [comment]
Thank you for your time. My internet is really angry with me now so I ll check it up tomorrow and get back to you

**Comment by king-alpha** [comment]
Everything works well now. Bravo and many thanks for the help

**Comment by king-alpha** [comment]
I think the main problem was a starter template I was using known as electron-vue which handles the boilerplate code and setup for using vuejs with electron. [https://github.com/SimulatedGREG/electron-vue](url)

**Comment by king-alpha** [comment]
I downloaded the prebuilt binaries which works fine when using it with electron but fails with the same old message i used to create this issue [https://github.com/JCMais/node-libcurl/issues/167](url) wen using it with the starter template i was talking about

**Comment by JCMais** [comment]
great it's working great now!
