### ISSUE TITLE
installation node-libcurl failed on MacOS X

### ISSUE THREAD

**Issue by ivictor777** [JCMais/node-libcurl#168]
Hello, I'm trying to install node-libcurl to MacOS X 10.13.6 High Sierra

MacBook-Pro-Viktor:.node-red admin$ node -v
v12.0.0

MacBook-Pro-Viktor:.node-red admin$ yarn -v
1.13.0

MacBook-Pro-Viktor:.node-red admin$ yarn add node-libcurl

...

error /Users/admin/.node-red/node_modules/node-libcurl: Command failed.
Exit code: 1

...

9 warnings and 8 errors generated.
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/admin/.node-red/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/admin/.node-red/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/admin/.node-red/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/Users/admin/.node-red/node_modules/node-libcurl/lib/binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/admin/.node-red/node_modules/node-libcurl
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/admin/.node-red/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/admin/.node-red/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/Users/admin/.node-red/node_modules/node-libcurl/lib/binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/admin/.node-red/node_modules/node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1000:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/admin/.node-red/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/admin/.node-red/node_modules/node-libcurl
node-pre-gyp ERR! node -v v12.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /Users/admin/.node-red/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/admin/.node-red/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/Users/admin/.node-red/node_modules/node-libcurl/lib/binding --napi_version=4 --node_abi_napi=na

**Comment by ivictor777** [comment]
also I tried to install via npm:

MacBook-Pro-Viktor:.node-red admin$ npm -v
6.9.0

MacBook-Pro-Viktor:.node-red admin$ npm i node-libcurl --save
npm WARN rm not removing /Users/admin/.node-red/node_modules/.bin/semver as it wasn't installed by /Users/admin/.node-red/node_modules/semver
npm WARN rm not removing /Users/admin/.node-red/node_modules/.bin/pbjs as it wasn't installed by /Users/admin/.node-red/node_modules/protobufjs
npm WARN rm not removing /Users/admin/.node-red/node_modules/.bin/nopt as it wasn't installed by /Users/admin/.node-red/node_modules/nopt
npm WARN rm not removing /Users/admin/.node-red/node_modules/node-libcurl/node_modules/node-pre-gyp/node_modules/.bin/nopt as it wasn't installed by /Users/admin/.node-red/node_modules/node-libcurl/node_modules/node-pre-gyp/node_modules/nopt
npm WARN rm not removing /Users/admin/.node-red/node_modules/.bin/mime as it wasn't installed by /Users/admin/.node-red/node_modules/mime
npm ERR! path /Users/admin/.node-red/node_modules/node-libcurl/node_modules/.node-pre-gyp.DELETE/node_modules/.bin
npm ERR! code ENOTEMPTY
npm ERR! errno -66
npm ERR! syscall rename
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/admin/.node-red/node_modules/node-libcurl/node_modules/.node-pre-gyp.DELETE/node_modules/.bin' -> '/Users/admin/.node-red/node_modules/node-libcurl/node_modules/node-pre-gyp/node_modules/.bin'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-04-25T16_47_01_570Z-debug.log
MacBook-Pro-Viktor:.node-red admin$

**Comment by JCMais** [comment]
@ivictor777 the version on npm is not compatible with Node.js 12

In the meantime you should or use Node.js 10, or try one of the pre-releases of version 2 of the addon (it's experimental tho, so keep that in mind):
```
yarn add node-libcurl@next
```

**Comment by ivictor777** [comment]
Thanks for the quick response, I'll try with the 10th version later.

**Comment by JCMais** [comment]
Closing this as is a known incompatibility issue, if you have other issues feel free to reopen or open a new issue

**Comment by geo-dev-cr** [comment]
2020, till not working on Catalina OS f**k

**Comment by JCMais** [comment]
@geo-dev-cr feel free to elaborate on the issue you are having and if possible posting a sample scenario to reproduce the issue. If it's not exactly the same than the one reported here, open a new issue. 

Just commenting it's not working and saying the year is not going to help anyone.
