### ISSUE TITLE
Install fails on OSX if path has spaces

### ISSUE THREAD

**Issue by tomkerswill** [JCMais/node-libcurl#17]
Hi

If the path has spaces, the installation fails --- at least on OSX. Here's an example:

npm install node-libcurl

Gives this output:

node-libcurl@0.3.0 install /Users/myusername/installfolder (with spaces)/lambda/examplefolder/node_modules/node-libcurl
node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild

/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `node /Users/myusername/installfolder (with spaces)/lambda/examplefolder/node_modules/node-libcurl/tools/curl-config.js'
gyp: Call to 'node /Users/myusername/installfolder (with spaces)/lambda/examplefolder/node_modules/node-libcurl/tools/curl-config.js' returned exit status 2. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0

**Comment by JCMais** [comment]
Should be fixed in 0.4.0.
