### ISSUE TITLE
Arbitrary File Overwrite

### ISSUE THREAD

**Issue by madnight** [JCMais/node-libcurl#173]
![image](https://user-images.githubusercontent.com/10064471/57866119-15f11e00-77ff-11e9-8a9d-5a9eb75e59e5.png)

**Comment by JCMais** [comment]
Thanks for the report, this has been fixed on the next version, which is going to become v2 since it has many breaking changes, it's currently available on the next tag `node-libcurl@next`.

In case you are using yarn, you can overwrite node-gyp to the latest version by using package resolutions.
