### ISSUE TITLE
v2 Release

### ISSUE THREAD

**Issue by JCMais** [JCMais/node-libcurl#174]
What is missing for v2 release:

- [ ] ~Api Docs (probably can be added later on) - Depends on https://github.com/microsoft/web-build-tools/issues/1281~
- [x] Rewrite examples ~using Typescript~
- [x] Verify async wrapper behaves correctly
- [x] Add missing libcurl options
- [x] Review CHANGELOG.md
- [x] Review README.md

**Comment by JCMais** [comment]
I will leave the API docs for later, the examples should be self-documenting. If anyone has suggestions for the examples, let me know.

I will release v2 this weekend.

**Comment by gschier** [comment]
I just started working on an upgrade to v2 today. Everything seems to have gone smoothly and it only took a few minutes 😄  

The main thing I noticed with the migration is that some of the naming seems inconsistent now. For example, the change from `SSL_DATA_IN` became `SslDataIn` but most constants still remain in `UPPER_CASE` format? Will you be converting all constants to this new naming scheme?

Also related, I noticed you have `Curl.option` and `CurlAuth` which are also inconsistent in style.

---

Feel free to ignore this comment if it's still a work in progress. Looking forward to v2!

**Comment by JCMais** [comment]
hey @gschier, great to hear the upgrade was easy!

`Curl.option`, `Multi.option`, `Share.option` and `Curl.info` will keep their current casing, mostly to keep them almost exactly like the options on libcurl itself (basically just dropping the prefix, `CURLOPT`, `CURLMOPT`, etc).

The newly introduced symbols will be in `CamelCase`, like `CurlAuth`, the reason is that those are now Typescript enums, and that is the recommended convention for them: https://github.com/JCMais/node-libcurl/tree/develop/lib/enum (and I think it does looks nice)

*However*, there are a few exceptions I made to that convention, they are:
- `CurlCode`, `CurlMultiCode`, and `CurlShareCode`
  Those were previously on `Curl.code` (`Curl.code.CURLE_OK` become `CurlCode.CURLE_OK`), they are still using the `UPPER_CASE` casing to make it easier to look for them, since they are exactly like the constants defined on libcurl itself.
- `CurlProtocol` (previously `Curl.protocol`) -> `https://github.com/JCMais/node-libcurl/blob/32647acc28b026bbd03aa1e3abea9cbbc8f7d43b/lib/enum/CurlProtocol.ts`
  I felt it was weird to have the protocols on camel case.

**Comment by JCMais** [comment]
any others suggestions / issues found during the upgrade @gschier (or anyone that have upgraded)?

**Comment by JCMais** [comment]
v2 has been released! 🎉
