### ISSUE TITLE
POSTFIELDSIZE possible bug?

### ISSUE THREAD

**Issue by nayanbhana** [JCMais/node-libcurl#18]
Hi there, thanks for this awesome library. It is really cool!
I am currently sending a very large binary string in the POSTFIELD and when I don't set a POSTFIELDSIZE it truncates my binary string. So I set the POSTFIELDSIZE as my data.length and it sends a lot more of the binary string but it is still truncating the data.

**Comment by JCMais** [comment]
what is the length?

**Comment by nayanbhana** [comment]
2244. Is there a max length that I have missed?

**Comment by JCMais** [comment]
There is a limit of 2GB from libcurl (which can be exceeded using another option which this library don't support currently), also, Idk if you should you should use POSTFIELD for binary data. I'm looking into that.

Can you post a sample code that I can use to test this?

**Comment by JCMais** [comment]
Alright, just tested using POSTFIELD, and it works*

You just need to make sure you set the POSTFIELDSIZE **before** setting the POSTFIELD option.

**Comment by JCMais** [comment]
Timing out.
