### ISSUE TITLE
does node-libcurl support unvaild HTTP Token (colon in header) ? as follows:

### ISSUE THREAD

**Issue by huenchao** [JCMais/node-libcurl#184]
headers: {
        ':authority': 'www.site.com',
        ':method': 'GET',
        ':scheme': 'https',
        'referer': 'https://site.com',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36'
    }

**Comment by huenchao** [comment]
btw, i couldn't find an example for using http proxy in example dicts. anyone who can tech me how to use http proxy with it. thx in advance. :)

**Comment by JCMais** [comment]
This addons accepts most libcurl options, so you should be able to use https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

```
curl.setOpt("PROXY", "http://myproxy.com:80")
```

About the header, there is no special handling when sending headers, if it works with libcurl/curl, it should work with this addon
