### ISSUE TITLE
please add curl_infotype  enums  to   Curl.info.

### ISSUE THREAD

**Issue by ihgazni2** [JCMais/node-libcurl#188]
**ISSUE**:

    /*
        https://curl.haxx.se/libcurl/c/CURLOPT_DEBUGFUNCTION.html
        typedef enum {
            CURLINFO_TEXT = 0,
            CURLINFO_HEADER_IN,    /* 1 */
            CURLINFO_HEADER_OUT,   /* 2 */
            CURLINFO_DATA_IN,      /* 3 */
            CURLINFO_DATA_OUT,     /* 4 */
            CURLINFO_SSL_DATA_IN,  /* 5 */
            CURLINFO_SSL_DATA_OUT, /* 6 */
            CURLINFO_END
        } curl_infotype;
    
    */
    
    
    /*
    > Curl.info.hasOwnProperty("TEXT")
    false
    > Curl.info.hasOwnProperty("HEADER_OUT")
    false
    > Curl.info.hasOwnProperty("HEADER_IN")
    false
    > Curl.info.hasOwnProperty("DATA_IN")
    false
    > Curl.info.hasOwnProperty("DATA_OUT")
    false
    > Curl.info.hasOwnProperty("SSL_DATA_IN")
    false
    > Curl.info.hasOwnProperty("SSL_DATA_OUT")
    false
    > Curl.info.hasOwnProperty("END")
    false
    >
    
    */

**please add for debug  using, such as:**

        handle.setOpt(Curl.option.DEBUGFUNCTION, function(infotype_num,infotype_buffer) {
           if(infotype_num === Curl.info.HEADER_OUT) {      ////HERE  
               let req_headers  = infotype_buffer.toString()
               console.log("check the default req_headers:\n\n", req_headers)
           } 
           return(infotype_num)
        })

        var { Curl, CurlCode, Easy ,parseHeaders} = require('node-libcurl')
        
        Curl.info.TEXT = 0 
        Curl.info.HEADER_OUT = 2
        Curl.info.HEADER_IN = 1
        Curl.info.DATA_IN = 3
        Curl.info.DATA_OUT = 4
        Curl.info.SSL_DATA_IN = 5
        Curl.info.SSL_DATA_OUT = 6
        Curl.info.END = 7
        
        
        var handle = new Easy()
        url = "https://github.com/JCMais/node-libcurl"
        handle.setOpt(Curl.option.URL, url)
        handle.setOpt(Curl.option.VERBOSE,1)
        
        handle.setOpt(Curl.option.DEBUGFUNCTION, function(infotype_num,infotype_buffer) {
           if(infotype_num === Curl.info.HEADER_OUT) {      ////HERE  
               let req_headers  = infotype_buffer.toString()
               console.log("check the default req_headers:\n\n", req_headers)
           } 
           return(infotype_num)
        })
        
        var ret = Easy.strError(handle.perform())
        
        /*
        > var ret = Easy.strError(handle.perform())
        check the default req_headers:
        
         GET /JCMais/node-libcurl HTTP/1.1
        Host: github.com
        Accept: */*
        
        
        undefined
        >
        
        */

**Comment by JCMais** [comment]
This is already possible, see example: https://github.com/JCMais/node-libcurl/blob/develop/examples/12-debug-callback.js

**Comment by ihgazni2** [comment]
thx
