### ISSUE TITLE
unable to set request timeout

### ISSUE THREAD

**Issue by developuser** [JCMais/node-libcurl#190]
I had unable to set timeout for my curl request, so the curl is waiting for the response for the long time,which leads to memory leakage.

`    const Curl = require( 'node-libcurl' ).Curl;
    const curl = new Curl();
    const querystring = require('querystring')
    curl.setOpt('URL', url);
    curl.setOpt(Curl.option.CONNECTTIMEOUT, 5);

    curl.setOpt('FOLLOWLOCATION', true);
    if(isHeaderauthentication == 'TRUE'){
        curl.setOpt('HTTPHEADER', header);
    }
    if(postdata != ''){
        curl.setOpt('POSTFIELDS', JSON.stringify(postdata));
    }
    curl.on('end', (status, data) => {
        curl.close();
        if (status !== 200) {
            logger('INFO',"Requested Url:"+url+" postData"+JSON.stringify(postdata)+" Response:"+JSON.stringify(data));
            return callback(true,data); 
        }else{
            logger('INFO',"Requested Url:"+url+" postData"+JSON.stringify(postdata)+" Response:"+JSON.stringify(data));
            return callback(false,data);
        }
    });
    curl.on('error', error => {
        curl.close()
        logger('ERROR',"Requested Url:"+url+" postData"+JSON.stringify(postdata)+" Response:"+JSON.stringify(data));
        return callback(false,'');
    });

    curl.perform();`

**Comment by developuser** [comment]
@JCMais kindly give the suggestions regarding this issue

**Comment by JCMais** [comment]
@JCMais do you have a code I can run directly to reproduce the issue? It would help to identify the problem

**Comment by developuser** [comment]
i had used the above mentioned code,the problem that i faced was when i make a curl request to a another server, if it takes too much time to respond back means i want to forcibly end the request  as like request timeout in php curl library.

**Comment by JCMais** [comment]
There are tests for the `CONNECTTIMEOUT` option: https://github.com/JCMais/node-libcurl/blob/249323f0f3883f8cbf6d0e91a89bfecb5862da53/test/curl/connectionTimeout.spec.ts

It's working correctly, what might be happening is that probably the server is answering the TCP connection request but taking too long to return anything useful, in this case you are looking for the [`CURLOPT_TIMEOUT`](https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html) option.
