### ISSUE TITLE
Cannot install on nodejs 10.16.0

### ISSUE THREAD

**Issue by k0pernikus** [JCMais/node-libcurl#192]
When installing on a node@10.16 system, it fails via:

```
Arguments: 
Directory: /home/philipp/rate-pipeline/node_modules/node-libcurl
Output:
node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.3.2/node_libcurl-v1.3.2-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.3.2 and node@10.16.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/JCMais/node-libcurl/releases/download/v1.3.2/node_libcurl-v1.3.2-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.3.2 and node@10.16.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
```
Upgrading to a later node version (e.g. 10.16.3 or 11.15.0)  works, though it has been fine before.

I noticed this today by builds suddenly breaking, meaning it has been fine before.

**Comment by k0pernikus** [comment]
Now, also building against 10.16.3 fails too, but building on node@10.16.2 works. WTF.

```
error /home/philipp/rate-pipeline/node_modules/node-libcurl: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/philipp/rate-pipeline/node_modules/node-libcurl
Output:
node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.3.2/node_libcurl-v1.3.2-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.3.2 and node@10.16.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/JCMais/node-libcurl/releases/download/v1.3.2/node_libcurl-v1.3.2-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.3.2 and node@10.16.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/philipp/rate-pipeline/node_modules/node-libcurl/build'
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
```

Are you deleting old releases or may this be a github issue?

**Comment by JCMais** [comment]
You should use version `1.3.3`, version `1.3.3` has no pre built binaries for Node 10 (ABI 64), you can check that going to the release itself:
`1.3.3`: https://github.com/JCMais/node-libcurl/releases/tag/v1.3.3
`1.3.2`: https://github.com/JCMais/node-libcurl/releases/tag/v1.3.2

**Comment by k0pernikus** [comment]
@JCMais Thanks for the answer. What I found odd though is that it sometimes appears to be working, and sometimes it fails. My build pipeline, without any changes to the the github repository or the used node version, would just work the other day again without any incident.

I have created a [gist for the full log](https://gist.github.com/k0pernikus/57830942c6f0bccbd965c8cf8a1675bd).

I can confirm that I have `1.3.2` in my yarn.lock so I will try upgrading to the 1.3.3 version to see if the issues go away. Though I find this random behavior odd.

**Comment by JCMais** [comment]
Thanks for full log, the error seems to be this one:
```
sed: can't read ./Release/.deps/Release/obj.target/node_libcurl/src/Share.o.d.raw: No such file or directory
rm: cannot remove './Release/.deps/Release/obj.target/node_libcurl/src/Share.o.d.raw': No such file or directory
make: *** [node_libcurl.target.mk:112: Release/obj.target/node_libcurl/src/Share.o] Error 1
```

Which is probably related to the following `node-pre-gyp` issue: https://github.com/mapbox/node-pre-gyp/issues/426

`1.3.2` is a really old release, I recommend you to upgrade to the latest version, if that is not possible, you can try to force the latest version of `node-pre-gyp` using [yarn selective version resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/).

I'm closing the issue since there is nothing that can be done on the library itself.
