### ISSUE TITLE
Cannot convert undefined or null to object (10135 COOKIELIST)

### ISSUE THREAD

**Issue by insub** [JCMais/node-libcurl#194]
i try to setOpt cookielist but get the error:
"Cannot convert undefined or null to object (10135 COOKIELIST)"

my code like that:
```
setOpt(
     Curl.option.COOKIELIST,
     [
        cookie.httpOnly ? `#HttpOnly_${cookie.domain}` : cookie.domain,
        cookie.hostOnly ? 'FALSE' : 'TRUE',
        cookie.path,
        cookie.secure ? 'TRUE' : 'FALSE',
        expiresTimestamp,
        cookie.key,
         cookie.value
     ].join('\t')
 );
```
on node-licurl version 2.0.0-alpha.0 is fine, when i update node-licurl to 2.0.2 then get this error,
how to fix it?

**Comment by JCMais** [comment]
can you post the full error? If possible with some code that can reproduce the problem directly (that is, I can just run it directly and see the error)

**Comment by insub** [comment]
The code comes from a private function of about 1000 lines in an open source library.
I am trying to upgrade it from node-licurl version v2.0.0-alpha.0 to v2.0.2，These codes work fine on the 2.0.0-alpha.0 version. 
But these codes are difficult to separate and run separately.
I think I should close this issue and check other code again.

Anyway, Thank,
