### ISSUE TITLE
POST example fails

### ISSUE THREAD

**Issue by vomc** [JCMais/node-libcurl#195]
If I am using the POST example from the README verbatim (granted I know that the URL listed is not going to work), I get

```javascript

curl.setOpt(curl.option.URL, AUTH_URL);
                        ^

TypeError: Cannot read property 'URL' of undefined
```

To reproduce make a new file and paste in the example:

```javascript
const { Curl } = require('node-libcurl');

const curl = new Curl();
const close = curl.close.bind(curl);

curl.setOpt(curl.option.URL, AUTH_URL);
curl.setOpt(curl.option.HTTPPOST, [
    { name: 'input-name', file: '/file/path', type: 'text/html' },
    { name: 'input-name2', contents: 'field-contents' }
]);

curl.on('end', close);
curl.on('error', close);
```

And try to run it

**Comment by JCMais** [comment]
It should be `Curl.option`

**Comment by JCMais** [comment]
I will leave this open because the README needs to be fixed, feel free to submit a PR if you are able to.

**Comment by vomc** [comment]
Looks like it won't let me 😢 

```javascript
jochen@admins-MBP:~/Documents/node-libcurl$ git push origin readme-update
remote: Permission to JCMais/node-libcurl.git denied to vomc.
fatal: unable to access 'https://github.com/JCMais/node-libcurl.git/': The requested URL returned error: 403
```

**Comment by JCMais** [comment]
You have to fork this repository on your Github account and then push to some branch there, this way Github will give you the option to open a pull request.


You can also edit the Readme file directly from Github UI and it will do most of this automatically for you.
________________________________

**Comment by vomc** [comment]
Ah ok! Thanks! 👉  https://github.com/JCMais/node-libcurl/pull/199
