### ISSUE TITLE
Example showing how to set headers

### ISSUE THREAD

**Issue by vomc** [JCMais/node-libcurl#196]
I looked through issues including closed ones and was suprised that nobody asked before but how do you set headers? 

I tried using `curl.setOpt(Curl.option.HEADER, { 'Content-Type': 'application.json' })` and then running a request in verbose mode but it looks like the headers are not set...

I can't imagine this is the first time anybody has asked, please let me know where there are some docs on how to do this. It looks like none of the 19 examples that you have use headers at all?

**Comment by vomc** [comment]
Argg, that clearly was the wrong option... HEADER i guess just determines whether you include the headers in the body...

**Comment by JCMais** [comment]
This is a common misconception with libcurl itself, for more details on what each options does the official documentation for libcurl is the best resource: https://curl.haxx.se/libcurl/c/curl_easy_setopt.html

Almost all options are supported on this binding

**Comment by JCMais** [comment]
You are correct that it's missing some examples on how to setup headers, but it's like that:

https://github.com/JCMais/node-libcurl/blob/2bc06625f5bf13c04c64cc014ad82c25fecc8fb2/test/curl/callbacks.spec.ts#L140

**Comment by vomc** [comment]
Yeah that makes sense! Thanks for looking into it! Happy to submit a PR with an updated README.md if that helps...

was thinking just update
```javascript


curl.setOpt(Curl.option.URL, '127.0.0.1/upload.php');
curl.setOpt(Curl.option.HTTPPOST, [
    { name: 'input-name', file: '/file/path', type: 'text/html' },
    { name: 'input-name2', contents: 'field-contents' }
]);
```

and then maybe an example with header


#### Setting HTTP headers

Pass an array of strings specifying headers
```javascript
curl.setOpt(Curl.option.HTTPHEADER,
  ['Content-Type: application/x-amz-json-1.1'])
```

**Comment by JCMais** [comment]
Feel free to do so @vomc, that would be really great.
