### ISSUE TITLE
Alpine Prebuild binaries don't contain brotli

### ISSUE THREAD

**Issue by JohnnyCrazy** [JCMais/node-libcurl#200]
Hi,

Using the following Dockerfile with `node-libcurl@2.0.2` will result in a libcurl without brotli

```docker
FROM node:12.13.1-alpine

RUN apk add --update --no-cache git openssl

ENV APP_DIR=/code
WORKDIR $APP_DIR

COPY package.json $APP_DIR
COPY yarn.lock $APP_DIR
RUN yarn install
 
ADD . $APP_DIR
RUN yarn run build

CMD ["yarn", "run", "start"]
```

Version String from test:

```
console.log src/requesters/libCurl.js:37
    Version: libcurl/7.50.0-DEV OpenSSL/1.1.1d zlib/1.2.11 libssh2/1.8.2 nghttp2/1.38.0
    Protocols: dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
    Features: IPv6, Largefile, NTLM, NTLM_WB, SSL, libz, TLS-SRP, HTTP2, UnixSockets
```

I had a look at the CI scripts, but it seems like it should always be build with brotli support?

**Comment by JCMais** [comment]
You are correct, this was probably some caching issue, I have fixed it just for the Node.js 12 Alpine prebuilt images.

I will keep this open until the next release.

**Comment by JohnnyCrazy** [comment]
Does this also mean 2.0.3 will receive an up-to-date curl version for alpine? 7.50.0 is over 3 years old :sweat_smile:

**Comment by JCMais** [comment]
yes, actually it should have been built with 7.64.1, 7,50.0 is the minimum version the addon is tested against. The fixed prebuilt binary is already using 7.64.1.

**Comment by JohnnyCrazy** [comment]
Ah okay, got it. Do you have an ETA for 2.0.3?

**Comment by JCMais** [comment]
End of the week - mid of next week

**Comment by JCMais** [comment]
v2.0.3 has been released
