### ISSUE TITLE
Need to update Electron dependency

### ISSUE THREAD

**Issue by pranavwani** [JCMais/node-libcurl#207]
@JCMais Please update the electron dependency as Electron `v8.0.0` is released.

**Comment by pranavwani** [comment]
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@10.15.3 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/home/jsbot/development/Project/Firecamp/firesocket-react-extension/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.0-linux-x64-glibc.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.0-linux-x64-glibc.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.0-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.0.3 and electron@v8.0.0 (electron-v8.0 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.0-linux-x64-glibc.tar.gz 
gyp info it worked if it ends with ok

**Comment by pranavwani** [comment]
Throw following error, electron v8.0.0 with node-libcurl v2.0.3 not found
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@10.15.3 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/home/jsbot/development/Project/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.0-linux-x64-glibc.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.0-linux-x64-glibc.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.0-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.0.3 and electron@v8.0.0 (electron-v8.0 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.0-linux-x64-glibc.tar.gz 
gyp info it worked if it ends with ok

**Comment by pranavwani** [comment]
@JCMais Will, it takes time?

**Comment by JCMais** [comment]
I started to work on that last weekend, I will probably keep working on it this weekend, but cannot say if it's going to be finished by then.

**Comment by pranavwani** [comment]
> I started to work on that last weekend, I will probably keep working on it this weekend, but cannot say if it's going to be finished by then.

Thank you for your efforts, it really helps

**Comment by JCMais** [comment]
@pranavwani could you try the latest pre-release version? It can be installed using the `next` tag:
```
yarn add node-libcurl@next
```

If it works this version is going to become `2.1.0`

**Comment by pranavwani** [comment]
ok, I'll check and let you know.

**Comment by pranavwani** [comment]
@JCMais pre-release version is tested with electron version `8.1.0`. It works properly.👍️

**Comment by JCMais** [comment]
thanks for taking the time to test, I will release `2.1.0` by the end of this week

**Comment by pranavwani** [comment]
Thanks

Try to cover following options in testing:

**Method:**
- GET
- POST

**Request body**
- Multipart/form-data
- x-www-form-urlencoded
- JSON
- Text
- xml

**SSL**
- Option: `Curl.option.CAINFO` with `.PEM`
- Option: `Curl.option.PROXY_CAINFO` with `.PEM`

**Proxy**
- Option: `Curl.option.PROXY` with `https`

**Comment by JCMais** [comment]
@pranavwani as soon as I can I will add more tests, for now, I'm closing this as [v2.1.0](https://github.com/JCMais/node-libcurl/releases/tag/v2.1.0) (see the release page for full changelog) has been finally released. 🎉
