### ISSUE TITLE
NO_DATA_PARSING undefined moving from 1.3.3

### ISSUE THREAD

**Issue by obriankevin11** [JCMais/node-libcurl#210]
Hi,

I can't find the change logs thus can't find what I have to replace this with.

Could you help please?

Thank you

**Comment by JCMais** [comment]
Hi, sorry if the change log was not clear: https://github.com/JCMais/node-libcurl/blob/develop/CHANGELOG.md#breaking-change-1

On "Following members were moved to their own export" there is:
> Curl.feature -> CurlFeature
> ...
> And their fields were changed from SNAKE_CASE to PascalCase.

This means that `Curl.feature.NO_DATA_PARSING` is now `CurlFeature.NoDataParsing`.

`CurlFeature` can be imported normally from `node-libcurl`:
```
const { CurlFeature } = require('node-libcurl')
```

**Comment by JCMais** [comment]
Closing as it has been answered
