### ISSUE TITLE
System Proxy support

### ISSUE THREAD

**Issue by pranavwani** [JCMais/node-libcurl#211]
Is system proxy supported?

Currently library does not detect proxy set via environment variable(`http_proxy`).

**Comment by JCMais** [comment]
libcurl should detect this variable and use it, is that not working currently? Can you post some sample code / docker image?

**Comment by pranavwani** [comment]
I think this is not issue actually, it is happening because of different environment

When try from terminal using `curl` library

endpoint: `http://localhost:3001`
proxy_server: `http://localhost:8080`

while try to execute,
code: `curl -v  http://localhost:3001`
Verbose:
`* Uses proxy env variable http_proxy == 'http://localhost:8080/'
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET http://localhost:3001/ HTTP/1.1
> Host: localhost:3001
> User-Agent: curl/7.65.3
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-powered-by: Express
< content-type: text/html; charset=utf-8
< content-length: 5
< etag: W/"5-9/+ei3uy4Jtwk1pdeF4MxdnQq/A"
< date: Wed, 08 Apr 2020 14:10:05 GMT
< connection: close
< 
* Closing connection 0`

But when try to run code using `libcurl` from the vs code
code:
`const {Curl} = require("node-libcurl")

let curl = new Curl()

curl.setOpt(Curl.option.URL, 'http://localhost:3001')
curl.setOpt(Curl.option.VERBOSE, 1)
curl.on("end", (status, data) => {
  console.log(data);
})
curl.perform()`

Verbose: 
`*   Trying 127.0.0.1:3001...
* Connected to localhost (127.0.0.1) port 3001 (#0)
> GET / HTTP/1.1
Host: localhost:3001
User-Agent: node-libcurl/2.1.0-2
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: text/html; charset=utf-8
< Content-Length: 5
< ETag: W/"5-9/+ei3uy4Jtwk1pdeF4MxdnQq/A"
< Date: Wed, 08 Apr 2020 14:18:40 GMT
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact`

But try to run vs code from the terminal, than it uses system proxy

Verbose:
`* Uses proxy env variable http_proxy == 'http://localhost:8080/'
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET http://localhost:3001/ HTTP/1.1
Host: localhost:3001
User-Agent: node-libcurl/2.1.0-2
Accept: */*
Proxy-Connection: Keep-Alive

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-powered-by: Express
< content-type: text/html; charset=utf-8
< content-length: 5
< etag: W/"5-9/+ei3uy4Jtwk1pdeF4MxdnQq/A"
< date: Wed, 08 Apr 2020 14:25:21 GMT
< connection: close
< 
* Closing connection 0`

**Comment by JCMais** [comment]
Glad you figured it out. Closing as it's not an issue.
