### ISSUE TITLE
Fix NW.js latest versions build on Windows

### ISSUE THREAD

**Issue by JCMais** [JCMais/node-libcurl#212]
Currently throwing an error on Windows: https://ci.appveyor.com/project/JCMais/node-libcurl/builds/31615817

**Comment by sleepingforest20** [comment]
please compatible with Termux. node Linux 72 Android 64 unknown.

**Comment by JCMais** [comment]
I am not going to keep offering support for NW,js, unfortunately it is way too much effort.
