### ISSUE TITLE
Pre-built binaries not found for node-libcurl@2.1.0

### ISSUE THREAD

**Issue by carlovenus** [JCMais/node-libcurl#214]
Hi, i am unable to build my Meteor application due to

`node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.1.0/node_libcurl-v2.1.0-node-v57-darwin-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.1.0 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) `

Versions:

Node v8.12.0
Npm 6.4.1

node-libcurl is not a dependency of the application's package.json.
Any idea?
Thanks in advance

**Comment by JCMais** [comment]
This is just the warning, can you post the whole installation log?

Could you share the packages you depend on? `node-libcurl` is probably a dependency from one of them.

About the warning itself, there are no pre-built binaries for Node.js v8 because it's on End-of-Life: https://github.com/nodejs/Release#end-of-life-releases

**Comment by carlovenus** [comment]
Thanks for the quick reply.
The error log:

`CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
clang: error: no such file or directory: '/usr/include'
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/****/.meteor/packages/meteor-tool/.1.8.1-beta.2.5olksl.s1jm3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/****/.meteor/packages/meteor-tool/.1.8.1-beta.2.5olksl.s1jm3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/****/.meteor/packages/meteor-tool/.1.8.1-beta.2.5olksl.s1jm3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/****/Desktop/****/core/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/Users/****/Desktop/****/core/node_modules/node-libcurl/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /Users/****/Desktop/****/core/node_modules/node-libcurl
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/****/.meteor/packages/meteor-tool/.1.8.1-beta.2.5olksl.s1jm3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node /Users/****/.meteor/packages/meteor-tool/.1.8.1-beta.2.5olksl.s1jm3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/****/Desktop/****/core/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/Users/****/Desktop/****/core/node_modules/node-libcurl/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/****/Desktop/****/core/node_modules/node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/****/.meteor/packages/meteor-tool/.1.8.1-beta.2.5olksl.s1jm3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/****/Desktop/****/core/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/****/Desktop/****/core/node_modules/node-libcurl
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/****/.meteor/packages/meteor-tool/.1.8.1-beta.2.5olksl.s1jm3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node /Users/****/.meteor/packages/meteor-tool/.1.8.1-beta.2.5olksl.s1jm3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/****/Desktop/****/core/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/Users/****/Desktop/****/core/node_modules/node-libcurl/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
npm WARN @babel/cli@7.8.4 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-runtime@7.9.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-libcurl@2.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libcurl@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/****/.npm/_logs/2020-04-15T19_52_24_998Z-debug.log`

And the dependecies

```
  "dependencies": {
    "@babel/runtime": "^7.2.0",
    "@maxmind/minfraud-api-node": "1.0.0",
    "@reactioncommerce/authorize-net": "^1.0.8",
    "accounting-js": "^1.1.1",
    "autoprefixer": "^7.2.3",
    "autosize": "^3.0.20",
    "avalara-taxrates": "^1.0.1",
    "aws-sdk": "^2.470.0",
    "babel-runtime": "^6.26.0",
    "bcrypt": "^1.0.3",
    "body-parser": "^1.17.1",
    "bootstrap": "^3.3.7",
    "braintree": "^2.0.2",
    "bunyan": "^1.8.8",
    "bunyan-format": "^0.2.1",
    "bunyan-loggly": "^1.2.0",
    "chart.js": "^2.7.2",
    "checkout-sdk-node": "^1.0.0",
    "cheerio": "^1.0.0-rc.3",
    "classnames": "^2.2.5",
    "country-data": "0.0.31",
    "crypto-js": "^3.1.9-1",
    "css-annotation": "^0.6.2",
    "deep-diff": "^0.3.4",
    "dnd-core": "^2.2.3",
    "faker": "^4.1.0",
    "fibers": "^3.1.1",
    "flatten-obj": "^3.1.0",
    "font-awesome": "^4.7.0",
    "googleapis": "^29.0.0",
    "griddle-react": "^0.7.1",
    "handlebars": "^4.0.6",
    "html-pdf": "^2.2.0",
    "i18next": "^7.1.2",
    "i18next-browser-languagedetector": "^1.0.1",
    "i18next-localstorage-cache": "^0.3.0",
    "i18next-sprintf-postprocessor": "^0.2.2",
    "immutable": "^3.8.1",
    "jquery": "^3.1.1",
    "jquery-i18next": "^1.2.0",
    "js-md5": "^0.4.2",
    "later": "^1.2.0",
    "lodash": "^4.17.4",
    "lodash.pick": "^4.4.0",
    "mailchimp-api-v3": "^1.12.0",
    "meteor-node-stubs": "^0.4.1",
    "moment": "^2.17.1",
    "moment-timezone": "^0.5.11",
    "nexmo": "^1.2.0",
    "node-geocoder": "^3.16.0",
    "nodemailer": "^2.7.2",
    "nodemailer-wellknown": "^0.2.2",
    "npm-shrinkwrap": "^6.0.2",
    "object-to-xml": "^1.1.0",
    "paypal-rest-sdk": "^1.7.1",
    "phantom": "^6.2.0",
    "phone": "^1.0.10",
    "postcss": "^5.2.16",
    "postcss-js": "^0.3.0",
    "prerender-node": "^2.7.0",
    "radium": "^0.24.0",
    "react": "^15.4.2",
    "react-addons-create-fragment": "^15.4.2",
    "react-addons-pure-render-mixin": "^15.4.2",
    "react-autosuggest": "^8.0.1",
    "react-bootstrap": "^0.30.7",
    "react-color": "^2.11.1",
    "react-dnd": "^2.2.3",
    "react-dnd-html5-backend": "^2.2.3",
    "react-dom": "^15.4.2",
    "react-dropzone": "^3.10.0",
    "react-helmet": "^4.0.0",
    "react-komposer": "^2.0.0",
    "react-measure": "^1.4.5",
    "react-nouislider": "^1.14.2",
    "react-onclickoutside": "^5.9.0",
    "react-select": "^1.0.0-rc.3",
    "react-simple-di": "^1.2.0",
    "react-taco-table": "^0.5.0",
    "react-tether": "^0.5.5",
    "react-textarea-autosize": "^4.0.5",
    "request": "^2.88.0",
    "shippo": "^1.2.0",
    "sortablejs": "^1.5.0",
    "spiderable-middleware": "^1.4.2",
    "stripe": "^4.15.1",
    "sweetalert2": "^6.4.2",
    "swiper": "^3.4.1",
    "telesign": "git+https://github.com/SWinja/node-telesign.git",
    "tether-drop": "^1.4.2",
    "tether-tooltip": "^1.2.0",
    "transliteration": "^1.5.3",
    "twilio": "^2.11.1",
    "universal-analytics": "^0.4.16",
    "url": "^0.11.0",
    "utf8": "^2.1.2",
    "v8-profiler": "^5.7.0",
    "velocity-animate": "^1.4.3",
    "velocity-react": "^1.2.1",
    "xml2js": "^0.4.17"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.3",
    "babel-plugin-lodash": "^3.3.4",
    "babel-preset-stage-2": "^6.24.1",
    "browserstack-local": "^1.3.0",
    "chai": "^3.5.0",
    "eslint": "^3.16.0",
    "eslint-plugin-react": "^6.10.0",
    "js-yaml": "^3.8.1",
    "react-addons-test-utils": "^15.4.2",
    "wdio-allure-reporter": "^0.1.2",
    "wdio-mocha-framework": "^0.5.8",
    "webdriverio": "^4.6.2"
  },
```

FYI os is MacOS Mojave. Thanks in advance

**Comment by JCMais** [comment]
You will have to follow the instructions here: https://github.com/JCMais/node-libcurl#building-on-macos

Could you share a [gist](http://gist.github.com/) with your yarn.lock / package-lock.json?

**Comment by carlovenus** [comment]
Setting npm_config_curl_include_dirs="$(xcrun --show-sdk-path)/usr/include" as environment variable worked for me.
Thank you for the support!
