### ISSUE TITLE
Building on Electron causes NODE_MODULE_VERSION conflict

### ISSUE THREAD

**Issue by TaquitoSlayer** [JCMais/node-libcurl#217]
`npm_config_build_from_source=true npm_config_runtime=electron npm_config_target=v8.1.0 npm_config_disturl=https://atom.io/download/atom-shell npm_config_curl_include_dirs="$(xcrun --show-sdk-path)/usr/include" yarn add node-libcurl `

I ran this, as well as used the #develop branch, and I still get the following:

> internal/modules/cjs/loader.js:1208
>   return process.dlopen(module, path.toNamespacedPath(filename));
>                  ^
> 
> Error: The module './node_modules/request-curl/node_modules/node-libcurl/lib/binding/node_libcurl.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 76. This version of Node.js requires
> NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
> the module (for instance, using 'npm rebuild' or 'npm install').
> 

The only reason why I'm trying to build from source right now is because when using just electron like so:

> npm_config_runtime=electron npm_config_target=v8.1.0 npm_config_disturl=https://atom.io/download/atom-shell yarn add node-libcurl

it still tries to download the pre-built binary from v2.0.3, then gets a 404.

> Output:
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.13.0
> node-pre-gyp info using node@12.16.1 | darwin | x64
> node-pre-gyp WARN Using request for node-pre-gyp https download 
> node-pre-gyp info check checked for "./node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
> node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.1-darwin-x64-unknown.tar.gz
> node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.1-darwin-x64-unknown.tar.gz
> node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.1-darwin-x64-unknown.tar.gz 
> node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.0.3 and electron@v8.1.0 (electron-v8.1 ABI, unknown) (falling back to source compile with node-gyp) 
> node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-electron-v8.1-darwin-x64-unknown.tar.gz 

I've tried a few other things that aren't worth mentioning, but ultimately, to the best of my abilities, I can't get this to run.

OS: MacOS 10.14.6
Node version: v12.16.1

edit: tried electron-rebuild but it gives me that error of no such file or directory: '/usr/include', currently trying to see how to set that in electron-rebuild

**Comment by JCMais** [comment]
@TaquitoSlayer have you got it to work?

There are no prebuilt binaries for ELectron 8 on the `v2.0.3` version, I recommend you to use `v2.1.1` instead.
