### ISSUE TITLE
Installation error Cannot find curl's header file.

### ISSUE THREAD

**Issue by riksof-zeeshan** [JCMais/node-libcurl#22]
Hi,

Using Node version `v0.10.23`
When i run this command:
`npm install node-libcurl`
 
i get the following error:
Cannot find curl's header file.
npm ERR! node-libcurl@0.4.0 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libcurl@0.4.0 install script.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-34-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/piggybaq
npm ERR! node -v v0.10.23
npm ERR! npm -v 1.3.17
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/piggybaq/npm-debug.log
npm ERR! not ok code 0

**Comment by JCMais** [comment]
You need to Install the libcurl devel package.

**Comment by JCMais** [comment]
Timing out.
