### ISSUE TITLE
How to send ArrayBuffer

### ISSUE THREAD

**Issue by pranavwani** [JCMais/node-libcurl#229]
Description: How to send binary data, as Curl.option.POSTFIELDS` only allow sending `string` and `Curl.option.HTTPPOST` allow to sending the form data

Request Payload: 
```
{
  uuid: '7d0ce53d-a614-49e6-96d5-0d9054e82f46',
  method: 'post',
  url: 'http://localhost:3100/api/protobuf',
  params: {},
  headers: { 'Content-Type': 'application/octet-stream' },
  withCredentials: true,
  crossDomain: true,
  extra_config: {
    ignore_response_content_length: false,
    user_agent: '',
    request_timeout: '',
    ssl: { disable_ssl_validation: false },
    proxy: {},
    origin: '',
    follow_location: true,
    max_redirects: -1
  },
  data: Uint8Array [
    10,   6, 112, 114,
    97, 110,  97, 118
  ]
}
```

**Comment by JCMais** [comment]
Hi, you want to use the `READFUNCTION` function, an example with streams is available at https://github.com/JCMais/node-libcurl/blob/6695c91987c6d8a0782cb5a769fb208bf00fea8d/examples/08-file-upload-stream.js

**Comment by pranavwani** [comment]
Thanks, @JCMais for put attention on this query. I will try to implement as you suggested.

Specific reason to sending buffer over HTTP API is: request payload is encoded via `protobuf`. To keep the benefits of `protobuf` to sending binary data over HTTP API raised the query.

**Comment by JCMais** [comment]
No problem, please let me know if you have any issues

**Comment by JCMais** [comment]
@pranavwani I've added an example showing how to send binary data, like in your specific scenario, sending protobuf encoded data: https://github.com/JCMais/node-libcurl/blob/develop/examples/19-binary-data-protobuf.js

**Comment by pranavwani** [comment]
Thanks Jonathan for help.
