### ISSUE TITLE
Support for CURLMOPT_PUSHFUNCTION and CURLMOPT_PUSHDATA (http2 push functionality)

### ISSUE THREAD

**Issue by MoMannn** [JCMais/node-libcurl#232]
Bindings for above functionalities are not yet supported which are integral to a http2 client.

**Comment by JCMais** [comment]
I should be able to add some basic support for this feature in the following days.

The plan is to make it available in a pre-release version for `v2.2.0`, so it can be tested before being released.

**Comment by JCMais** [comment]
@MoMannn I've just added support for `CURLMOPT_PUSHFUNCTION`, sample code can be found at [`./examples/20-http2-server-push.js`](https://github.com/JCMais/node-libcurl/blob/develop/examples/20-http2-server-push.js)

For more documentation see the overloaded method documentation temporarily available here: https://jovial-kilby-4334c9.netlify.app/classes/_multi_.multi.html#setopt

Also, I've created a Discord server: https://discord.gg/3vacxRY

Feel free to join to discuss any issues / give feedback related to the implementation.

**Comment by JCMais** [comment]
Documentation's link is now https://develop--node-libcurl-docs.netlify.app/classes/_multi_.multi.html#setopt

**Comment by JCMais** [comment]
@MoMannn in case you have tried the feature, did it work as you expected?

Planning on releasing v2.2 tomorrow.

**Comment by MoMannn** [comment]
Not yet, will start working on it today.

**Comment by JCMais** [comment]
@MoMannn I've released `v2.2.0`, if you find any issues with this option feel free to create an issue. 👍
