### ISSUE TITLE
Add prebuilt binaries for Electron 9

### ISSUE THREAD

**Issue by gschier** [JCMais/node-libcurl#238]
Electron 9.0 is out, which means the prebuilt binaries should be updated to support it if possible 🥂 

https://www.electronjs.org/releases/stable?page=2#9.0.0

**Comment by gschier** [comment]
Note, we are currently upgrading Electron for [Insomnia](https://github.com/Kong/insomnia), which is how I noticed this. We can upgrade to 8 for now so the priority on this isn't major. Our team can also help with the effort if necessary 👍

**Comment by JCMais** [comment]
I should be able to do that tomorrow with the release of `v2.2`

**Comment by gschier** [comment]
Awesome, thanks @JCMais! 🙏

**Comment by JCMais** [comment]
@gschier `v2.2.0` with prebuilt binaries for Electron v9 has been released, it should take a while until all binaries are available though.

**Comment by gschier** [comment]
Thanks @JCMais. Should it be 9.1 instead of 9.0, however?

**Comment by JCMais** [comment]
You are right, I will submit the binaries again

**Comment by gschier** [comment]
Nice, thanks!
