### ISSUE TITLE
Are any debug mode to print the exact curl command that was executed?

### ISSUE THREAD

**Issue by RodolfoGS** [JCMais/node-libcurl#242]
Exists an option like "debug mode" to print the exact curl command that was executed?

I tested with `curl.setOpt(Curl.option.VERBOSE, 1);` but I need print the exact command that was executed.

For example:
```
curl 'https://example.com' \
  -H 'User-Agent: Browser/1.0' \
  -H 'Accept: text/html,application/json' \
  -H 'Connection: keep-alive' \
  --compressed
```

**Comment by JCMais** [comment]
Hi, the `curl` tool is different than the [`libcurl`](https://curl.haxx.se/libcurl/) C library. The `curl` tool uses `libcurl` internally. 

This addon allows Node.js to call into libcurl functions directly, it does not use the `curl` binary, but C library directly, so having a debug method as you mentioned is not possible. You can build such output by keeping track of every option you have set and building the command-line arguments yourself if needed.
