### ISSUE TITLE
Windows Build Failed

### ISSUE THREAD

**Issue by MaisumAbbas** [JCMais/node-libcurl#243]
Everytime I try to install node_libcurl on windows using visual studio code, it throws an error:

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.2.0/node_libcurl-v2.2.0-node-v79-win32-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.2.0 and node@13.9.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)

Error: Command failed: cd curl-for-windows && git submodule update --init && python configure.py
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found

gyp: Call to 'node "C:\Users\Maisum Abbas\node_modules\node-libcurl/tools/retrieve-win-deps.js"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Maisum Abbas\AppData\Roaming\npm\node_modu
les\npm\node_modules\node-gyp\lib\configure.js:351:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)    
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Maisum Abbas\\AppData\\Roamin
g\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Maisum Abbas\\node_modules\\node-libcurl\\lib\\binding\\node_libcurl.node" "--module_name=node_libcurl" "--module_path=C:\\Users\\Maisum Abbas\\node_modules\\node-libcurl\\lib\\binding" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd C:\Users\Maisum Abbas\node_modules\node-libcurl
gyp ERR! node -v v13.9.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
    node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Mais
um Abbas\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Maisum Abbas\node_modules\node-libcurl\lib\binding\node_libcurl.node --module_name=node_libcurl --module_path=C:\Users\Maisum Abbas\node_modules\node-libcurl\lib\binding --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Maisum Abbas\node_modules\node
-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:28
6:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Maisum Abbas\\node_m
odules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Maisum Abbas\node_modules\node-libcurl
node-pre-gyp ERR! node -v v13.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Maisum Abbas\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\
node-gyp.js configure --fallback-to-build --module=C:\Users\Maisum Abbas\node_modules\node-libcurl\lib\binding\node_libcurl.node --module_name=node_libcurl --module_path=C:\Users\Maisum Abbas\node_modules\node-libcurl\lib\binding --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Maisum Abbas\package.json'
npm WARN Maisum Abbas No description
npm WARN Maisum Abbas No repository field.
npm WARN Maisum Abbas No README data
npm WARN Maisum Abbas No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-libcurl@2.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Maisum Abbas\AppData\Roaming\npm-cache\_logs\2020-08-25T06_30_30_258Z-debug.log

Also, I didn't find this file node_libcurl-v2.2.0-node-v79-win32-x64-unknown.tar.gz in the releases section. 

I am also new to node.js so don't know much about it.

**Comment by JCMais** [comment]
There are no prebuilt binaries for Node.js v13, so the addon is falling back to building from source.

The error you are getting is related to Git:
```
Error: Command failed: cd curl-for-windows && git submodule update --init && python configure.py
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found
```

So you have two options, use Node.js v14, which has prebuilt binaries available, or try to fix the error you are getting (Looks like it's related to this: https://stackoverflow.com/questions/49256190/how-to-fix-git-sh-setup-file-not-found-in-windows)

**Comment by MaisumAbbas** [comment]
I first tried the v14 but it was taking too long to get any response. So I tried the given link and added the env variables to Path and it worked. Thank you so much.
