### ISSUE TITLE
Limit file size download

### ISSUE THREAD

**Issue by gsouf** [JCMais/node-libcurl#245]
We are running node-libcurl in docker containers with limited amount of memory (ie 128MB). 

We have issues we curl downloads files larger than the memory available. It seems to buffer the full file in memory and pushes the container to go OOM. We would need to be able to limit the amount of data that curl is allowed to download.

I see the existence of the option [maxfilesize](https://curl.haxx.se/libcurl/c/CURLOPT_MAXFILESIZE.html). However the doc says it's not guaranteed to work:

> The file size is not always known prior to download, and for such files this option has no effect even if the file transfer ends up being larger than this given limit

Do we have some ways to workaround this?

**Comment by JCMais** [comment]
This is the default way data is handled, as most of the time clients would be using the library to access APIs or other text-based responses.

However this does not work great with binary/bigger files. For that, you probably are better off using your own data handling, this can be done two ways:

- enabling the `Raw` flag: `curlHandle.enable(CurlFeature.Raw)`
  Doing that the data argument passed to the `end` event will be a raw `Buffer`
- Setting the `WRITEFUNCTION` option to your own callback and handling each data chunk yourself.

The first one above would still not work for your use case, as all the data coming in would be added to the internal buffer. If you have memory limitations you must use the second option.

Inside the `WRITEFUNCTION` you can control if libcurl should keep receiving data or not, the idea is the same than the original [`CURLOPT_WRITEFUNCTION`](https://curl.haxx.se/libcurl/c/CURLOPT_WRITEFUNCTION.html) option. For a simple example see [`./examples/16-ftp-download.js`](https://github.com/JCMais/node-libcurl/blob/3c341e1b74ac362f2136c61e8ca5a5bb602919f4/examples/16-ftp-download.js)

**Comment by gsouf** [comment]
@JCMais amazing thank you, I'm going to try those. Does the `WRITEFUNCTION` approach allows to access http headers before body is received?

**Comment by JCMais** [comment]
you can also use `HEADERFUNCTION` to capture the headers the same way.

**Comment by gsouf** [comment]
@JCMais thanks you're a rockstar 👨‍🎤

I figured out that all that stuff is native curl stuff. I came up with a solution more tailored to my needs and here is my humble contribution to anyone who would also struggle with download limits.

What I do instead of using the propose `WRITEFUNCTION` is to use `XFERINFOFUNCTION`. It allows to abort the transfer as soon as the download size exceed a value of our choice.  It throws and error with code `42` that I catch and use `curl.getInfo` to get the status code, that is the only thing I'm interested in in that case:

```js
        // disable curl storage to avoid OOM issues
        curl.enable(CurlFeature.Raw | CurlFeature.NoStorage)

        // NOPROGRESS = 0 is required to get XFERINFOFUNCTION to work
        curl.setOpt(Curl.option.NOPROGRESS, 0);

        // listen to transer progress
        curl.setOpt(Curl.option.XFERINFOFUNCTION, (downloadSize, downloaded, uploadSize, uploaded) => {
            // abort as soon as we downloaded more than 1024 bytes
            if (downloadSize > 1024) {
                return -1;
            } else {
                return 0;
            }
        });

        // handle error throwed when interrupted via XFERINFOFUNCTION
        curl.on('error', (error, errorCode) => {
            // 42 is for CURLE_ABORTED_BY_CALLBACK
            if (42 === error) {
                const statusCode = curl.getInfo(Curl.info.RESPONSE_CODE);
            }
        });
```

**Comment by JCMais** [comment]
Oh, that is much better!

Thanks for posting the full solution. Feel free to open another issue if you have any other questions.
