### ISSUE TITLE
Silent exit of node.js

### ISSUE THREAD

**Issue by mjgp2** [JCMais/node-libcurl#246]
I have a situation where I am using Multi/Easy and node.js is exiting with a zero exit code randomly on both OSX and docker when using curl multi. I have tried node 14 and 12. I have tried the bundled binary and building from source via the `npm install` flag.

There is no details of any segfault, no uncaught exceptions and no unhandled rejections.

It happens randomly right after calling `multi.addHandle(easy)` (the log statement immediately after is not reached).

It happens no matter if there are 1, 10 or 100 concurrent requests.

Everything is working just fine up to that point.

I am stumped.

I am trying to get together a covering example currently, but wanted to ask if there is any insight to help me debug that can be offered.

**Comment by JCMais** [comment]
I cannot think of anything that would cause this. Please provide a Dockerfile that can reproduce it and I will happily take a look.

**Comment by mjgp2** [comment]
Yes, I hope to provide in the next few days. Thanks for the reply!

**Comment by mjgp2** [comment]
This is a node.js issue, I have pinpointed it and will try to file upstream bug. Closing this.
