### ISSUE TITLE
Easy not setting default user agent?

### ISSUE THREAD

**Issue by avie** [JCMais/node-libcurl#248]
I'm using Easy and ran into a problem where a website was rejecting requests.  I had old code using Curl that worked fine.  After comparing the network traffic I noticed that Easy was not sending a user-agent (!).  I manually set the USERAGENT and lo and behold it was sent and worked just like when using Curl.

It is possible Easy isn't setting a default user-agent?

**Comment by JCMais** [comment]
Hi!

Using the Easy interface directly does not set anything on the request by default. You must do that manually. This is the way libcurl also works

The Curl interface (which is also used by the curly.[method] functions) on the other hand, sets a default user agent: https://github.com/JCMais/node-libcurl/blob/70805fe19b937f2873643e20d90e1cd9cd77e3f7/lib/Curl.ts#L174-L182

I'm not willing to add a default user agent to the Easy interface as this would be different from the way libcurl works natively.

**Comment by avie** [comment]
Good to know.  Is there perhaps a list of other differences like this one?  I'm starting to repurpose some Curl code as Easy code to get easy synchronous operation and am a bit worried there might be other pitfalls!

**Comment by JCMais** [comment]
By saying Curl do you mean the command-line tool or using the C library libcurl?

If using `libcurl` directly, the Easy interface should be almost exactly the same than using the `curl_easy_*` functions, there are a few options that are not supported, but those are mostly related to stuff that is easy to do with JS directly or too hard to put into this binding.  For a full-list go here: https://github.com/JCMais/node-libcurl/blob/70805fe19b937f2873643e20d90e1cd9cd77e3f7/scripts/utils/curlOptionsBlacklist.js

Now if you mean the Curl tool, then there are probably a few options that it sets by default when doing requests, like the User-Agent header you mentioned. 

What I would recommend in this case is to use the `--libcurl` option as it allows you to get a "almost complete" C code for the command you tried to run with `curl`. From there you should be able to see almost all options it's using, and then convert that to Node.js.

**Comment by avie** [comment]
Yep, I meant the Curl interface (in node-libcurl)!  It also looks like Cookie handling might be different.  Still debugging though.

**Comment by JCMais** [comment]
If you want to see what is the default `HEADERFUNCTION` / `WRITEFUNCTION` being used by the `Curl` interface, here are they:

https://github.com/JCMais/node-libcurl/blob/70805fe19b937f2873643e20d90e1cd9cd77e3f7/lib/Curl.ts#L305-L331

The `Curl` interface uses an internal `Multi` handle to take care of the internal `Easy` ones, here is their callback:
https://github.com/JCMais/node-libcurl/blob/70805fe19b937f2873643e20d90e1cd9cd77e3f7/lib/Curl.ts#L77-L92

And here is the `onEnd` being called in there:
https://github.com/JCMais/node-libcurl/blob/70805fe19b937f2873643e20d90e1cd9cd77e3f7/lib/Curl.ts#L356-L394

This is the place where the data is converted from `Buffer` to `string` and the headers are parsed.

**Comment by JCMais** [comment]
Closing this as looks the original issue was resolved. Feel free to open a new one if you have any other issue.
