### ISSUE TITLE
Doesn't build on Node 15

### ISSUE THREAD

**Issue by ronag** [JCMais/node-libcurl#256]

**Comment by alexandrucancescu** [comment]
For me it doesn't even build on node 14, on macos. A more detailed install instructions are needed for macos. Where can we download all the static libs that we need?

**Comment by JCMais** [comment]
Post the full build log here if possible.

**Comment by alexandrucancescu** [comment]
OS 11 Big Sur
nodejs v.14.15.1

Ran `npm_config_curl_include_dirs="$(xcrun --show-sdk-path)/usr/include" npm i -s node-libcurl@latest`

```
[node-libcurl] Success: "/Users/andu/dev/webstorm/cb-scraper/node_modules/node-libcurl/lib/binding/node_libcurl.node" is installed via remote
node-libcurl WARN Could not finish postinstall 
node-libcurl ERR! Error: Command failed: node "/Users/andu/dev/webstorm/cb-scraper/node_modules/node-libcurl/dist/index.js"
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/andu/dev/webstorm/cb-scraper/node_modules/node-libcurl/lib/binding/node_libcurl.node, 1): Library not loaded: /usr/local/opt/zstd/lib/libzstd.1.dylib
  Referenced from: /Users/andu/dev/webstorm/cb-scraper/node_modules/node-libcurl/lib/binding/node_libcurl.node
  Reason: image not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/andu/dev/webstorm/cb-scraper/node_modules/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
 
+ node-libcurl@2.3.0
added 104 packages from 78 contributors and audited 300 packages in 8.542s
```

postinstall script fails. Can import module but it will throw the same error, about libzstd.

**Comment by alexandrucancescu** [comment]
Managed to build it on node 14 macos big sur. The problem was I installed curl witt `brew install curl`, and was missing libzstd I suppose. The correct way to install libcurl to be able to build node-libcurl is `brew install curl-openssl`. I think it would be a good idea to add this in the **Building on macOS** section, like in the linux section, that has the commands to install the lib dependencies.

Also using the instructions in the README I was able to install node-libcurl for node 15 on ubuntu server 18.

**Comment by JCMais** [comment]
This is strange, the addon should use the prebuilt binaries on macOS for Node.js v14, weird that it was trying to build from source.

I will try to find some time to build on macOS big sur and check if there is anything wrong.

**Comment by Nishchit14** [comment]
@JCMais I am facing the same issue as @alexandrucancescu's but on `macOS Catalina` with NodeJS 12 and 14 both. I'll be watching this thread, Thank you for your awesome work man!!.

**Comment by Nishchit14** [comment]
installing `brew install curl-openssl` worked for me. Thanks @alexandrucancescu

**Comment by alexandrucancescu** [comment]
Can we add this on instructions for building on mac?

**Comment by JCMais** [comment]
I will add then after I test installing the library myself, as this may be something wrong with the build process itself, it should not really need an external library as the addon is built statically.

**Comment by ronag** [comment]
Fixed my build issues:

https://github.com/nxtedition/node-libcurl/commit/101475c99915378ef5e9e7eb743ea0ab3a948bf8

**Comment by JCMais** [comment]
I suppose you also had to install libcurl manually @ronag ?


I just updated to Big Sur, looks like the libcurl shared library is not provided anymore, or it's in another place now.

**Comment by RyzorBent** [comment]
installing ```brew install curl-openssl``` also worked for me.

**Comment by JCMais** [comment]
Thanks to everyone that contributed to this issue.

I'm closing the issue as it is, in fact, the same issue than https://github.com/JCMais/node-libcurl/issues/274

The pre-release version `v2.3.1-0` has support for Node.js 15 and has the above dependency issue fixed. If everything is working correctly I will publish `v2.3.1` late today / tomorrow.
