### ISSUE TITLE
NODE_MODULE_VERSION issue node 12.16.3

### ISSUE THREAD

**Issue by liben96** [JCMais/node-libcurl#257]
Hi,
After installing v.2.2.0 by using 'npm install' or 'yarn', I am facing the following error:

Error: The module '/home/prov-dev/umee-provisioning/umee/node_modules/node-libcurl/lib/binding/node_libcurl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing

I'm using node version 12.16.3.

Any ideas?
Thanks

NOTE: I have also tried different versions of Node (10.16.3 and 14.4.0) and different vesions of the node-libcurl library (2.1.3) and I always get the same error... the only thing that is change in the error is the number (NODE_MODULE_VERSION XXX)

**Comment by JCMais** [comment]
Are you sure you are using Node.js v12 to run your code? `NODE_MODULE_VERSION 64` is the version for Node.js 10, while the addon was built for version 12 (ABI 72).

**Comment by liben96** [comment]
Thanks for your answer.
Yes, i am 100% sure that i am using node v12 (see the image attached).

I am using nvm and i have tried different versions of node (10, 12 and 14 - last one). You can see the error highlighted in red.[](url)

![node-lib-curl](https://user-images.githubusercontent.com/11990892/98378049-d139f200-2045-11eb-8738-5f5ddc2be486.png)

**Comment by JCMais** [comment]
Can you run `console.log(process.versions)` right above the code you are requiring node-libcurl?

**Comment by liben96** [comment]
This is what I get:

 { http_parser: '2.8.0',
  node: '10.6.0',
  v8: '6.7.288.46-node.13',
  uv: '1.21.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/xxxxx/node_modules/node-libcurl/lib/binding/node_libcurl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Any ideas how I can fix it? Thanks

**Comment by JCMais** [comment]
I'm closing as this is not really an issue with this library.

Now related to the issue you are seeing, make sure that forever is using the correct version of Node.js you want it to use. 

This could be helpful: https://stackoverflow.com/questions/16229921/forever-with-two-node-versions-installed-specify-a-node-version-to-run-with

Keep in mind that the shell forever uses probably does not have nvm setup, so it's using the default node.js available in the system, which in your case is Node.js v10.
