### ISSUE TITLE
How to disable proxy username caching?

### ISSUE THREAD

**Issue by alexandrucancescu** [JCMais/node-libcurl#258]
I have to change the username when using a proxy server, after every request, but libcurl or node-libcurl addon seems to cache it, as it send the same username even after I change it.

When using curly I tried every option
```javascript
// changing the proxy option
curlOptions.proxy = `${options.proxy.auth}@${options.proxy.host}:${options.proxy.port}`;
// changing only the username
curlOptions.proxyUsername = options.proxy.auth;
//changing userpwd
curlOptions.proxyUserpwd = options.proxy.auth;
```
I also tried using a new Curl instance every time I need to change proxy username
```javascript
const curl = new Curl()
curl.setOpt("PROXY",proxy)
curl.setOpt("SSL_VERIFYPEER", false);
```

All of them produce the same result, and node-libcurl will keep sending the first proxy username every time.
Is there any solution, or workaround to force libcurl to update the username?

**Comment by JCMais** [comment]
If you are using a new instance or just setting the option to null, it should not cache the option. Can you post the output of running this function? https://node-libcurl-docs.netlify.app/classes/_lib_curl_.curl.html#getversioninfostring

Also, try running with the `VERBOSE` option set to `true` and see if there is any interesting output related to this.

**Comment by alexandrucancescu** [comment]
Version: libcurl/7.73.0 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 zstd/1.4.5 c-ares/1.16.1 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
Protocols: dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Features: AsynchDNS, IDN, IPv6, Largefile, NTLM, NTLM_WB, SSL, libz, brotli, TLS-SRP, HTTP2, UnixSockets, HTTPS-proxy

**Comment by alexandrucancescu** [comment]
I'm pretty sure it gets cached. I use a service that changes my IP based on the proxy username, and changing the username in node-libcurl doesn't produce this result. This service also provides a self hosted proxy, where I can analyse the username that gets sent, and it's the same for 5-6 more requests after I change it. I tested with 5 more http clients and they do not have this behaviour. Do you think it is from the node addon or the library? I've read somewhere that it is common for some http clients to cache the proxy username.
I am not too familiar with CONNECT method that is used for proxy forwarding, but another think I suspect is that maybe curl makes multiple requests through the same proxy connection.

**Comment by JCMais** [comment]
The only way to be completely sure is to make a simple application using libcurl itself. No special handling of the proxy options is done by this addon.

Can you check if the same happens when using just the `Easy` class (synchronous way)?

Another option is to try to build a simple C program and see if the same issue happens with pure libcurl: https://curl.se/libcurl/c/simple.html

**Comment by emredalka** [comment]
FRESH_CONNECT true option resolves the proxy problem
