### ISSUE TITLE
Is there any example of how it works in the code applying proxy?

### ISSUE THREAD

**Issue by Oseias447** [JCMais/node-libcurl#261]
In Lib it says that there is proxy support, but I haven't found any example of how to apply the proxy.

**Comment by JCMais** [comment]
This library supports all options libcurl supports related to Proxies (https://ec.haxx.se/libcurl/libcurl-proxies), The main option related to proxy support is [`CURLOPT_PROXY`](https://curl.se/libcurl/c/CURLOPT_PROXY.html) and it's fully supported. You just need to set the option using `setOpt`:
```
// ...
curl.setOpt('PROXY', 'http://user:pass@proxy:80')
```

 or inside the `options` param passed to `curly`:
```
// ...
const { data } = await curly.get('some-url', {
  proxy: 'http://user:pass@proxy:80'
})
```

If this is not working, then there is a bug.
