### ISSUE TITLE
Support electron 11.x.x

### ISSUE THREAD

**Issue by xland** [JCMais/node-libcurl#270]
When could node-libcurl support electron 11.x.x?
Thanks!

**Comment by JCMais** [comment]
Right, I should be able to add Electron `11.x.x` by the end of this week.

**Comment by JCMais** [comment]
The pre-release version `v2.3.1-0` has support for Electron 11 and Electron 12, could you test, please?

If everything is working correctly I should be able to release `v2.3.1` late today / tomorrow.

Sorry that this took a while to get added. 😅

**Comment by xland** [comment]
Sorry, I'm not working on this now.

**Comment by JCMais** [comment]
`v2.3.1` has been released with support for Electron v11 and v12
