### ISSUE TITLE
Request receive headers only

### ISSUE THREAD

**Issue by creazy231** [JCMais/node-libcurl#276]
I want to build a small monitoring tool for my company to use it internally.
Everything works like a charm but what if someone adds a large JSON file as a monitoring URL?

**Is there a way to receive only headers?**

**Real example:**
Monitoring URL: https://raw.githubusercontent.com/json-iterator/test-data/master/large-file.json
Response Time (on my server): ~ 2.589 ms
Response Time (other similar Services): ~ 460 ms

So my guess is, that other services only request for headers? 🤔

**Comment by tsibahatau** [comment]
Why don't just use HEAD method?

**Comment by JCMais** [comment]
You want to use the `NOBODY` option: https://curl.se/libcurl/c/CURLOPT_NOBODY.html

**Comment by creazy231** [comment]
@JCMais `NOBODY` is what I was looking for and it helped a lot.
My scripts currently run via google cloud functions to cover different regions. Unfortunately the performance of node-libcurl is not so good there, so I switched to node-fetch. Anyway thanks for the help, maybe it can help someone else in the future :)

**Comment by JCMais** [comment]
@creazy231 did you notice performance issues in any specific part of the library in particular?

**Comment by creazy231** [comment]
No, not really. I think it's just how node-libcurl and node-fetch handles requests. I didn't took a look deeper into it. Maybe it's just a bad user "problem" I got with this lib because I don't know much about cURL itself 😅

**Comment by JCMais** [comment]
One of the main benefits of libcurl is the connection cache, for ephemeral environments, this may not bring that big of a performance benefit.

The performance for single requests should still be at least similar to JavaScript libraries like node-fetch tho, so in case you get back to test this and find anything unusual about the performance of this library, please let me know. 😄
