### ISSUE TITLE
How to use node-libcurl with NextJS using native-ext-loader?

### ISSUE THREAD

**Issue by 9ntonio** [JCMais/node-libcurl#277]
### I need Help please! 

I am getting the following error when running my code on the browser:

<img width="644" alt="Screen Shot 2021-02-20 at 9 20 19 AM" src="https://user-images.githubusercontent.com/2566895/108603572-968e6800-735d-11eb-81fd-ab592ae97dfe.png">

I am using NextJS on a [Netlify build image that uses Ubuntu version 16.04 (aka Xenial) ](https://github.com/netlify/build-image/blob/xenial/included_software.md)as the base. 

my `next.config.js` is set as follows:

<img width="664" alt="Screen Shot 2021-02-20 at 9 28 38 AM" src="https://user-images.githubusercontent.com/2566895/108603657-1288b000-735e-11eb-9da7-e6bca2c1d3b4.png">

As you can see I'm using [native-ext-loader](https://github.com/smt116/node-native-ext-loader#readme) as a way to load your npm package into my build. 

I'm assuming the error is basically saying it can not find the binary files that I am trying to include in the config above. 

Please let me know if you need anything else in helping resolve this issue. 

Thanks in advance, Antonio.

**Comment by JCMais** [comment]
Hi, you probably have to use [`rewritePath`](https://github.com/smt116/node-native-ext-loader#rewritepath-default-undefined).

Other than that without a reproducible code snippet, I cannot offer much help.

**Comment by 9ntonio** [comment]
Thanks for the reply. 

Here is the code snippet you requested. I hope this helps. 

```
import { NextPage } from 'next';
import querystring from 'querystring';

import { Curl } from 'node-libcurl';
const curl = new Curl();
const url = 'https://www.slack.com';

interface Props {
  hostData?: string;
  slackCode?: any;
}

const Page: NextPage<Props> = ({ hostData, slackCode }) => (
  <main>

    <h1>Your data:&nbsp; 
      <u>{hostData}</u>
    </h1>

    <h1>Slack Data:<br /> 
      <u>{slackCode}</u>
    </h1>

  </main>
)

Page.getInitialProps = async ({ req, query }) => {
  const hostData = req ? req.headers.host : 'NO HOST DATA';
  const slackCode = query.code;
  const data = {
    'code': slackCode,
    'client_id': process.env.CLIENT_ID,
    'client_secret': process.env.CLIENT_SECRET,
  }

  curl.setOpt(Curl.option.URL, url);
  // !! You need to build the query string,
  // !! node has this helper function for that:
  curl.setOpt(Curl.option.POSTFIELDS, querystring.stringify(data));
  curl.setOpt(Curl.option.VERBOSE, true);

  curl.on('end', (statusCode, body) => {
    console.log("\x1b[31m",`\n Body: \n${body}`);
    curl.close();
  })

  curl.on('error', curl.close.bind(curl));
  curl.perform();
  return { hostData, slackCode };
}
```

I am basically waiting to receive a json response. I am getting the response, but soon after I am getting the error noted in my first post. 

I hope this helps clarify the issues I'm having.

**Comment by 9ntonio** [comment]
@JCMais did my added code help clarify your concern?

**Comment by JCMais** [comment]
I have not tested it yet, I should be able to do it this weekend.

**Comment by JCMais** [comment]
@9ntonio this happens because the import to `node-libcurl` is in the root of the file, so it's running in both browser and server environments. Native Node.js addons cannot be loaded in a browser.

In your case, you have a few options, if you are using Next.js 9.3 or newer, you can use [`getServerSideProps`](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) and add the require to `node-libcurl` in there, this way all code that uses `node-libcurl` is only running in the server:


```tsx
import { NextPage } from 'next';
import querystring from 'querystring';

const url = 'https://www.slack.com';

interface Props {
  hostData?: string;
  slackCode?: any;
}

const Page: NextPage<Props> = ({ hostData, slackCode }) => (
  <main>

    <h1>Your data:&nbsp; 
      <u>{hostData}</u>
    </h1>

    <h1>Slack Data:<br /> 
      <u>{slackCode}</u>
    </h1>

  </main>
)

Page.getServerSideProps = async ({ req, query }) => {
  const{ Curl } = require('node-libcurl');
  const curl = new Curl();

  const hostData = req ? req.headers.host : 'NO HOST DATA';
  const slackCode = query.code;
  const data = {
    'code': slackCode,
    'client_id': process.env.CLIENT_ID,
    'client_secret': process.env.CLIENT_SECRET,
  }

  curl.setOpt(Curl.option.URL, url);
  // !! You need to build the query string,
  // !! node has this helper function for that:
  curl.setOpt(Curl.option.POSTFIELDS, querystring.stringify(data));
  curl.setOpt(Curl.option.VERBOSE, true);

  curl.on('end', (statusCode, body) => {
    console.log("\x1b[31m",`\n Body: \n${body}`);
    curl.close();
  })

  curl.on('error', curl.close.bind(curl));
  curl.perform();
  return { hostData, slackCode };
}
```

Otherwise, if you are using a older Next.js version, you should:
- move the require of `node-libcurl` to be inside `getInitialProps`
- make you are only running the code with the require and `node-libcurl` usage if `req` is defined (which means this is being called in the server):


```tsx
import { NextPage } from 'next';
import querystring from 'querystring';

const url = 'https://www.slack.com';

interface Props {
  hostData?: string;
  slackCode?: any;
}

const Page: NextPage<Props> = ({ hostData, slackCode }) => (
  <main>

    <h1>Your data:&nbsp; 
      <u>{hostData}</u>
    </h1>

    <h1>Slack Data:<br /> 
      <u>{slackCode}</u>
    </h1>

  </main>
)

Page.getInitialProps = async ({ req, query }) => {
  if (!req) {
    // return initial props in the frontend - you should not use or require native addons here
    return {};
  }
  
  // running in the server, you are free to use native addons or Node.js modules.
  
  const{ Curl } = require('node-libcurl');
  const curl = new Curl();

  const hostData = req ? req.headers.host : 'NO HOST DATA';
  const slackCode = query.code;
  const data = {
    'code': slackCode,
    'client_id': process.env.CLIENT_ID,
    'client_secret': process.env.CLIENT_SECRET,
  }

  curl.setOpt(Curl.option.URL, url);
  // !! You need to build the query string,
  // !! node has this helper function for that:
  curl.setOpt(Curl.option.POSTFIELDS, querystring.stringify(data));
  curl.setOpt(Curl.option.VERBOSE, true);

  curl.on('end', (statusCode, body) => {
    console.log("\x1b[31m",`\n Body: \n${body}`);
    curl.close();
  })

  curl.on('error', curl.close.bind(curl));
  curl.perform();
  return { hostData, slackCode };
}
```

**Comment by 9ntonio** [comment]
@JCMais thank you for your help and detailed instructions. I will post back here once I confirm that your notes resolve my issue. 

Thank you again for your help.

**Comment by 9ntonio** [comment]
@JCMais I can confirm that your suggestion to use `getServerSideProps` addressed my issue. I had to use it as an async  function per the following code.  Please note I am using `NextJS v10.0.6`.

```
import { NextPage } from 'next';
import querystring from 'querystring';
const url = 'https://slack.com/';

interface Props {
  hostData?: string;
  slackCode?: any;
}

const Page: NextPage<Props> = ({ hostData, slackCode }) => (
  <main>

    <h1>Your data:&nbsp; 
      <u>{hostData}</u>
    </h1>

    <h1>Slack Data:<br /> 
      <u>{slackCode}</u>
    </h1>

  </main>
)

export async function getServerSideProps({ req, query }) {
  const{ Curl } = require('node-libcurl');
  const curl = new Curl();

  const hostData = req ? req.headers.host : 'NO HOST DATA';
  const slackCode = query.code;
  const data = {
    'code': slackCode,
    'client_id': process.env.CLIENT_ID,
    'client_secret': process.env.CLIENT_SECRET,
  }

  curl.setOpt(Curl.option.URL, url);
  // !! You need to build the query string,
  // !! node has this helper function for that:
  curl.setOpt(Curl.option.POSTFIELDS, querystring.stringify(data));
  curl.setOpt(Curl.option.VERBOSE, true);

  curl.on('end', (statusCode: any, body: any) => {
    console.log("\x1b[31m",`\n Body: \n${body}`);
    curl.close();
  })

  curl.on('error', curl.close.bind(curl));
  curl.perform();
  return { props: { hostData, slackCode } };
}

export default Page
```

For anyone trying this as a fix, please note to use the following structure of your returned data:

`return { props: {data} }`

If you do not use this structure you will get an error. 

Thank you for your help, and I hope this helps anyone who has the same issue I did.

**Comment by JCMais** [comment]
Glad you got it working @9ntonio, and thanks for posting the full solution.
