### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by krivtsov** [JCMais/node-libcurl#279]
Hi! After updating the version to 2.3.1 build error, broken link 
https://github.com/JCMais/node-libcurl/releases/download/v2.3.1/node_libcurl-v2.3.1-node-v64-linux-x64-glibc.tar.gz

```bash
> node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.3.1/node_libcurl-v2.3.1-node-v64-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.3.1 and node@10.19.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
Traceback (most recent call last):
```

**Comment by JCMais** [comment]
I have added back the prebuilt binaries to Node.js v10, I know this is something that is not always easy to do, but I would recommend upgrading to Node.js v12, as Node.js v10 is nearing its end of life.
