### ISSUE TITLE
Curl with proxy + user, pass not working

### ISSUE THREAD

**Issue by DuySexy** [JCMais/node-libcurl#284]
Hi.
I use node-libcurl with proxy http://qFW4xX:revFEU@45.32.117.124:57101 but not working

Error: [Error: Failure when receiving data from the peer] { errorCode: 56 }

`curl.setOpt('PROXY', 'http://qFW4xX:revFEU@45.32.117.124:57101');`

if i use only proxy without user,pass, it working . example: `curl.setOpt('PROXY', '123.45.67.89');`

-- also i use alternate syntax:
```
curl.setOpt('PROXY', '45.32.117.124:57101')
curl.setOpt('PROXYUSERPWD', 'qFW4xX:revFEU');
```
still not working.

however, issue not belong to proxy, because i use http://qFW4xX:revFEU@45.32.117.124:57101 with PHP curl that working perfectly (same server) 

`curl_setopt($ch, CURLOPT_PROXY, 'http://qFW4xX:revFEU@45.32.117.124:57101');`

bot php and nodejs run same server. stop iptables, open all ports, not install any firewall.

sr my english is not good. please help me. thank!

**Comment by DuySexy** [comment]
http proxy info:
v6 address: 2001:19f0:4401:233:3ccd:c105:de78:c65a
ip: 45.32.117.124
port 57101
user:pass qFW4xX:revFEU
country: singapore

**Comment by DuySexy** [comment]
@JCMais help me

**Comment by DuySexy** [comment]
please help me

**Comment by JCMais** [comment]
can you share the full PHP code and Node.js? Or at least all the options you are setting.

**Comment by DuySexy** [comment]
thank for reply!

this issue from destination site (xxx.com), I try curl other url (google.com) then it works fine.

also i want know any reason from destination site cause error?

**Comment by JCMais** [comment]
This may happen if the destination server is blocking the connection in some way, or does not support the given HTTP method.
