### ISSUE TITLE
Source code omitted for this binary file

### ISSUE THREAD

**Issue by c4kaci** [JCMais/node-libcurl#286]
Hi,

I'm beginner in the Node world. 

I installed libcurl with "**npm i node-libcurl --save**" .  It's OK. 

I wrote to my C4.js 
**const { curly } = require('node-libcurl');**

When I want to build my project  I get this error:
***********************************************************************************
 ERROR  Failed to compile with 1 error                                                                                                                                                         7:53:59 PM
 error  in ./node_modules/node-libcurl/lib/binding/node_libcurl.node

Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/node-libcurl/dist/Multi.js 5:17-60
 @ ./node_modules/node-libcurl/dist/index.js
 @ ./src/c4/C4.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.22:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
***********************************************************************************

Thx:
kaci

**Comment by JCMais** [comment]
This is a backend-only library, it cannot be used in the frontend.
