### ISSUE TITLE
node-libcurl can't bypass Cloudflare while curl can

### ISSUE THREAD

**Issue by vladgovor77771** [JCMais/node-libcurl#292]
I'm trying to fetch site which is protected by Cloudflare.

This works as expected.
```bash
curl --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" --compressed --header "Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3" --header "Connection: close" --header "Te: trailers" --header "Upgrade-Insecure-Requests: 1" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" https://all-access.wax.io/
```

When I'm trying to do the same through ```node-libcurl```, Cloudflare 1020 error code returns (status code 403).

```js
const { curly } = require("node-libcurl");

const main = async () => {
  const res = await curly.get("https://all-access.wax.io/", {
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    httpHeader: [
      "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3",
      "Upgrade-Insecure-Requests: 1",
      "Te: trailers",
      "Connection: close",
    ],
    // acceptEncoding: "gzip, deflate", // doesn't matter
    sslVerifyPeer: false, // if true also doesn't work
  });

  console.log(res.data); // error code: 1020
}

main();
```

Where is a problem?

**Comment by vladgovor77771** [comment]
Here is comparison of node-libcurl, axios, node-fetch and curl executable: https://gist.github.com/vladgovor77771/3f0283b9c0b3720ce4d9a6cab2354205 
![image](https://user-images.githubusercontent.com/39651842/120899646-772ff800-c639-11eb-938a-60c635560d9c.png)

node-libcurl, axios, node-fetch don't work. But curl exec works (Burp also passes). Is it related to Node.js http/socket impl?

**Comment by JCMais** [comment]
Are you sure `curl` works as expected?

Trying curl directly here returns the `Access Blocked` page from Cloudflare.

**Comment by vladgovor77771** [comment]
@JCMais 
Try this:
```
docker run -ti ubuntu:20.04 /bin/bash
apt-get update && apt-get install curl=7.68.0-1ubuntu2.5 -y
curl --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" --compressed --header "Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3" --header "Connection: close" --header "Te: trailers" --header "Upgrade-Insecure-Requests: 1" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" https://all-access.wax.io/
```

**Comment by vladgovor77771** [comment]
@JCMais, any thoughts about? I trying to research, what types of http clients can bypass cf. ```httpie``` for linux also works.

**Comment by JCMais** [comment]
Not sure I can help you here.

Tried running the same docker command you commented above and it does work. however, node-libcurl itself is not doing anything special on the requests, the only thing we do is set the user agent to a default one, but you can overwrite that by passing the `USERAGENT` option, so I'm not sure how Cloudflare is blocking the request when using it.
