### ISSUE TITLE
Curly not following redirects

### ISSUE THREAD

**Issue by SaulMoonves** [JCMais/node-libcurl#297]
Curly doesn't seem to be following redirects. I get back the statusCode of 301 and the data is a string or buffer. I checked the location header and it's present but obviously not followed since the function returned. I believed it would follow redirects because of looking at other issues in the past.

Is this a bug, or how do I coerce curly to follow redirects automatically? And, if possible, restrict it from following infinite redirects?

**Comment by JCMais** [comment]
Hi @SaulMoonves, you have to use the `followLocation` option. You can use most libcurl options, `FOLLOWLOCATION` is one of them: https://curl.se/libcurl/c/CURLOPT_FOLLOWLOCATION.html

You can also use `MAXREDIRS` to limit the number of redirects: https://curl.se/libcurl/c/CURLOPT_MAXREDIRS.html

I hope this helps!

**Comment by SaulMoonves** [comment]
@JCMais Thank you. I didn't see an example of how to set options on Curly, so I did the due diligence and checked the source code and I have my answer. For the benefit of others, querying a crappy broken website (something I have to do often):

```
const curlOpts = {
  FOLLOWLOCATION: true,
  MAXREDIRS: 5,
  SSL_VERIFYPEER: false,
  SSL_VERIFYHOST: false
}

const response = await curly.get('https://brokenssl.example.com/', curlOpts);
```

**Comment by JCMais** [comment]
glad you got it figured out :)

The API documentation is available here (but it has the same information than you have in the fn itself as it is generated from the TypeScript types): https://node-libcurl-docs.netlify.app/interfaces/_lib_curly_.curlyfunction.html
