### ISSUE TITLE
gen:constants fails due to curl.haxx.se -> curl.se redirect

### ISSUE THREAD

**Issue by johnwchadwick** [JCMais/node-libcurl#298]
The `build-constants.js` script tries to pull from https://curl.haxx.se/libcurl/c/curl_easy_setopt.html, but the page has moved to https://curl.se/libcurl/c/curl_easy_setopt.html. The redirect is not followed and it tries to parse a 302 response, which fails.

Node.JS v14.17.2
NPM 6.14.13
Debian 10.10
`develop` / 0423c74

**Comment by JCMais** [comment]
@johnwchadwick Thanks for the issue and the PR (!), really appreciate it!

**Comment by johnwchadwick** [comment]
No problem, thank you for the prompt response!
