### ISSUE TITLE
Request through proxy on https secured website

### ISSUE THREAD

**Issue by nytr0gen** [JCMais/node-libcurl#30]
Hello,
Making a request to a https website (i tried https://www.google.com, https://yahoo.com) doesn't work while i'm using a http proxy (i tried some from the hidemyass list). The proxy works using curl (curl --proxy $PROXY https://google.com). Also I can use node-libcurl with a proxy on a http website. Also a socks5 proxy works on a https website. I just can't get a http proxy to work.

Let me know if I wasn't clear enough. I'm pretty bad at explaining bugs.

**Comment by JCMais** [comment]
Hi.

Can you post a code sample of what you are trying to accomplish?

**Comment by nytr0gen** [comment]
i've took the proxies from http://proxylist.hidemyass.com/
```
'use strict';
var Curl = require('node-libcurl').Curl;

var opts = {
    headers: {
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Encoding': 'gzip, deflate',
        'Accept-Language': 'en-US,en;q=0.8',
        'Connection': 'keep-alive',
        'User-Agent': 'Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36'
    }
};
// this works
// opts.url = 'https://www.yahoo.com';
// opts.proxy = 'socks5h://46.4.88.203:9050';

// this doesn't work. i get a timeout. on this proxy or any other http proxy
opts.url = 'https://www.yahoo.com';
opts.proxy = '220.255.3.170:80';

// this works
// opts.url = 'http://www.yahoo.com';
// opts.proxy = '220.255.3.170:80';

var curl = new Curl();
var curlOpts = {};
curlOpts['CUSTOMREQUEST'] = 'GET';
curlOpts['URL'] = opts.url;
curlOpts['CONNECTTIMEOUT_MS'] = 30000;
curlOpts['FOLLOWLOCATION'] = false;
curlOpts['ACCEPT_ENCODING'] = 'gzip';
curlOpts['PROXY'] = opts.proxy;
curlOpts['HTTPHEADER'] = [];
for (let key in opts.headers) {
    curlOpts['HTTPHEADER'].push(key + ': ' + opts.headers[key]);
}

for (let key in curlOpts) {
    curl.setOpt(Curl.option[key], curlOpts[key]);
}

curl.on('end', function (statusCode, body, headers) {
    console.log(statusCode, headers);
    curl.close();
});

curl.on('error', function(err, errCode) {
    console.error(err);
    curl.close();
});

curl.perform();
```

**Comment by JCMais** [comment]
Still investigating this, but already exhausted the time I had this week, gonna debug more next week.

From what I can see the socket is closed before the connection is made. Still trying to understand what is going on.

**Comment by JCMais** [comment]
Ok, looks like the issue was with libcurl itself, it was probably because of this bug http://sourceforge.net/p/curl/bugs/1492/, fixed here https://github.com/bagder/curl/commit/852d35b6ea.

If you are wondering why it doesn't happens when using the curl tool, it's probably because the tool itself doesn't uses the multi interface, while this binding does.

Try using a version of libcurl > 7.42

**Comment by nytr0gen** [comment]
thank you :)

**Comment by hashtafak** [comment]
I just comment to explain the code using port 80 proxy mean http proxy, not https proxy (port 443)
So the proxy server will not accept https method. Am i right?
