### ISSUE TITLE
Put file upload support

### ISSUE THREAD

**Issue by Jakobud** [JCMais/node-libcurl#31]
I'm trying to figure out a list of all the options available. In your examples for uploading a file, you use `curl.option.HTTPPOST`. `HTTPPOST` is not a listed valid curl option in any documentation that I can see. I see `POST` but not `HTTPPOST`. So anyways, according to your doc's, the `curl.option` is an Object with all the valid options in it. So in an attempt to learn more, I did this:

```
var Curl = require('node-libcurl').Curl;
var curl = new Curl();
console.log(curl.option);
```

I get `undefined`. Am I missing something here? How do I see the list of all available options? I need to upload a file using http PUT, but I have no idea what option name to use for this in your library...

**Comment by JCMais** [comment]
[CURLOPT_HTTPPOST](http://curl.haxx.se/libcurl/c/CURLOPT_HTTPPOST.html).
[All curl options](http://curl.haxx.se/libcurl/c/easy_setopt_options.html)

Some options are not implemented, like socket callbacks.

And your code is incorrect. Correct:

    var Curl = require('node-libcurl').Curl;
    console.log( Curl.option );

**Comment by Jakobud** [comment]
Okay thanks! That is making more sense now. Do you know how to use the `UPLOAD` option? I'm trying to do something like this:

```
curl.setOpt('URL', url);
curl.setOpt('UPLOAD', true);
curl.setOpt('READDATA', fh);
curl.setOpt('INFILESIZE', fileSize);
```

But I get:

```
return this._curl.setOpt( optionIdOrName, optionValue );
                      ^
TypeError: Option value should be a string.
```

Specifically its referring to this line:

```
curl.setOpt('READDATA', fh);
```

I'm not sure why it's giving that error...

I'm following this type of example:

http://curl.haxx.se/libcurl/c/CURLOPT_UPLOAD.html

Any clues on this?

**Comment by Jakobud** [comment]
Trying to look a little deeper into this, documentation says that the `READDATA` option should be a file pointer, which is what I'm doing:

```
var fh = fs.openSync('myfile.txt');
```

but your library is saying it should be a string. Any thoughts on that? Am I misunderstanding?

http://curl.haxx.se/libcurl/c/CURLOPT_READDATA.html

**Comment by JCMais** [comment]
As this is a binding for libcurl, in javascript, it has some limitations. Not all options are going to have the same type requirement, and not all options are going to be available.

READDATA is one of those. READDATA needs a file pointer that can be read by the libcurl READFUNCTION, it's not possible to pass a javascript file descriptor because of that. And it's not possible to change the READFUNCTION from javascript, since it requires a c function callback.

I will take a look into that to see what I can do. But I'm problem going to find some problems, like this one https://github.com/nodejs/node-gyp/issues/416

**Comment by JCMais** [comment]
Ok, got it working without major issues, gonna test some more, and will push it to the dev branch this week.

**Comment by JCMais** [comment]
Done in v0.6.0.

Example:

```js
var Curl = require( '../lib/Curl' ),
    path = require( 'path' ),
    fs   = require( 'fs' ),
    crypto = require( 'crypto' );

var curl = new Curl(),
    url = 'httpbin.org/put',
    fileSize = 10 * 1024, //1KB
    fileName = path.resolve( __dirname, 'upload.test' ),
    fd = -1;

//write random bytes to a file, this will be our upload file.
fs.writeFileSync( fileName, crypto.randomBytes( fileSize ) );

console.log( 'File: ', fs.readFileSync( fileName, 'base64' ) );

fs.open( fileName, 'r+', function( err, fd ) {

    //enabling VERBOSE mode so we can get more details on what is going on.
    curl.setOpt( Curl.option.VERBOSE, 1 );
    //set UPLOAD to a truthy value to enable PUT upload.
    curl.setOpt( Curl.option.UPLOAD, 1 );
    //pass the file descriptor to the READDATA option
    // passing one invalid value here will cause an aborted by callback error.
    curl.setOpt( Curl.option.READDATA, fd );

    curl.setOpt( Curl.option.URL, url );

    curl.on( 'end', function( statusCode, body ) {

        console.log( body );

        //remember to always close the file descriptor!
        fs.closeSync( fd );

        fs.unlinkSync( fileName );

        //the same for the curl instance, always close it when you don't need it anymore.
        this.close();
    });

    curl.on( 'error', function( err ) {

        console.log( err );

        fs.closeSync( fd );
        fs.unlinkSync( fileName );
        this.close();
    });

    curl.perform();
});
```
