### ISSUE TITLE
Can't npm install on Mac osx yosemite

### ISSUE THREAD

**Issue by girmay** [JCMais/node-libcurl#32]
npm WARN package.json node-web-scrape@0.0.1 No repository field.
npm WARN package.json node-web-scrape@0.0.1 No license field.
npm WARN engine node-libcurl@0.5.1: wanted: {"node":">= 0.10.0 && <= 0.12","iojs":">= 1.0.0"} (current: {"node":"4.1.0","npm":"2.14.3"})
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
\
> node-libcurl@0.5.1 install /Applications/xxx/node_modules/node-libcurl
> node tools/retrieve-win-deps && node tools/generate-stubs && pangyp rebuild

gyp: /Users/xxx/.node-gyp/4.1.0/common.gypi not found (cwd: /Applications/MAMP/htdocs/mvc/node_modules/node-libcurl) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/MAMP/htdocs/mvc/node_modules/node-libcurl/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/Applications/MAMP/htdocs/mvc/node_modules/node-libcurl/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /Applications/MAMP/htdocs/mvc/node_modules/node-libcurl
gyp ERR! node -v v4.1.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-libcurl"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.5.1 install: `node tools/retrieve-win-deps && node tools/generate-stubs && pangyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libcurl@0.5.1 install script 'node tools/retrieve-win-deps && node tools/generate-stubs && pangyp rebuild'.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && pangyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/mvc/npm-debug.log

**Comment by JCMais** [comment]
Node v4 is currently not supported, Will fix that this weekend.

**Comment by JCMais** [comment]
Supported in v0.6.0.
