### ISSUE TITLE
Getting error in rebuilding with node v0.12.7

### ISSUE THREAD

**Issue by mozammilwy** [JCMais/node-libcurl#33]
Hi,
I am getting error on rebuilding with node v0.12.7 and npm v2.11.3. The logs are as -

npm install node-libcurl
npm WARN engine node-libcurl@0.5.1: wanted: {"node":">= 0.10.0 && <= 0.12","iojs":">= 1.0.0"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
-
> node-libcurl@0.5.1 install /home/mz/temp_moz/node_modules/node-libcurl
> node tools/retrieve-win-deps && node tools/generate-stubs && pangyp rebuild

Cannot find curl's header file.
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "node-libcurl"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.5.1 install: `node tools/retrieve-win-deps && node tools/generate-stubs && pangyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libcurl@0.5.1 install script 'node tools/retrieve-win-deps && node tools/generate-stubs && pangyp rebuild'.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && pangyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mz/temp_moz/node_modules/npm-debug.log

**Comment by JCMais** [comment]
You need to install the libcurl header files. If you are using ubuntu/debian, the package name is libcurl4-openssl-dev.

**Comment by mozammilwy** [comment]
I am migrating from node-curl to node-libcurl. Is there any migration plan/doc or any breaking changes that i should keep in my mind. 
The reason for this migrating is node-upgrade from node v0.10.32 to v0.12.7.
Thanks for your help.

**Comment by JCMais** [comment]
This is a whole new project, there is probably only a small fraction of the original code, and as so, the API is different too. I didn't created any migration guide, but you can get an idea of how stuff are done now reading some of the examples: https://github.com/JCMais/node-libcurl/tree/master/examples

Also, I've just pushed a new version (v0.6.0) which adds support for creating Easy, Multi and Share handles, just like libcurl itself, take a look on the new generated api docs here: https://github.com/JCMais/node-libcurl/blob/master/api.md

Closing as looks like the original issue is resolved, if you have more questions, ask away.
