### ISSUE TITLE
missing files for building from source when installed from npm

### ISSUE THREAD

**Issue by kapouer** [JCMais/node-libcurl#330]
Hi,

some of us have a build-friendly environment, so that packages with bindings.gyp can be built from source, instead of pulling binaries.
However node-libcurl seems to be missing some files (build/scripts/*, for a start).

**Comment by JCMais** [comment]
can you post the full error?

I am able to build it from the source just fine on Windows and Ubuntu.

**Comment by kapouer** [comment]
My mistake, i used node-gyp... it works all right with `node-pre-gyp` in the npm-installed node_modules/node-libcurl.
I wasn't sure if it worked with `npm install node-libcurl --build-from-source` but it seems it works too.
