### ISSUE TITLE
curly stream and writeFunction

### ISSUE THREAD

**Issue by kapouer** [JCMais/node-libcurl#331]
Hi, i am trying to stream response and abort curl in some cases:

```
async function cfetch(url) {
	let stop = false;
	const { headers, data, statusCode } = await curly.get(url, {
		curlyStreamResponse: true,
		curlyResponseBodyParsers: false,
		writeFunction(chunk, size, nmemb) {
			if (stop) {
				return -1;
			} else {
				return size * nmemb;
			}
		}
	});
	
	const req = {
		abort() {
			stop = true;
		}
	};
	const res = new PassThrough();
	res.headers = headers.pop();
	res.statusCode = statusCode;
	data.pipe(res);
	return { req, res };
}
const { req, res } = await cfetch("https://longhtmldocument.com");
const parser = res.pipe(someSaxParser);
parser.on('enough', () => req.abort());
```
this example works great for the streaming response part if i remove the `writeFunction` option.
However i need to be able to abort the request, and it doesn't work as expected: "data" stream receives no data.
If i try to write the chunks directly to "res" stream, it also fails somehow.

is there some hope to get this working ?

**Comment by kapouer** [comment]
I got it working using

```
async function cfetch(url) {
	let stop = false;
	const { headers, data, statusCode } = await curly.get(url, {
		curlyStreamResponse: true,
		curlyResponseBodyParsers: false,
		writeFunction(chunk, size, nmemb) {
			if (stop) {
				return -1;
			} else {
				return size * nmemb;
			}
		}
	});
	
	const req = {
		abort() {
			data.destroy();
		}
	};
	const res = new PassThrough();
	res.headers = headers.pop();
	res.statusCode = statusCode;
	data.on('error', () => {
		res.end();
	});
	data.pipe(res);
	return { req, res };
}
```

**Comment by JCMais** [comment]
Currently, you cannot provide `writeFunction` when using the stream options, as internally the streaming is done by using a custom writeFunction: https://github.com/JCMais/node-libcurl/blob/fb5ae130ccaa9d4f01a90e1bc645ed5b4a304845/lib/Curl.ts#L983-L1086

Using destroy as you did is the correct way to do it.

**Comment by kapouer** [comment]
Maybe it would help future users to add the example above to the provided examples ?

**Comment by JCMais** [comment]
Yep, that would be great! I should have some time to do it later next week, in the meantime feel free to open a PR :)
