### ISSUE TITLE
curly: error setting certificate file: /etc/ssl/certs/ca-certificates.crt on Fedora 35

### ISSUE THREAD

**Issue by jhoogstraat** [JCMais/node-libcurl#334]
This node script produces curl error 77: `const response = await curly.get(url)`.
`curl $URL` does work however.

The file `ca-certificates.crt` does not exist on my machine, instead `ls /etc/ssl/certs/` prints
```
Permissions Size User Date Modified Name
lrwxrwxrwx@   49 root 13 Dez  2021  ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
lrwxrwxrwx@   55 root 13 Dez  2021  ca-bundle.trust.crt -> /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
```

**Comment by JCMais** [comment]
To keep the maintainability of this project, I am closing old tickets. If the issue continues with the latest version of node-libcurl, please feel free to create a new ticket.
