### ISSUE TITLE
How convert to libcurl?

### ISSUE THREAD

**Issue by bismoney** [JCMais/node-libcurl#342]
```
$counter = "";            // Укажите номер счетчика
$token = "";              // Укажите OAuth-токен
$client_id_type = "";     // Укажите тип идентификаторов посетителей – CLIENT_ID, USER_ID или YCLID

$curl = curl_init("https://api-metrika.yandex.ru/management/v1/counter/$counter/offline_conversions/upload?client_id_type=$client_id_type");

curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, array('file' => new CurlFile(realpath('file.csv'))));
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_HTTPHEADER, array("Content-Type: multipart/form-data", "Authorization: OAuth $token"));

$result = curl_exec($curl);

echo $result;

curl_close($curl);
```

Need curlFile format
curl_setopt($curl, CURLOPT_POSTFIELDS, array('file' => new CurlFile(realpath('file.csv'))));

    var Curl = require( 'node-libcurl' ).Curl;

    var curl = new Curl();

    curl.setOpt('URL', data.url);
    curl.setOpt('FOLLOWLOCATION', true);
    curl.setOpt('SSL_VERIFYPEER', false);

    curl.setOpt('HTTPHEADER', [
        'Authorization: OAuth AQAAAAAF0D1yAAfC3Q40j9_TvE4nhNZ4sv6CusA',
        'Content-Type: multipart/form-data;boundary=----WebKitFormBoundaryyrV7KO0BoCBuDbTL',
    ]);

    curl.on( 'end', function( statusCode, body, headers ) {
        console.info(statusCode);
        console.info( '---' );
        console.info(body);
        this.close();
    });

    curl.on( 'error', function( err, curlErrorCode ) {

        console.error( err.message );
        console.error( '---' );
        console.error( curlErrorCode );

        this.close();

    });

    curl.perform();

Help pls ;(

**Comment by JCMais** [comment]
Please check the examples folder, almost all common use-cases are in there. For file upload, it looks like this: https://github.com/JCMais/node-libcurl/blob/1563bb7699eb9b22989058a0d018c59a460aaf37/examples/08-file-upload-post.js
