### ISSUE TITLE
calling close in on 'data' is throwing error

### ISSUE THREAD

**Issue by mozammilwy** [JCMais/node-libcurl#35]
Hi,

1. Have you implemented NTLM authentication for exchange in this project?
2. When i am trying to use setOpt as below i am getting error. However it's mentioned here -    http://curl.haxx.se/libcurl/c/curl_easy_setopt.html 

       curl.setOpt('IPRESOLVE',  1); 
       curl.setOpt('ACCEPT_ENCODING',  1);
       curl.setOpt('SSLVERSION',  1);

**Comment by JCMais** [comment]
> 1. Have you implemented NTLM authentication for exchange in this project?

I didn't not tested NTLM auth, it *should* work the way it's. Remember that you need a libcurl that was built with OpenSSL or GnuTLS for it to work.

> When i am trying to use setOpt as below i am getting error. However it's mentioned here - http://curl.haxx.se/libcurl/c/curl_easy_setopt.html 

You need to be more clear on what error it's throwing, but from the code that you posted:

> curl.setOpt('ACCEPT_ENCODING', 1);

``ACCEPT_ENCONDING`` must be a string, you are passing a number.

Also, your tittle mentions an error that is not on your description, did you fixed it?

**Comment by mozammilwy** [comment]
Hi

Thanks for your help. Actually i resolved the title error :). But whenever i am trying to use setOpt for the following examples-

curl.setOpt(Curl.option.SSLVERSION,  30);
curl.setOpt(Curl.option.IPRESOLVE,  1); // CURL_IPRESOLVE_V4

I am getting the follwing error-
"Error: Unknown option given. First argument must be the option internal id or the option name. You can use the Curl.option constants.
    at Error (native)
    at Curl.setOpt (/home/mz/mz-node-modules/node_modules_base/node_modules/node-libcurl/lib/Curl.js:529:23)"

Also when i am doing  curl.setOpt(Curl.option.ACCEPT_ENCODING,  'true'), it's working but
Is it actually setting the ACCEPT_ENCODING to true?

**Comment by JCMais** [comment]
> Error: Unknown option given. First argument must be the option internal id or the option name. You can use the Curl.option constants.

You are using ``SSLVERSION``, this option was not added yet, just published a new version to npm with it, try version ``0.6.2``.

Also, don't use numbers directly, since this is error prone. Use the constants:

``javascript
curl.setOpt(Curl.option.SSLVERSION, Curl.sslversion.SSLv3 );
curl.setOpt(Curl.option.IPRESOLVE, Curl.ipresolve.V4 );
``

> Also when i am doing curl.setOpt(Curl.option.ACCEPT_ENCODING, 'true'), it's working but
Is it actually setting the ACCEPT_ENCODING to true?

Yes, which is wrong. You must pass the encoding that you expect: [CURLOPT_ACCEPT_ENCONDING](http://curl.haxx.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html)

> Sets the contents of the Accept-Encoding: header sent in a HTTP request, and enables decoding of a response when a Content-Encoding: header is received. Three encodings are supported: identity, which does nothing, deflate which requests the server to compress its response using the zlib algorithm, and gzip which requests the gzip algorithm.

> If a zero-length string is set like "", then an Accept-Encoding: header containing all built-in supported encodings is sent.

> You can also opt to just include the Accept-Encoding: header in your request with CURLOPT_HTTPHEADER but then there will be no automatic decompressing when receiving data.

> This is a request, not an order; the server may or may not do it. This option must be set (to any non-NULL value) or else any unsolicited encoding done by the server is ignored. See the special file lib/README.encoding for further details.

**Comment by mozammilwy** [comment]
Hi,

Thanks again for your help. I checked console.log(Curl.option) and found that there is no Curl.option.IPRESOLVE flag. However it's mentioned here http://curl.haxx.se/libcurl/c/CURLOPT_IPRESOLVE.html . I also checked console.log(Curl.ipresolve) and it shown me all the three possible values. I think it might be a possible bug. Not sure but 'IPRESOLVE' might be missing from Curl.cc

Currently i am getting error on
curl.setOpt(Curl.option.IPRESOLVE,  Curl.ipresolve.V4);
and the error is "/home/mz/mz-node-modules/node_modules_base/node_modules/node-libcurl/lib/Curl.js:847
 or the option name. You can use the Curl.option constants.' : Easy.strError( 
                                                                    ^
Error: Unknown option given. First argument must be the option internal id or the option name. You can use the Curl.option constants.
    at Error (native)
    at Curl.setOpt (/home/mz/mz-node-modules/node_modules_base/node_modules/node-libcurl/lib/Curl.js:847:190)
    at Object.<anonymous> (/home/mz/mz/programs/dragon/repo/releases/20151001074739/src/test/imap_smtp_connect_check/node-libcurl-test-2.js:23:6)"

**Comment by JCMais** [comment]
Sorry, forgot again to add this one. It should work now! :sweat_smile: 

Try ``v0.6.3``

**Comment by mozammilwy** [comment]
Thanks a lot for your help. Now everything is working fine my side. One last thing. For one exchange account i set 'HTTPAUTH' as NTLM (8) and it failed then i tried with BASIC(1) and it worked. I was using 9 for NTLM or BASIC authentication in node-curl. Can i use it for node-libcurl also?

**Comment by JCMais** [comment]
In reality those values are [bitmasks](https://en.wikipedia.org/wiki/Mask_%28computing%29), if you want to try more than one auth method, you should OR them together, like this:

``curl.setOpt( 'HTTPAUTH', Curl.auth.BASIC | Curl.auth.NTLM );``

Note the ``|`` (bitwise OR) operator.

Closing this as it's resolved, feel free to ask any questions if you have.
