### ISSUE TITLE
single connection

### ISSUE THREAD

**Issue by insidexoff** [JCMais/node-libcurl#351]
How to use single connection in this library. so you have to wait for the previous http connection request to finish before executing the new connection.

I put node-libcurl in loop however this node-libcurl does concurrent http connection requests. i want a single connection how to do it.

**Comment by insidexoff** [comment]
I used this curl option to solve this problem. This doesn't seem like a good solution

 ```
NOPROGRESS: 1,
DNS_CACHE_TIMEOUT: 120,
MAXREDIRS: 20,
NOSIGNAL: 1,

FOLLOWLOCATION: true,
HTTPHEADER: datarow.headers,
SSL_VERIFYPEER: false,
SSL_VERIFYHOST: false,
CUSTOMREQUEST: datarow.method,
VERBOSE: true,
```

**Comment by JCMais** [comment]
@insidexoff mind sharing some code of what you want to accomplish?
