### ISSUE TITLE
Error using CURLOPT_PRIVATE

### ISSUE THREAD

**Issue by KokeroO** [JCMais/node-libcurl#357]
I have the following error when using `CURLOPT_PRIVATE ` with Easy:

`Error: Unsupported option, probably because it's too complex to implement using javascript or unecessary when using javascript (like the _DATA options).`

**Comment by JCMais** [comment]
In the C libcurl API, the `CURLOPT_PRIVATE` is used to store some data related to a specific easy handle. With Node.js this is not needed, as you can easily do that directly by adding a field to the instance or having a separate data structure to hold the data, such as a `WeakMap` where the key is the class instance.


The Easy class has a field `private` with a type set to `any` to help with this, as you can then assign any value to it. But my recommendation would be  to use a WeakMap or similar data structure
