### ISSUE TITLE
Strange behavior in Node debugger (REPL)

### ISSUE THREAD

**Issue by svlapin** [JCMais/node-libcurl#36]
Hello,

first of all, thanks for amazing module!
I pretty enjoy it and everything works awesome until I try to do some things in Node debugger.

Consider the following trivial snippet (`test.js`):
```js
var Curl = require('node-libcurl').Curl;

var curl = new Curl();

debugger;
```

Run it in debugger mode:
```sh
$ node debug test.js
```

And after pressing `c` to continue, get stopped at the breakpoint. Type `repl` + `Enter`, get into REPL console.
Type `curl` and hit `Enter`, and get the error:
```
node: ../node_modules/nan/nan_object_wrap.h:33: static T* Nan::ObjectWrap::Unwrap(v8::Local<v8::Object>) [with T = NodeLibcurl::Easy]: Assertion `object->InternalFieldCount() > 0' failed.
program terminated
```

I guess it happens because debugger tries to obtain some internal structure of the `Curl` instance.

Also, that does not reproduce if I start in REPL from the very beginning:
```sh
$ node
```
```js
> new (require('node-libcurl').Curl)()
Curl {
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _handle: Easy { onData: [Function: bound ], onHeader: [Function: bound ] },
  _id: 1,
  _chunks: [],
  _headerChunks: [],
  _chunksLength: 0,
  _headerChunksLength: 0,
  _isRunning: false,
  _features: 0,
  onData: null,
  onHeader: null }
```

Thanks.

**Comment by JCMais** [comment]
Hi, thanks for the report.

From what I can see, this is a bug with node itself, see this issue: https://github.com/nodejs/node-v0.x-archive/issues/9028

Closing this, since it's not something I can fix from here.
