### ISSUE TITLE
Add prebuilt binaries for nodejs 18 LTS

### ISSUE THREAD

**Issue by bchew** [JCMais/node-libcurl#366]
nodejs 18 has just been moved to active LTS and we have just realised there were no prebuilt binaries after upgrading as per snippet below:

```
npm ERR! node-pre-gyp info using node@18.12.0 | linux | x64
npm ERR! node-pre-gyp info check checked for "/home/node/e2e/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v2.3.4/node_libcurl-v2.3.4-node-v108-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v2.3.4/node_libcurl-v2.3.4-node-v108-linux-x64-glibc.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for node-libcurl@2.3.4 and node@18.12.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v2.3.4/node_libcurl-v2.3.4-node-v108-linux-x64-glibc.tar.gz 
```

Would it be possible to have prebuilt binaries for 18 as well? That would be appreciated, thanks.

I could create a PR if the changes for 18 are similar to https://github.com/JCMais/node-libcurl/commit/4844420ff81ce40d7f99726c9c614aab27d76eaf if you prefer

**Comment by JCMais** [comment]
@bchew I am working on this. I will increase the major version as it will require an upgrade of nan and node-gyp tho. This basically means requiring Python 3 and ubuntu >= 20.04 if you are using linux.

**Comment by bchew** [comment]
@JCMais have just tried with the `v3.0.0-0` pre-release version in a Node.js 18 with Ubuntu 22.04 container image and it has worked fine for us. Thanks!

**Comment by JCMais** [comment]
@bchew awesome, I will try to release it this weekend, but there will be no major changes between this pre-release version and v3, so feel free to keep using it until then.

**Comment by ddolcimascolo** [comment]
Hi @JCMais 

Any news on the support of Node 18? I can help if you need

Cheers,
David

**Comment by ddolcimascolo** [comment]
As a side note, we're using v3.0.0-0 with Node 18.12 and it works fine

**Comment by JCMais** [comment]
@ddolcimascolo @bchew v3.0.0 has been released, it may take a while until all prebuilt binaries are ready.

**Comment by ddolcimascolo** [comment]
Thx @JCMais one more time for your work in this library!
