### ISSUE TITLE
Can't build lib in Debian 9

### ISSUE THREAD

**Issue by obriankevin11** [JCMais/node-libcurl#376]
Hi,
I'm having troubles to use the lib in my node project on Debian 9 (which runs ok on windows).
I have the following error msg: Error: Cannot find module '../lib/binding/node_libcurl.node'

node: 16.13.1
npm: 8.1.2

So I'm trying to build it but can't figure things out. I have all the requirements:
gcc >= 4.8
libcurl dev files
python 2.7

I tried "npm install node-libcurl --build-from-source" but it just installs the prebuilt package.
Any idea (of what I'm doing wrong :))?
Thank you.

**Comment by JCMais** [comment]
You need Python 3.0 to build the newer version of node-libcurl. I forgot to update the README with the changes. Take a look on the CHANGELOG for the most recent requirements.

**Comment by obriankevin11** [comment]
Thank you.

**Comment by neoakris** [comment]
Update in case anyone else runs into this in the future: 
I had to run a tweaked command to fix it, there's also a dependency on git
```docker
FROM docker.io/node:20-bookworm-slim
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt update -y && apt install -y \
    python3 libcurl4-openssl-dev build-essential git
# ^-- fixes an debian specific issue related to npm install sync-request-curl dependency
```
