### ISSUE TITLE
Getting errors on npm install

### ISSUE THREAD

**Issue by oelbaga** [JCMais/node-libcurl#380]
**Describe the bug**

When I attempt to install the package installation gets disrupted and terminal throws this error:
```
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm ERR! code 1
```

**To Reproduce**

Install the package: npm i node-libcurl

**Version information:**

Version: 3.0.0
```
```

OS:
Node.js Version: Node.js v17.4.0

**Additional context**
<img width="683" alt="Screenshot 2023-01-26 at 7 45 13 PM" src="https://user-images.githubusercontent.com/11394862/214982175-f1bca407-e2a0-4053-97b4-d298fc4fe4f4.png">

**Comment by JCMais** [comment]
To keep the maintainability of this project, I am closing old tickets (sorry if your ticket was kept open for so long without feedback). 

If the issue continues with the latest version of node-libcurl, please feel free to create a new ticket.
