### ISSUE TITLE
How to use node-libcurl with bun?

### ISSUE THREAD

**Issue by A-Posthuman** [JCMais/node-libcurl#387]
I'm interesting in trying to improve the speed of my app by using bun instead of node to run it. However when I try to run my app with bun 0.5.9 I get an error:

error: Cannot find module "../lib/binding/node_libcurl.node" from "/home/ubuntu/node_modules/node-libcurl/dist/Easy.js"

This was after using bun to install node-libcurl. Any ideas? Thanks

**Comment by adarshmadrecha** [comment]
As of now this library is not compatible with bun. 
Once #389 is implemented, you can try with bun.

**Comment by JCMais** [comment]
Non-nodejs runtimes are not supported at the moment. Closing this for now.

The issue to track here is https://github.com/JCMais/node-libcurl/issues/155
