### ISSUE TITLE
Get response body with multies

### ISSUE THREAD

**Issue by evgenyzinoviev** [JCMais/node-libcurl#39]
This example https://github.com/JCMais/node-libcurl/blob/develop/examples/multi-interface.js shows how to get the status code, but how to get the response body?

**Comment by JCMais** [comment]
You need to set the onData callback on each handle you want to store the received body, I've pushed an improved version of the example which does just that: https://github.com/JCMais/node-libcurl/blob/develop/examples/multi-interface.js
