### ISSUE TITLE
TypeError: Class extends value #<Object> is not a constructor or null

### ISSUE THREAD

**Issue by floydjones1** [JCMais/node-libcurl#392]
**Describe the bug**

I have a node project using this libirary and I want to start bundling it with parcel(or esbuild) into a single file so I don't have the bloat of node_modules folder. When I bundle successfully with parcel 2 I get this output and when I run the file I get this output.

![image](https://github.com/JCMais/node-libcurl/assets/43974214/2e94b7ba-9556-4c41-9acf-dc2d456f1152)

**To Reproduce**

Steps to reproduce the behavior, if possible, provide a Dockerfile that is able to reproduce the issue.

**Version information:**

Version:
```
Version: libcurl/7.86.0 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.10.0 nghttp2/1.47.0
Protocols: dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Features: AsynchDNS, Debug, TrackMemory, IDN, IPv6, Largefile, NTLM, NTLM_WB, SSL, libz, brotli, TLS-SRP, HTTP2, UnixSockets, HTTPS-proxy, alt-svc
```

OS:
Node.js Version:
18.14.2
**Additional context**

**Comment by JCMais** [comment]
Sorry, but I cannot offer support for custom bundlers.
