### ISSUE TITLE
crashing on timeout

### ISSUE THREAD

**Issue by codehero** [JCMais/node-libcurl#4]
When a curl request times out, the node process crashes within the winsock closesocket() call.
The call stack is as follows:

closesocket()
Curl_closesocket()
conn_free()
Curl_disconnect()
Curl_done()
curl_multi_remove_handle()
Curl::ProcessMessages()
Curl::OnTimeout()
uv_timer_get_repeat()
uv_run()

Any advice on how to resolve?

**Comment by JCMais** [comment]
@codehero can you check if this issue is fixed for you in the develop branch?

**Comment by codehero** [comment]
I'm afraid I've abandoned the use of node-libcurl in my application. I've no longer got the time to look at it, apologies. Good luck.

**Comment by JCMais** [comment]
No problems! And thank you for your help.
