### ISSUE TITLE
he requested URL returned error: 401，how to read response body to get msg？

### ISSUE THREAD

**Issue by oopses** [JCMais/node-libcurl#400]
request code is 401，but server also return some error msg in body，how to read it？

**Comment by oopses** [comment]
sorry，i set wrong opt

**Comment by JCMais** [comment]
Hey @oopses, could you add more details about the solution? What option was missing? 

Anything I can improve on the docs?

**Comment by oopses** [comment]
> Hey @oopses, could you add more details about the solution? What option was missing?
> 
> Anything I can improve on the docs?
Sorry, I didn't provide complete information. I didn't have an idea at first, so I thought of using the C++ demo to try it out and find a property related
https://curl.se/libcurl/c/CURLOPT_FAILONERROR.html
https://github.com/JCMais/node-libcurl/blob/887949944dce38a19ee4ecbc5854aabe757e2a46/src/Curl.cc#L119C4-L119C4

After setting the above to false, curl will continue to read data, and it can be processed in combination with statusCode


👍node-libcurl is fantastic
