### ISSUE TITLE
Provide cli via -g install flag

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [JCMais/node-libcurl#47]
Have you considered providing this as a cli utility that basically works like curl? (could install with two names, say `ncurl` and `curl` to avoid conflicts). I was thinking about this because installing curl on windows isn't the best experience, but you'd need it to run nodejs/node core tests.

Care for a PR? Alternatively I'd just write some module for it.

**Comment by JCMais** [comment]
Hi,

I don't think this is in the scope of this module, so no, I'm not whiling to have this added, at least not for now. Feel free to create one module if you think this would be useful.

I agree that it's hard to install curl on windows, that is one of the motives I maintain the following fork of an older project of same name:  https://github.com/JCMais/curl-for-windows it has every libcurl dependency in a single gyp project, so you only need python and any version of visual studio to get curl working.

**Comment by eljefedelrodeodeljefe** [comment]
Okay. Will check out that, but probably will end up with the separate package and have yours as dependency. 

Will post a link. I am already working on it, but I already know that'll take out the speed of `libcurl`, because of initialization times. I guess that would have been a -1 for integrating it here.

Thx for maintaining this.
