### ISSUE TITLE
Curl.option.SSH_AUTH_TYPES is missing?

### ISSUE THREAD

**Issue by johnnypez** [JCMais/node-libcurl#48]
Hi,
It could be wrong but it looks like the CURLOPT for [SSH_AUTH_TYPES](https://curl.haxx.se/libcurl/c/CURLOPT_SSH_AUTH_TYPES.html) is missing.
I can see that you have provided the relevant settings in `Curl.ssh_auth` [here](https://github.com/JCMais/node-libcurl/blob/9858668460e62d53ee3910ed6d3722f1e108f5a4/lib/Curl.js#L447) but when I try to implement it, I get

> Error: Unknown option given. First argument must be the option internal id or the option name.

The following should reproduce the error:

```
var Curl = require('node-libcurl').Curl

curl = new Curl()
curl.setOpt(Curl.option.VERBOSE, true)
curl.setOpt(Curl.option.URL, "sftp://user:pass@example.com")
curl.setOpt(Curl.option.SSH_AUTH_TYPES, Curl.ssh_auth.PASSWORD)
curl.perform()
```

**Comment by JCMais** [comment]
Hi!

Thanks for reporting that, should be fixed in `0.8.0`!

**Comment by johnnypez** [comment]
Any idea when 0.8.0 will land? Is there any way I could work around it?

**Comment by johnnypez** [comment]
Sorry, I see that you released 0.8.0 last night. Thank you ;)

**Comment by johnnypez** [comment]
It took me a minute to realise that this only works with an `Easy` handle. Is there any particular reason for that?

e.g. this throws an error
```
var ch = new Curl()
ch.setOpt(Curl.option.SSH_AUTH_TYPES, Curl.ssh_auth.PASSWORD)
```

but this works.
```
var ch = new Easy()
ch.setOpt(Curl.option.SSH_AUTH_TYPES, Curl.ssh_auth.PASSWORD)
```

**Comment by johnnypez** [comment]
Did you ever have one of those mornings where you waste two hours because you haven't woken up yet?
Libcurl doesn't have sftp support enabled on my local machine but it's available on my dev machine in the cloud. So I was seeing different results.

Also, after reading your code, I realised that the above was not throwing an error when trying to set that option on the Easy() handle directly because only the Curl() handle checks the return code and throws an error if CURLE_OK is not returned. In both instances CURLE_UNKNOWN_OPTION was being returned.

Anyway, thanks again for implementing this so quick. Time for ☕☕☕

**Comment by JCMais** [comment]
> Did you ever have one of those mornings where you waste two hours because you haven't woken up yet?

Almost everyday. :smile:
