### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by sergez** [JCMais/node-libcurl#5]
During build I've got an error described bellow

  string_format.cc
..\src\string_format.cc(11): error C2220: warning treated as error - no 'object' file generated [<project path>\node_modules\node-libcurl\build\node-libcurl.vcxproj]
..\src\string_format.cc(11): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [<project path>\node_modules\node-libcurl\build\node-libcurl.vcxpro
j]
..\src\Curl.cc(474): error C2220: warning treated as error - no 'object' file generated [<project path>\node_modules\node-libcurl\build\node-libcurl.vcxproj]
..\src\Curl.cc(474): warning C4267: '+=' : conversion from 'size_t' to 'int', possible loss of data [<project path>\node_modules\node-libcurl\build\node-libcurl.vcxproj]
..\src\Curl.cc(483): warning C4267: '+=' : conversion from 'size_t' to 'int', possible loss of data [<project path>\node_modules\node-libcurl\build\node-libcurl.vcxproj]
..\src\Curl.cc(740): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [<project path>\node_modules\node-libcurl\build\node-libcurl.vcxproj]

Env: Win 7 x64, VS 2013 update 4, python 2.7.9, node 0.10.34, npm 1.4.28

It's strange because i don't have any issues on Win 8.1 32bit, VS 2013 update 4. I have no idea how to fix this issue.

**Comment by JCMais** [comment]
Can you check if your issue is fixed in the develop branch?

Git clone the repository and run npm install.
