### ISSUE TITLE
"Cloning" a curl request for multiple execution

### ISSUE THREAD

**Issue by netei** [JCMais/node-libcurl#51]
I would like to be able to "retry" a curl request (with exactly the same options), without having to redefine all opts manually. Is they a way to do this ?

For example : 

```
var curl=new Curl();
curl.setOpt('URL',url);
curl.setOpt('FOLLOWLOCATION',true);
curl.setOpt('SSL_VERIFYPEER', false);

var curlRetry = curl.clone()
curl.on('end', function(statusCode) {
  if (statusCode===404) {
    curlRetry.perform();
  }
})

curl.perform();
```

**Comment by JCMais** [comment]
You want the [dupHandle method](https://github.com/JCMais/node-libcurl/blob/develop/api.md#module_node-libcurl.Curl+dupHandle), it's called that way to keep it consistent with the libcurl api.

Example: https://github.com/JCMais/node-libcurl/blob/develop/examples/duplicate-handle.js

**Comment by netei** [comment]
Thanks, I ended up writing some specific code (eg storing the options in a vanilla JS Obj, then looping over key values to set the options), but I might use curls method instead. 

Thanks !
