### ISSUE TITLE
Set header

### ISSUE THREAD

**Issue by gerasimvol** [JCMais/node-libcurl#54]
Hi, I'm trying to set option `curl.setOpt( 'CURLOPT_HTTPHEADER', ['Host: ' + frontend]);`, where `frontend` is front end IP. But 'end' or 'error' handlers are not invoked. Any thoughts how to set host in header?

**Comment by JCMais** [comment]
Can you post a example? Also, what is the module and curl version.

**Comment by gerasimvol** [comment]
For example, I have frontend with IP: `mail.example.com` and backend IP: `192.168.0.15:80`

I give curl `192.168.0.15:80` to check accessibility to this IP, but also I want to set in header:

Host: mail.example.com
(https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) search for 'host'

**Comment by JCMais** [comment]
The option is correct, enable verbose mode and see what is happening: ``curl.setOpt( 'VERBOSE', true );``

**Comment by gerasimvol** [comment]
Still no output if `curl.setOpt( 'CURLOPT_HTTPHEADER', ['Host: ' + mail.example.com]);` is used.

Also, when `curl.setOpt( 'CURLOPT_HTTPHEADER', ['Host: ' + mail.example.com]);` isn't used I have some log in console. How to save output in variable? For example `var curlLog = curl.verboseInfo`

**Comment by JCMais** [comment]
Oh, I missed something about your report.

```
curl.setOpt( 'CURLOPT_HTTPHEADER', ['Host: ' + frontend]);
```

This should be:

```
curl.setOpt( 'HTTPHEADER', ['Host: ' + frontend]);
```

or

```
curl.setOpt( Curl.option.HTTPHEADER, ['Host: ' + frontend]);
```

**Comment by gerasimvol** [comment]
Yes! Such a dump mistake. Thanks!

**Comment by gerasimvol** [comment]
`curl.setOpt( 'VERBOSE', true ); ` log in console. Is it posible to save log in string or file?

**Comment by JCMais** [comment]
That would be the STDERR option of libcurl, but it's not implemented, you can use the debug callback to get the information as strings. Example: https://github.com/JCMais/node-libcurl/blob/develop/examples/debug-callback.js
