### ISSUE TITLE
Error building for nwjs

### ISSUE THREAD

**Issue by bozzzi** [JCMais/node-libcurl#56]
WIN7 X64
Node 0.12.13 X32

Python 2.7 - OK
Visual Studio 2013 - OK 
git - OK

npm install nw-gyp -g - OK
npm install node-libcurl --runtime=node-webkit --target=0.12.3 --arch=ia32 --msvs_version=2013 --build-from-source --save

**console error:**
gyp: conditions target_arch=="arm" must be length 2 or 3, not 17

**debug-log error:**
14804 error Windows_NT 6.1.7601
14805 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-libcurl" "--runtime=node-webkit" "--target=0.12.3" "--arch=ia32" "--msvs_version=2013" "--build-from-source" "--save"
14806 error node v0.12.13
14807 error npm  v2.15.0
14808 error code ELIFECYCLE

**Editing file deps\curl-for-windows\openssl\openssl.gyp
removes mentioned error, goes further with building but fails with many errors.**

Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git init -q && git submodule add https://github.com/JCMais/curl-for-windows.git deps/curl-for-windows"
'deps/curl-for-windows' already exists and is not a valid git repo

------------------------------------------------------
When using:
**npm install node-libcurl**
builds OK, work OK in node, not working in nwjs (Module version mismatch. Expected 43, got 14)

On Mac & Linux (Debian Ubuntu) same command builds and work OK for nwjs.

Can anybody compile and upload **node_libcurl-v0.9.0-node-v43-win32-ia32.tar.gz**

**Comment by JCMais** [comment]
Hi, I'm really busy this week, so I cannot work on this issue right now. I compiled the addon to nw some time ago, and probably some stuff changed that is causing this issue.

**Comment by bozzzi** [comment]
Hi,

Thanks for prompt response. 

I didn't dig into deep but I think it's something with openSSL and it's linkage with curl library. 

I'll try to do some debuging, and let you know. If you can help with superficial explanation of "some stuff changed" maybe I can find the origin of the error.

Thank you

**Comment by bozzzi** [comment]
Found temporary workaround.

1. npm install node-libcurl
2. node-gyp rebuild --target=0.12.3
3. Open project in Visual Studio 2015 (I think it is going to work with 2013 the same)
4. In VS project solution replace dependency lib **.node.gyp/Release/node.lib** with **.nw.gyp/Release/nw.lib** and build solution
5. Replace **node-libcurl\lib\binding\node_libcurl.node **with newly built file

WORKING

Testing for now for unexpected behavior, but seems that all the tests work fine.

**Comment by JCMais** [comment]
Hi, I finally had time to look into this, and I found the issue.

``nw-gyp`` bundles an outdated version of ``gyp`` which doesn't support the if-else conditions syntax being used in the ``openssl.gyp`` here https://github.com/JCMais/curl-for-windows/blob/master/openssl/openssl.gyp#L69.

The way to fix that is to update the gyp version manually, you can do that downloading it from this repo: https://github.com/bnoordhuis/gyp and placing it in the gyp folder inside the nw-gyp folder. (nw-gyp is probably installed globally, so you need to look up where it's).

Them there is still one more thing to do, you need to disable the compiler ``WarnAsError`` flag for this addon, do so in the ``node-libcurl/bindings.gyp`` file.

After that rebuild the addon, run this from the addon folder: ``node_modules\.bin\node-pre-gyp rebuild --runtime=node-webkit --target=0.15.0-rc2 --arch=x64``

**Comment by bozzzi** [comment]
Great,

Thx
