### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by gqferreira** [JCMais/node-libcurl#57]
> My system:
> Linux 3.16.0-4-586 #1 Debian 3.16.7-ckt25-2 (2016-04-08) i686 GNU/Linux

**I'm having the following problem when I try to install node-libcurl**
Can someone help me?
Thank you!

root@Homologacao-telemetria:/var/www/html/socket-server# npm install node-libcurl --safe

> node-libcurl@0.9.0 install /var/www/html/socket-server/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.11.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/socket-server/node_modules/node-libcurl/.node-gyp"
make: Entering directory '/var/www/html/socket-server/node_modules/node-libcurl/build'
make: *** No rule to make target '../.node-gyp/5.11.0/include/node/common.gypi', needed by 'Makefile'.  Pare.
make: Leaving directory '/var/www/html/socket-server/node_modules/node-libcurl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/www/html/socket-server/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.16.0-4-586
gyp ERR! command "/opt/node/bin/node" "/var/www/html/socket-server/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/www/html/socket-server/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/var/www/html/socket-server/node_modules/node-libcurl/lib/binding"
gyp ERR! cwd /var/www/html/socket-server/node_modules/node-libcurl
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/node/bin/node /var/www/html/socket-server/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/html/socket-server/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/var/www/html/socket-server/node_modules/node-libcurl/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/html/socket-server/node_modules/node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 3.16.0-4-586
node-pre-gyp ERR! command "/opt/node/bin/node" "/var/www/html/socket-server/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/html/socket-server/node_modules/node-libcurl
node-pre-gyp ERR! node -v v5.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.13
node-pre-gyp ERR! not ok 
Failed to execute '/opt/node/bin/node /var/www/html/socket-server/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/html/socket-server/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/var/www/html/socket-server/node_modules/node-libcurl/lib/binding' (1)
/var/www/html/socket-server
├── express@4.13.4 
├── fs@0.0.2 
├── net@1.0.2 
└── socket.io@1.4.5 

npm WARN enoent ENOENT: no such file or directory, open '/var/www/html/socket-server/package.json'
npm WARN socket-server No description
npm WARN socket-server No repository field.
npm WARN socket-server No README data
npm WARN socket-server No license field.
npm ERR! Linux 3.16.0-4-586
npm ERR! argv "/opt/node/bin/node" "/opt/node/bin/npm" "install" "node-libcurl" "--safe"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.9.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libcurl@0.9.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-libcurl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/socket-server/npm-debug.log
root@Homologacao-telemetria:/var/www/html/socket-server#

**Comment by JCMais** [comment]
This is an issue with node-gyp not with the addon, try to follow some of the solutions here: https://github.com/nodejs/node-gyp/issues/454
