### ISSUE TITLE
How to download file

### ISSUE THREAD

**Issue by JoniJnm** [JCMais/node-libcurl#58]
Hi,

curl for linux has the [option -o](https://curl.haxx.se/docs/manpage.html#-o). How can I download a file using this plugin? I tried:

```js
curl.on('end', function ( statusCode, body, headers ) {
	this.close();

	var zipFile = tmpFolder + 'langs.zip';
	FS.writeFileSync(zipFile, body, {
		encoding: null
	});
});
```

And

```js
var zipper = require('zip-local');

curl.on('end', function ( statusCode, body, headers ) {
	this.close();

	var buffer = new Buffer(body, "binary");
	zipper.unzip(zipFile, function(err, unzipped) {
		//check err
		unzipped.save(outputFolder, function(err) {
			//check err
			cb(); //ok
		});
	});
});
```

But I can't open it, seems like is corrupted.

**Comment by bozzzi** [comment]
Hi,

Can you post all code? 
From which source are you downloading file?

You can use something like

_var http = require('http');
var fs = require('fs');

var testURL = 'http://test.com/test.zip';
var testDest = './zips/test.zip'; 

var download = function(url, dest, cb) {
  var file = fs.createWriteStream(dest);
  var request = http.get(url, function(response) {
    response.pipe(file);
    file.on('finish', function() {
      file.close(cb);  // close() is async, call cb after close completes.
    });
  }).on('error', function(err) { // Handle errors
    fs.unlink(dest); // Delete the file async. (But we don't check the result)
    if (cb) cb(err.message);
  });
};_

for downloading file using simple http request. Why do you need curl?

and then unzip it with

_var zipper = require('zip-local');

var unzippFN = function(dest, cb){
zipper.unzip(dest, function(error, unzipped) { 

    if(!error) {
        // extract to the current working directory
        unzipped.save(null, function() { });

        var unzippedfs = unzipped.memory();

        // print an array of file paths in the unzipped file
        console.log(unzippedfs.contents()); 
        if(cb)cb(unzippedfs.contents())
});
}_


_download(testUrl, testDest, function(){
	console.log('download complete');
	unzippFN(testDest, function(data){
		console.log('Unzipped data again: '+data);
	});
});_

Didn't test the code but it should work...

**Comment by JCMais** [comment]
If you want to use libcurl for that, check the [progress-callback.js](https://github.com/JCMais/node-libcurl/blob/develop/examples/progress-callback.js) file. It has an example showing how to download a file and display a progress bar.
