### ISSUE TITLE
CURLOPT_TIMEOUT not working

### ISSUE THREAD

**Issue by bozzzi** [JCMais/node-libcurl#59]
Hi,

According to libcurl docs:

CURLOPT_TIMEOUT
Timeout for the entire request. See CURLOPT_TIMEOUT
CURLOPT_TIMEOUT_MS
Millisecond timeout for the entire request. See CURLOPT_TIMEOUT_MS

but setting **curl.setopt( 'TIMEOUT', 100)** returns **TypeError: undefined is not a fn**

I can see than **Curl.option** has default values 

TIMEOUT: 13
TIMEOUT_MS: 155

but are they really included? It logically should be that every call that takes longer than the default value ( longer than 155 ms ) should fail if not set differently. I assume that this option is not implemented?

I have situation where I need curl, but if no response returned in some time (f.e. 15000 ms) it should return exception, so I can init curl call again...

Any suggestion would be highly appreciated.

Thanks

**Comment by JCMais** [comment]
Hi @bozzzi, 

The correct function is ``curl.setOpt``, javascript is case-sensitive.

The api is here: https://github.com/JCMais/node-libcurl/blob/develop/api.md

> I can see than Curl.option has default values 
Those are constant used by libcurl to identify each option, they are not the default values of given option, just their identifier.

**Comment by bozzzi** [comment]
Hi,

Thanks for prompt response.

I can not believe I made such a typo, and searched for problem on wrong place... :-)

Thanks again.
