### ISSUE TITLE
Build failing on OS X Yosemite

### ISSUE THREAD

**Issue by jrsinclair** [JCMais/node-libcurl#6]
Attempting to install with node v0.10.35 I get the following errors:

    > node-libcurl@0.1.0 install /Users/james/path-to-my-project/node_modules/node-libcurl
    > node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild

      CXX(target) Release/obj.target/node-libcurl/src/node-libcurl.o
      CXX(target) Release/obj.target/node-libcurl/src/Curl.o
    In file included from ../src/Curl.cc:11:
    ../src/generated-stubs/curlAuth.h:5:10: warning: implicit conversion from 'unsigned long' to 'int32_t' (aka 'int') changes value from 18446744073709551599 to -17
          [-Wconstant-conversion]
            {"ANY", CURLAUTH_ANY},
            ~       ^~~~~~~~~~~~
    /usr/include/curl/curl.h:640:32: note: expanded from macro 'CURLAUTH_ANY'
    #define CURLAUTH_ANY          (~CURLAUTH_DIGEST_IE)
                                   ^~~~~~~~~~~~~~~~~~~
    In file included from ../src/Curl.cc:11:
    ../src/generated-stubs/curlAuth.h:6:14: warning: implicit conversion from 'unsigned long' to 'int32_t' (aka 'int') changes value from 18446744073709551598 to -18
          [-Wconstant-conversion]
            {"ANYSAFE", CURLAUTH_ANYSAFE},
            ~           ^~~~~~~~~~~~~~~~
    /usr/include/curl/curl.h:641:32: note: expanded from macro 'CURLAUTH_ANYSAFE'
    #define CURLAUTH_ANYSAFE      (~(CURLAUTH_BASIC|CURLAUTH_DIGEST_IE))
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../src/Curl.cc:188:68: error: use of undeclared identifier 'nullptr'
        Curl::ExportConstants( &authObj, curlAuth, sizeof( curlAuth ), nullptr, nullptr );
                                                                       ^
    ../src/Curl.cc:189:68: error: use of undeclared identifier 'nullptr'
        Curl::ExportConstants( &httpObj, curlHttp, sizeof( curlHttp ), nullptr, nullptr );
                                                                       ^
    ../src/Curl.cc:190:71: error: use of undeclared identifier 'nullptr'
        Curl::ExportConstants( &pauseObj, curlPause, sizeof( curlPause ), nullptr, nullptr );
                                                                          ^
    ../src/Curl.cc:191:83: error: use of undeclared identifier 'nullptr'
        Curl::ExportConstants( &protocolsObj, curlProtocols, sizeof( curlProtocols ), nullptr, nullptr );
                                                                                      ^
    ../src/Curl.cc:605:51: error: unknown class name 'false_type'; did you mean '__false_type'?
    template <typename> struct ResultCanBeNull : std::false_type {};
                                                      ^~~~~~~~~~
                                                      __false_type
    /usr/include/c++/4.2.1/bits/cpp_type_traits.h:98:10: note: '__false_type' declared here
      struct __false_type { };
             ^
    ../src/Curl.cc:606:50: error: unknown class name 'true_type'; did you mean '__true_type'?
    template <> struct ResultCanBeNull<char*> : std::true_type {};
                                                     ^~~~~~~~~
                                                     __true_type
    /usr/include/c++/4.2.1/bits/cpp_type_traits.h:97:10: note: '__true_type' declared here
      struct __true_type { };
             ^
    ../src/Curl.cc:623:40: error: no member named 'value' in 'ResultCanBeNull<char *>'
        if ( ResultCanBeNull<TResultType>::value && !result ) //null pointer
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    ../src/Curl.cc:1057:24: note: in instantiation of function template specialization 'Curl::GetInfoTmpl<char *, v8::String>' requested here
            retVal = Curl::GetInfoTmpl<char*, v8::String>( *(obj), infoId );
                           ^
    ../src/Curl.cc:623:40: error: no member named 'value' in 'ResultCanBeNull<long>'
        if ( ResultCanBeNull<TResultType>::value && !result ) //null pointer
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    ../src/Curl.cc:1062:24: note: in instantiation of function template specialization 'Curl::GetInfoTmpl<long, v8::Integer>' requested here
            retVal = Curl::GetInfoTmpl<long, v8::Integer>(  *(obj), infoId );
                           ^
    ../src/Curl.cc:623:40: error: no member named 'value' in 'ResultCanBeNull<double>'
        if ( ResultCanBeNull<TResultType>::value && !result ) //null pointer
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    ../src/Curl.cc:1067:24: note: in instantiation of function template specialization 'Curl::GetInfoTmpl<double, v8::Number>' requested here
            retVal = Curl::GetInfoTmpl<double, v8::Number>( *(obj), infoId );
                           ^
    2 warnings and 9 errors generated.
    make: *** [Release/obj.target/node-libcurl/src/Curl.o] Error 1

**Comment by JCMais** [comment]
@jrsinclair Those errors are because the compiler is not compiling the code with c++11 support enabled, I've probably fixed this in 05fcea7, but as I don't own a mac to test it, can you check it?

**Comment by jrsinclair** [comment]
Hi @JCMais, thanks heaps for the quick response. Is there any chance you could tag that commit to make it easier to grab through npm?

Cheers,

James

**Comment by JCMais** [comment]
Grab the lastest version from npm, the changes are there.

**Comment by jrsinclair** [comment]
Thanks for that. It seems to have fixed a few of the errors, but revealed new ones. Compiler output is below:

    npm WARN engine node-libcurl@0.1.2: wanted: {"node":">= 0.8.0 && < 0.11.0"} (current: {"node":"0.10.35","npm":"2.1.17"})
    -
    > node-libcurl@0.1.2 install /Users/james/Dropbox/carmm_shared/ServerWatcher_James/node-checker/node_modules/node-libcurl
    > node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild

      CXX(target) Release/obj.target/node-libcurl/src/node-libcurl.o
      CXX(target) Release/obj.target/node-libcurl/src/Curl.o
    In file included from ../src/Curl.cc:17:
    ../src/generated-stubs/curlAuth.h:5:10: error: constant expression evaluates to 18446744073709551599 which cannot be narrowed to type 'int32_t' (aka 'int') [-Wc++11-narrowing]
            {"ANY", CURLAUTH_ANY},
                    ^~~~~~~~~~~~
    /usr/include/curl/curl.h:640:31: note: expanded from macro 'CURLAUTH_ANY'
    #define CURLAUTH_ANY          (~CURLAUTH_DIGEST_IE)
                                  ^~~~~~~~~~~~~~~~~~~~~
    ../src/generated-stubs/curlAuth.h:5:10: note: override this message by inserting an explicit cast
            {"ANY", CURLAUTH_ANY},
                    ^~~~~~~~~~~~
                    static_cast<int32_t>( )
    /usr/include/curl/curl.h:640:31: note: expanded from macro 'CURLAUTH_ANY'
    #define CURLAUTH_ANY          (~CURLAUTH_DIGEST_IE)
                                  ^~~~~~~~~~~~~~~~~~~~~
    In file included from ../src/Curl.cc:17:
    ../src/generated-stubs/curlAuth.h:6:14: error: constant expression evaluates to 18446744073709551598 which cannot be narrowed to type 'int32_t' (aka 'int') [-Wc++11-narrowing]
            {"ANYSAFE", CURLAUTH_ANYSAFE},
                        ^~~~~~~~~~~~~~~~
    /usr/include/curl/curl.h:641:31: note: expanded from macro 'CURLAUTH_ANYSAFE'
    #define CURLAUTH_ANYSAFE      (~(CURLAUTH_BASIC|CURLAUTH_DIGEST_IE))
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../src/generated-stubs/curlAuth.h:6:14: note: override this message by inserting an explicit cast
            {"ANYSAFE", CURLAUTH_ANYSAFE},
                        ^~~~~~~~~~~~~~~~
                        static_cast<int32_t>( )
    /usr/include/curl/curl.h:641:31: note: expanded from macro 'CURLAUTH_ANYSAFE'
    #define CURLAUTH_ANYSAFE      (~(CURLAUTH_BASIC|CURLAUTH_DIGEST_IE))
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from ../src/Curl.cc:17:
    ../src/generated-stubs/curlAuth.h:14:11: error: constant expression evaluates to 2147483648 which cannot be narrowed to type 'int32_t' (aka 'int') [-Wc++11-narrowing]
            {"ONLY", CURLAUTH_ONLY}
                     ^~~~~~~~~~~~~
    /usr/include/curl/curl.h:639:31: note: expanded from macro 'CURLAUTH_ONLY'
    #define CURLAUTH_ONLY         (((unsigned long)1)<<31)
                                  ^~~~~~~~~~~~~~~~~~~~~~~~
    ../src/generated-stubs/curlAuth.h:14:11: note: override this message by inserting an explicit cast
            {"ONLY", CURLAUTH_ONLY}
                     ^~~~~~~~~~~~~
                     static_cast<int32_t>( )
    /usr/include/curl/curl.h:639:31: note: expanded from macro 'CURLAUTH_ONLY'
    #define CURLAUTH_ONLY         (((unsigned long)1)<<31)
                                  ^~~~~~~~~~~~~~~~~~~~~~~~
    In file included from ../src/Curl.cc:17:
    ../src/generated-stubs/curlAuth.h:5:10: warning: implicit conversion from 'unsigned long' to 'int32_t' (aka 'int') changes value from 18446744073709551599 to -17
          [-Wconstant-conversion]
            {"ANY", CURLAUTH_ANY},
            ~       ^~~~~~~~~~~~
    /usr/include/curl/curl.h:640:32: note: expanded from macro 'CURLAUTH_ANY'
    #define CURLAUTH_ANY          (~CURLAUTH_DIGEST_IE)
                                   ^~~~~~~~~~~~~~~~~~~
    In file included from ../src/Curl.cc:17:
    ../src/generated-stubs/curlAuth.h:6:14: warning: implicit conversion from 'unsigned long' to 'int32_t' (aka 'int') changes value from 18446744073709551598 to -18
          [-Wconstant-conversion]
            {"ANYSAFE", CURLAUTH_ANYSAFE},
            ~           ^~~~~~~~~~~~~~~~
    /usr/include/curl/curl.h:641:32: note: expanded from macro 'CURLAUTH_ANYSAFE'
    #define CURLAUTH_ANYSAFE      (~(CURLAUTH_BASIC|CURLAUTH_DIGEST_IE))
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings and 3 errors generated.
    make: *** [Release/obj.target/node-libcurl/src/Curl.o] Error 1

**Comment by JCMais** [comment]
Those warnings are about a known issue, but that has no implications to the client code.

Try the latest version.

**Comment by jrsinclair** [comment]
Latest version installed fine. Thanks.
