### ISSUE TITLE
I cannot install package

### ISSUE THREAD

**Issue by huquduy** [JCMais/node-libcurl#64]
this is logs after i run "npm install node-libcurl --build-from-source"
make: Entering directory '/var/www/apibetting/node_modules/node-libcurl/build'
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
make: g++: Command not found
node_libcurl.target.mk:102: recipe for target 'Release/obj.target/node_libcurl/src/node_libcurl.o' failed
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 127
make: Leaving directory '/var/www/apibetting/node_modules/node-libcurl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/www/apibetting/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-22-generic
gyp ERR! command "/usr/bin/nodejs" "/var/www/apibetting/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/www/apibetting/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/var/www/apibetting/node_modules/node-libcurl/lib/binding"
gyp ERR! cwd /var/www/apibetting/node_modules/node-libcurl
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /var/www/apibetting/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/apibetting/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/var/www/apibetting/node_modules/node-libcurl/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/apibetting/node_modules/node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.4.0-22-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/var/www/apibetting/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/apibetting/node_modules/node-libcurl
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /var/www/apibetting/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/apibetting/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/var/www/apibetting/node_modules/node-libcurl/lib/binding' (1)
apiGameSite@0.0.0 /var/www/apibetting
└── (empty)

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-libcurl" "--build-from-source"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libcurl@1.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-libcurl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/apibetting/npm-debug.log
npm ERR! code 1

help me, :(

**Comment by JCMais** [comment]
Hi.

Install ``gcc`` on your distro.
> The only compiler supported on linux is gcc >=4.8, also you need to have the libcurl development files available, if you are running debian for example, you must install the libcurl4-openssl-dev package.

**Comment by huquduy** [comment]
i don't know, but it work fine when i change to Ubuntu 14.04, thanks you!

**Comment by viion** [comment]
Would it be possible to be more specific on what you need to install?

I get this issue on a vagrant machine (works fine on a normal). I have to use the `--no-bin-links` option otherwise it won't get past that, which is usually enough for most packages but for this I am getting the same error described above.

**Comment by JCMais** [comment]
@viion  Paste the error log. Use  ``--verbose`` when installing.
