### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by BossMode** [JCMais/node-libcurl#65]
I couldn't find anything in the examples, is code for SOCKS4A, 6?

Like this for example `curl.setOpt(Curl.option.PROXYTYPE,6)/`

**Comment by JCMais** [comment]
Looks like I forgot to add those constants, will do so next version.

Yes, the value for ``SOCKS4A`` is 6: https://github.com/curl/curl/blob/curl-7_49_1/include/curl/curl.h#L635
