### ISSUE TITLE
node 4.4.7 + osx = cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by kamil7732** [JCMais/node-libcurl#67]
Hi,
I've followed steps of fellow programmers that solved the issue of using your lib with node 4
sadly after moving the needle I bumped onto another problem.
TypeError: Cannot read property 'bind' of undefined
I20160818-21:06:08.673(2)?     at Curl (/node_modules/node-libcurl/lib/Curl.js:84:66)

it was built like npm install --save node-libcurl --build-from-source

osx is newest, xcode also
any idea?

also how I used the lib:

```
const curl = require( 'node-libcurl' ).Curl;
curl('http://.../add?inputFormat=xml&outputFormat=json',
            {
                POST: 1,
                // RETURNTRANSFER: 1,
                POSTFIELDS: html,
                USERPWD: "jjd",
                SSL_VERIFYPEER: false,
                SSL_VERIFYHOST: false
            },
            Meteor.bindEnvironment((err, res) => {
               
                let result = JSON.parse(res.body);
                console.log(result.invoices[0].invoice.id);
               
            }));
```
yes it's meteor...newest on node 4.4.7

**Comment by JCMais** [comment]
The calls you are doing are wrong, they are not part of the API, the constructor doesn't accepts any parameters, and you are passing the url, and some objects.
