### ISSUE TITLE
Max redirects?

### ISSUE THREAD

**Issue by ragFOEX** [JCMais/node-libcurl#69]
Using node-libcurl on a certain url seems to hang. When I try the same with command line curl I get the error message
`curl: (47) Maximum (50) redirects followed`

But node-libcurl seems to try forever.

I've set a connectiontimeout, but that doesn't seem to count here.

**Comment by JCMais** [comment]
Hi,
can you post the code please? And if possible the URL you are trying to request.

**Comment by ragFOEX** [comment]
I'm using the [sample code](https://github.com/JCMais/node-libcurl#simple-request), but the website I'm pointing to keeps redirecting. 

I was just able to fix the underlying problem by providing a cookiefile, so now the website doesn't redirect anymore. But I'm wondering how I still could limit the number of redirects.

Example URL: http://demo.tryfoexnow.com/apex/f?p=125

**Comment by JCMais** [comment]
Oh, you can limit using the option [``MAXREDIRS``](https://curl.haxx.se/libcurl/c/CURLOPT_MAXREDIRS.html):

```javascript
curl.setOpt( Curl.option.MAXREDIRS, 50 );
```

You can see the list of options supported by libcurl on their official documentation: https://curl.haxx.se/libcurl/c/curl_easy_setopt.html

**Comment by ragFOEX** [comment]
Thanks, that's what I was missing!

**Comment by dzcpy** [comment]
How to use it with curly?
