### ISSUE TITLE
Build fail OSX

### ISSUE THREAD

**Issue by riyadhalnur** [JCMais/node-libcurl#7]
```
Cannot find curl's header file.
npm ERR! node-libcurl@0.1.3 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libcurl@0.1.3 install script.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.0.0
npm ERR! command "/Users/newscred/.nvm/v0.10.26/bin/node" "/Users/newscred/.nvm/v0.10.26/bin/npm" "install" "node-libcurl" "--save"
npm ERR! cwd /Users/newscred/Desktop/instagram_node
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/newscred/Desktop/instagram_node/npm-debug.log
npm ERR! not ok code 0
```

**Comment by JCMais** [comment]
>Cannot find curl's header file.

Looks like you don't have libcurl installed, since the installer cannot find the headers.

**Comment by riyadhalnur** [comment]
i do have it though
![screen shot 2015-01-17 at 10 58 20 pm](https://cloud.githubusercontent.com/assets/3457571/5789605/734f5fee-9e9c-11e4-94ff-a81caa12d0b3.png)

**Comment by JCMais** [comment]
That is the curl tool, its possible that the library was installed somewhere else. Try to run ``curl-config --libs``.

**Comment by celle886** [comment]
I have the same error. What is the next step when i have the install folder?

**Comment by JCMais** [comment]
@celle886 I've started working on a new feature to use curl-config to get the correct configuration flags, can you checkout the branch feature/custom-libcurl-lib-path and try to build it? (``node-gyp rebuild``)

**Comment by kevinhikaruevans** [comment]
This was happening to me earlier.

I had two installations of curl, one from the Debian repository and one that I compiled.
I removed the binaries/libraries from the compiled version earlier but curl-config was still pointing to the deleted binaries. I reinstalled the package containing curl-config (libcurl4-gnutls-dev) and it worked after that.

**Comment by JCMais** [comment]
Timing out.
