### ISSUE TITLE
Help to code

### ISSUE THREAD

**Issue by wallace7souza** [JCMais/node-libcurl#70]
Hi!
I'm trying to use this lib but how would the code for the nodejs similar to this line

`curl -X GET https://api.pagar.me/1/plans \
-d 'api_key=ak_test_grXidddddQ4GisdfdfsdfsdfsdfsdfsdfsdfsdfDRTR5qNQxJW0' \
-d 'page=1' \
-d 'count=3'`

**Comment by JCMais** [comment]
Hi,

When in doubt on how to convert one request from command-line for usage with libcurl, you can pass the ``--libcurl [FILE]`` argument, it will generate a C file with code that should match the one required to repeat the request. From there you can just convert to Javascript using this library.

About your command-line, I removed ``-X GET``, using -d implies the [``POSTFIELDS``](https://curl.haxx.se/libcurl/c/CURLOPT_POSTFIELDS.html) option, which means a ``POST`` request is going to be made.

The source generated is basically the following:

```c
hnd = curl_easy_init();
curl_easy_setopt(hnd, CURLOPT_URL, "https://api.pagar.me/1/plans");
curl_easy_setopt(hnd, CURLOPT_NOPROGRESS, 1L);
curl_easy_setopt(hnd, CURLOPT_POSTFIELDS, "api_key=ak_test_grXijQ4GicOa2BLGZrDRTR5qNQxJW0&page=1&count=3");
curl_easy_setopt(hnd, CURLOPT_POSTFIELDSIZE_LARGE, (curl_off_t)61);
curl_easy_setopt(hnd, CURLOPT_USERAGENT, "curl/7.51.0-DEV");
curl_easy_setopt(hnd, CURLOPT_MAXREDIRS, 50L);
curl_easy_setopt(hnd, CURLOPT_SSH_KNOWNHOSTS, "path/to/.ssh/known_hosts");
curl_easy_setopt(hnd, CURLOPT_TCP_KEEPALIVE, 1L);
```

Converting to Javascript using this module:
```javascript
var Curl = require( 'node-libcurl' ).Curl,
    curl = new Curl();

//you can use a string as option
curl.setOpt( Curl.option.URL, 'https://api.pagar.me/1/plans' );
curl.setOpt( Curl.option.POSTFIELDS, 'api_key=ak_test_grXijQ4GicOa2BLGZrDRTR5qNQxJW0&page=1&count=3' );
// About the other options in the C source:
// NOPROGRESS is not necessary since 1 is the default,
// POSTFIELDSIZE is not necessary for that request,
// USERAGENT is optional, 
// MAXREDIRS is not necessary if you are not enabling FOLLOWLOCATION,
// SSH_KNOWNHOSTS is not necessary, and
// KEEPALIVE is optional.


curl.on( 'end', function ( statusCode, body, headers ) {

    console.info( 'Status Code: ', statusCode );
    console.info( 'Headers: ', headers );
    console.info( 'Body length: ', body.length );

    this.close();
});

curl.on( 'error', function ( err, curlErrCode ) {

    console.error( 'Err: ', err );
    console.error( 'Code: ', curlErrCode );

    this.close();
});

curl.perform();
```

Also, keep in mind that the URL you are trying to request is using SSL, you probably will need to set other options for it to work, check the example file [ssl.js](https://github.com/JCMais/node-libcurl/blob/develop/examples/ssl.js)

**Comment by wallace7souza** [comment]
Thanks @JCMais !
Worked fine! including with security
