### ISSUE TITLE
How to use CURLOPT_SSLCERTPASSWD?

### ISSUE THREAD

**Issue by omkarpg0931** [JCMais/node-libcurl#71]
hi,

I have a certificate that needs password to be sent with it. I tried SSLCERTPASSWD but i am getting 

			curl.setOpt( Curl.option.SSLCERTPASSWD, '23421451241' );

Error: Unknown option given. First argument must be the option internal id or the option name. You can use the Curl.option constants.

**Comment by bozzzi** [comment]
Try:

curl.setOpt( 'SSLCERTPASSWD', 23421451241);

**Comment by omkarpg0931** [comment]
@bozzzi tried. not working. getting the same error.

if i remove curl.setOpt( Curl.option.SSLCERTPASSWD, '23421451241' ); or curl.setOpt( 'SSLCERTPASSWD', 23421451241); statement it works but due to password i am getting "Invalid certificate error"error.

**Comment by bozzzi** [comment]
Can you debug cert error more in detail?

**Comment by omkarpg0931** [comment]
Try CERT:PASS without SSLCERTPASSWD

did you mean to try this way? 
curl.setOpt( 'CERT:PASS', certfile:'23421451241' )

**Comment by JCMais** [comment]
This option was renamed a long time ago, use (https://curl.haxx.se/libcurl/c/CURLOPT_KEYPASSWD.html)[KEYPASSWD]
