### ISSUE TITLE
Send curl get request with parameters

### ISSUE THREAD

**Issue by vipinder** [JCMais/node-libcurl#72]
not able send curl get request with parameters

**Comment by JCMais** [comment]
what you tried?

Check the ``post-data.js`` and ``simple-request.js`` examples.

**Comment by vipinder** [comment]
using simple-request.js i am getting blank response
  var curl = new Curl();

        curl.setOpt(Curl.option.URL, url);
        curl.setOpt(Curl.option.FOLLOWLOCATION, true);
        curl.setOpt(Curl.option.COOKIEFILE, ''); //enable cookies

        curl.on('end', function (statusCode, body, headers) {
           console.log(body)
            this.close();
        });

        curl.on('error', curl.close.bind(curl));
        curl.perform();

**Comment by JCMais** [comment]
is the error event firing? Add a callback with ``console.log`` to see.

Also, what is your node.js version, and if you build from source, the libcurl version.

**Comment by JCMais** [comment]
Timed-out.
