### ISSUE TITLE
Rebuild on Windows fails with missing "deps" directory

### ISSUE THREAD

**Issue by gschier** [JCMais/node-libcurl#76]
Hi there,

I'm trying to build the lib on Windows. However, when installed via NPM, the `node-libcurl/deps` directory seems to be missing (I see that it's in .npmignore). 

This causes `npm install node-libcurl --build-from-source` to fail with the following error:

```batch
C:\Users\IEUser\Desktop\insomnia>npm install node-libcurl --build-from-source

> node-libcurl@1.0.0 install C:\Users\IEUser\Desktop\insomnia\node_modules\node-libcurl
> node-pre-gyp install --fallback-to-build

File:  C:\Users\IEUser\Desktop\insomnia\node_modules\node-libcurl\deps\curl-for-windows\libssh2.gyp  not found.
gyp: Call to 'node "C:\Users\IEUser\Desktop\insomnia\node_modules\node-libcurl/tools/retrieve-win-deps.js"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

Is there a way to get around this missing dependency?

_Note: it works fine without `--build-from-source` (using the prebuilt bins), but I need to be able to rebuild it for use with Electron._

**Comment by gschier** [comment]
After some debugging, it looks like the check being used to see if you're in a git repo returns a false positive if the parent directory is a git repo https://github.com/JCMais/node-libcurl/blob/develop/tools/retrieve-win-deps.js#L27

I forced it to call `parseSubmodulesConfig();` and it got further (now failing on different error). Maybe there is a more reliable way to check if the current directory is under git control?

**Comment by JCMais** [comment]
> After some debugging, it looks like the check being used to see if you're in a git repo returns a false positive if the parent directory is a git repo

You are right! I didn't think of that. I could parse the result of ``git rev-parse --git-dir`` and make sure it's the same directory of the module.

**Comment by JCMais** [comment]
This should be fixed on ``v1.1.0``, let me know if it's not.

**Comment by gschier** [comment]
Thanks! I will test it out soon 😄

**Comment by gschier** [comment]
Just letting you know that the new version now works as expected.

**Comment by JCMais** [comment]
Glad it's working!
