### ISSUE TITLE
npm package needs updating

### ISSUE THREAD

**Issue by gschier** [JCMais/node-libcurl#77]
Hello,

I noticed that `node-gyp` is set to version `3.5.0` in this repo, but the version on npm is still at `3.3.0`. Does the npm package need to be updated?

https://github.com/JCMais/node-libcurl/commit/8be2e11e5372421c59cd84f0e4f473ea0cf81ba2

**Comment by JCMais** [comment]
Hi,

The changes to the ``develop`` branch were not pushed to npm yet, trying to get an update this week, probably today if time allows me.

**Comment by gschier** [comment]
That makes sense. FYI, the change is also in master https://github.com/JCMais/node-libcurl/blob/master/package.json#L40

Looking forward to the update! This library is literally the perfect fit for my project [Insomnia](https://insomnia.rest/). If you need any help in the future let me know.

**Comment by JCMais** [comment]
Yes, I just pushed changes to master. Version ``v1.1.0`` published to npm.
