### ISSUE TITLE
not working on alpine

### ISSUE THREAD

**Issue by dcharbonnier** [JCMais/node-libcurl#79]
Dockerfile
```
FROM node:7.5-alpine
RUN apk add --no-cache libcurl
RUN npm install node-libcurl
RUN  echo "require('node-libcurl')"|node
```
`docker build .`
```
...
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Error relocating /node_modules/node-libcurl/lib/binding/node_libcurl.node: __vsnprintf_chk: symbol not found
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/node-libcurl/lib/Easy.js:40:29)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by dcharbonnier** [comment]
working Dockerfile (**but would be nice to have the binary**)
```
FROM node:7.5-alpine
RUN apk add --no-cache libcurl python alpine-sdk curl-dev
RUN npm install node-libcurl --build-from-source
RUN  echo "require('node-libcurl')"|node
```

**Comment by dcharbonnier** [comment]
still not working with an httpS url

**Comment by JCMais** [comment]
for httpS you need Openssl installed.

**Comment by dcharbonnier** [comment]
it's installed...
```
curl -V
curl 7.52.1-DEV (x86_64-unknown-linux-gnu) libcurl/7.52.1-DEV OpenSSL/1.0.2k zlib/1.2.8 libssh2/1.7.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 
```
I even compiled curl and openssl manually but the test stop after that :
```
> * Connected to www.google.com (172.217.23.68) port 443 (#1)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/transcoder-agent/cacert.pem
  CApath: none
> 
```
no data event, no end event, no error event

**Comment by JCMais** [comment]
does using libcurl alone works?

**Comment by dcharbonnier** [comment]
"using" libcurl seams complicated but installing pycurl on this system pycurl can manage httpS

**Comment by JCMais** [comment]
This will not verify the peer, but will connect if ssl is working:
``curl --insecure https://www.google.com``

Or from code, just set the following option:
``curl.setOpt( Curl.option.SSL_VERIFYPEER, false );``

If that works the problem is that you are not using a cert file, you can download one from here https://curl.haxx.se/docs/caextract.html

And use it with ``curl.setOpt( Curl.option.CAINFO, 'path-to-the-cert-file' );

If nothing works, post a code that can reproduce the problem.

**Comment by dcharbonnier** [comment]
```
curl --insecure https://www.google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.it/?gfe_rd=cr&amp;ei=ruKlWMb4MtDw8Aer4J6QBw">here</A>.
</BODY></HTML>
```
and yes I tried to disable ssl verify and also to download the certificates providing the file path but it does not help, I'm trying to build a minimal container to reproduce the problem

**Comment by dcharbonnier** [comment]
https://gist.github.com/dcharbonnier/b4f9ff9a30bfa4fd17e4ed2813508f28#file-readme

```
  pycurl
    ✓ should get an http url (183ms)
    ✓ should get an https url (341ms)

  node-libcurl
    npm install
      ✓ should succeed (13246ms)
      1) should import without error
    npm install --build-from-source
      ✓ should succeed (17706ms)
      ✓ should import without error (16278ms)
      ✓ should get an http url (16432ms)
      2) should get an https url


  6 passing (2m)
  2 failing

  1) node-libcurl npm install should import without error:
     module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Error relocating /tmp/node_modules/node-libcurl/lib/binding/node_libcurl.node: __vsnprintf_chk: symbol not found
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/node_modules/node-libcurl/lib/Easy.js:40:29)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

  Error: module.js:598
    return process.dlopen(module, path._makeLong(filename));
                   ^

  Error: Error relocating /tmp/node_modules/node-libcurl/lib/binding/node_libcurl.node: __vsnprintf_chk: symbol not found
      at require (internal/module.js:20:19)
      at Object.<anonymous> (/tmp/node_modules/node-libcurl/lib/Easy.js:40:29)

      at Context.it (test/test.js:49:23)

  2) node-libcurl npm install --build-from-source should get an https url:
     Error: Timeout

      at Context.it (test/test.js:88:23)
```

**Comment by JCMais** [comment]
I will be able to test this only this weekend or next week.

But I just saw that ``node-serialport`` has some special instructions for alpine, can you try using those to install this module?

https://github.com/EmergingTechnologyAdvisors/node-serialport#alpine-linux

**Comment by dcharbonnier** [comment]
The problem for serialport is that you can't compile without those packages but in this case it's not the problem, the package they require are all in alpine-sdk and I manage to compile node-libcurl, if I had a crash for a problem of linking it would be easier than this unexpected "freeze".
If you don't know docker and need some help I'm here.

**Comment by JCMais** [comment]
Can you try building from the current develop branch?

**Comment by dcharbonnier** [comment]
exactly the same, I updated the gist

**Comment by JCMais** [comment]
I still didn't had time to check on this. And currently I cannot install Docker, since it blocks me from using VirtualBox (Windows).

**Comment by dcharbonnier** [comment]
Not a big deal for me anymore I removed the node-libcurl dependency but you should mention on the readme that npm install may not work on some systems, depending on the ssl version they have and that there is no compatibility with alpine. That could help people deciding to not use this library if they plan to use docker at some point, otherwise this lib is amazing.

**Comment by OnArs** [comment]
@dcharbonnier @JCMais is there any solution?

**Comment by dcharbonnier** [comment]
no @OnArs, run. I execute a curl binary when I need a long download/upload and node request for the rest and it work perfectly

**Comment by OnArs** [comment]
That's not a solution at all. @JCMais could you please pay attention to this issue?

**Comment by JCMais** [comment]
@OnArs  I'm paying attention, that is why it's still open, I just didn't had time to investigate this.

**Comment by OnArs** [comment]
@JCMais  it's serious. When you investigate?

**Comment by JCMais** [comment]
@OnArs the best estimative I can give is two weeks or so. 

For now, your best bet is searching similar issues, like this one for `wget`:

**Comment by JCMais** [comment]
Looks like it's working on the latest version!
