### ISSUE TITLE
Curl request never finish / return, timeout does not work

### ISSUE THREAD

**Issue by tomrf** [JCMais/node-libcurl#81]
With the following example, curl never returns anything, and never times out.

Using curl(1) from the command line with -L -v shows a 301 redirect to a slow https site, but data is returned with HTTP 200 after about 10 seconds.

With node-libcurl, no 'end' or 'error' event is ever fired, and the request never times out even though TIMEOUT is set to three seconds.

Any ideas?

```
var Curl = require('node-libcurl').Curl;

function curlUrl(url, callback) {
	var curl = new Curl();
	curl.setOpt('URL', url);
	curl.setOpt('FOLLOWLOCATION', true);
	curl.setOpt('TIMEOUT', 3);
	curl.on('end', function(statusCode, body, headers) {
	    this.close();
	    callback(body, statusCode);
	});
	curl.on('error', function (err, code) {
		curl.close.bind(curl);
		callback(null, code);
	});
	curl.perform();
}

curlUrl('http://arrow.no', function(results, errorCode) {
	console.log(results, errorCode);
});
```

Node version: v6.9.4
node-libcurl@1.1.0

**Comment by JCMais** [comment]
This correctly works here. 

But first it gave me an issue with the CA Cert, since you are not specifying one, libcurl cannot verify if the SSL is valid or not.

> Error: Peer certificate cannot be authenticated with given CA certificates
> null 60

Disabling SSL_VERIFYPEER (``curl.setOpt('SSL_VERIFYPEER', 0);``) correctly gives the timeout error:
> Error: Timeout was reached
> null 28

**Comment by tomrf** [comment]
I'm still having the same problem even with SSL_VERIFYPEER set to false.

Any tips on how to get more verbose debugging info, or how to investigate this further on my end?

**Comment by JCMais** [comment]
Set ``curl.setOpt( 'VERBOSE', true )``

**Comment by tomrf** [comment]
libcurl version: libcurl/7.29.0 NSS/3.21 Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3

Running this same script with VERBOSE set to true, and just letting it hang for a while, I can see that the operation finally times out after 690 seconds(!)

For some reason the TIMEOUT specified is not respected in this case?

```
* About to connect() to arrow.no port 80 (#0)
*   Trying 50.56.4.134...
* Connected to arrow.no (50.56.4.134) port 80 (#0)
> GET / HTTP/1.1
Host: arrow.no
Accept: */*

< HTTP/1.1 301 Moved Permanently
< Server: Apache
< Content-Type: text/html; charset=UTF-8
< Date: Mon, 27 Feb 2017 15:48:56 GMT
< Location: https://www.arrow.com/
< Connection: Keep-Alive
< Content-Length: 0
<
* Connection #0 to host arrow.no left intact
* Issue another request to this URL: 'https://www.arrow.com/'
* About to connect() to www.arrow.com port 443 (#1)
*   Trying 95.100.176.203...
* Connected to www.arrow.com (95.100.176.203) port 443 (#1)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=webassets.arrow.com,OU=Akamai SAN SSL OV,O=Arrow Electronics,L=Melville,ST=New York,C=US
*       start date: Aug 18 00:00:00 2016 GMT
*       expire date: Sep 17 23:59:59 2017 GMT
*       common name: webassets.arrow.com
*       issuer: CN=GeoTrust SSL CA - G3,O=GeoTrust Inc.,C=US
> GET / HTTP/1.1
Host: www.arrow.com
Accept: */*

* Operation timed out after 690119 milliseconds with 0 out of -1 bytes received
* Closing connection 1
null 28
```

**Comment by tomrf** [comment]
On a different server with the same versions of node, curl, node-libcurl, I am seeing a different message after 11 minutes 30 seconds (TIMEOUT set to 10 sec);

```
[...] time node test.js [...]
* select/poll returned error
* Closing connection 1
null 55

real    11m29.464s
user    0m0.541s
sys     0m0.211s
```

**Comment by JCMais** [comment]
> Also note '0 out of -1 bytes received' -- is the operation expecting -1 bytes? Seems weird.

This does look weird, but your libcurl version is more than 4 years old, can you install a newer one to check if the issue is fixed?

**Comment by tomrf** [comment]
I upgrade curl/libcurl to v7.53.1 and TIMEOUT now works as expected.  Sadly curl 7.29 comes with the latest release of CentOS (maybe RedHat and Fedora too?).  Maybe add a warning on install or use about older versions of libcurl? I dunno.

Thanks a bunch for helping me debug this!
