### ISSUE TITLE
How to statically link libcurl?

### ISSUE THREAD

**Issue by gschier** [JCMais/node-libcurl#84]
Hello again,

It appears that the default configuration for this project is to dynamically link the libcurl library. I'm building an Electron app for the desktop, so I'd like to be able to statically link libcurl and not rely on OS dependencies.

The only documentation I've found on this is [here](https://github.com/mapbox/node-pre-gyp/wiki/External-libraries), but it doesn't provide much detail. Do you have any advice on how I might go about it (links, blog posts, etc)?

Thanks!

**Comment by JCMais** [comment]
Specifically for libcurl, you need to define ``CURL_STATICLIB`` (like it's being defined currently, but only for Windows, https://github.com/JCMais/node-libcurl/blob/develop/binding.gyp#L62), and make ``curl-config.js`` (https://github.com/JCMais/node-libcurl/blob/develop/tools/curl-config.js) execute ``curl-config --static-libs`` instead of ``curl-config --libs``.

I'm static linking only for Windows because it's rare to have ``libcurl`` or ``openssl`` available there.

**Comment by gschier** [comment]
@JCMais thanks for the response and thanks for pointing me in the right direction. 

FYI, I didn't think it'd be a huge deal either to dynamically link but I've seen a few cases where the user had either a too-new (Arch Linux) or too-old (OSX Sierra) version of libcurl. There was also an issue due to Fedora users having an NSS build of libcurl instead of OpenSSL. 

I'll play around with it some more and let you know what I find! 😄

**Comment by JCMais** [comment]
Any luck on that @gschier?

**Comment by gschier** [comment]
@JCMais have not had the time to try this yet. I'll make sure to let you know when I do 😄

**Comment by gschier** [comment]
@JCMais So I just gave it a shot and successfully got it working on a Mac. Your suggestions were all that needed to be done in this project. The hard part was figuring out how to compile Curl from source without shared libs so that `curl-config` output the right things. 

If you're curious, here's what it took:

```bash
CPPFLAGS="-I/usr/local/opt/openssl/include" LDFLAGS="-L/usr/local/opt/openssl/lib" ./configure --disable-shared --with-ssl
```

And verified in the console:

```javascript
require('node-libcurl').Curl.getVersion()
"libcurl/7.54.1-DEV OpenSSL/1.0.2k zlib/1.2.8"

// What it was previously: 
// "libcurl/7.51.0 SecureTransport zlib/1.2.8"
```

It looks like it would be pretty easy to add a command line flag to enable static builds via a flag. `node-sqlite3` does a similar thing: https://github.com/mapbox/node-sqlite3/blob/master/binding.gyp#L4

**Comment by king-alpha** [comment]
Hi, I'm using a windows machine (x64) and I'm trying to get node-libcurl to work for my electron application, I followed the install command given in the documentation which is `npm install node-libcurl --runtime=electron --target=1.0.2 --disturl=https://atom.io/download/atom-shell --arch=x64 --save
` and replaced the target version with the target version of electron that I was building for (in this case it was 2.0.17) and this is the error I keep getting any time I run the install command. `fatal error LNK1106: invalid file or disk full: cannot seek to 0x 29851C [D:\Code\share\node_modules\node-libcurl\build\node_libcurl.vcxproj]
![Screenshot (181)](https://user-images.githubusercontent.com/36765257/56358228-ec5abd80-6192-11e9-8a31-6f9fb1bdb348.png)
`  please, can anyone help me out on this?

**Comment by JCMais** [comment]
the prebuilt binaries are now statically linked with libcurl and their dependencies.

Currently available only on the `next` tag, which will become v2: `node-libcurl@next`

**Comment by gschier** [comment]
Woah, this is awesome! Are there any instructions for building it from source (for use with Electron)?

**Comment by JCMais** [comment]
@gschier  the addon now also has prebuilt binaries for Electron (the latest 3 versions) and nw.js (latest 2 versions), so installing the addon for Electron can be done like this:
```
npm install node-libcurl@next --runtime=electron --target=$(npx electron --version) --disturl=https://atom.io/download/atom-shell --save
```
or using yarn:
```
npm_config_runtime=electron npm_config_target=$(npx electron --version) npm_config_disturl=https://atom.io/download/atom-shell yarn add node-libcurl@next
```

If you want to ignore the prebuild binaries you can pass `--build-from-source` if installing via npm or the env var `npm_config_build_from_source=true` when using yarn.

**Comment by gschier** [comment]
Oh my God even better! You're the best ❤️
