### ISSUE TITLE
Promisify library, use await / async

### ISSUE THREAD

**Issue by JCMais** [JCMais/node-libcurl#85]
This will require Node.js >= 7.6 if not using a transpiler like babel. However, using babel is probably better since this will allow us to use more recent es6 features, like import / export, while also supporting old Node.js versions.

Those changes would only be made to the `Curl` wrapper, the other apis (`Easy` and `Multi`) will stay the same.

- [ ] Make `Curl#perform` return a promise.
- [ ] Use `async`/`await`.
- [ ] Create babel scripts to compile lib files (those files would added to the npm package and made the entry point of the package).

**Comment by do-web** [comment]
Here is a simple wrapper https://github.com/do-web/curl-request

**Comment by JCMais** [comment]
I prefer to leave this to the client for now. When everyone has migrated to newest node we can use that without needing babel.

**Comment by JCMais** [comment]
Closing for now, there will be a new experimental async wrapper on v2
