### ISSUE TITLE
--unix-socket option

### ISSUE THREAD

**Issue by giper45** [JCMais/node-libcurl#89]
Hi, does this library support the --unix-socket curl option ? I'd like to do something like curl --unix-socket /var/run/docker.sock http:/images/json

**Comment by JCMais** [comment]
See: https://github.com/JCMais/node-libcurl/issues/70#issuecomment-253640483

You want to use the option `Curl..option.UNIX_SOCKET_PATH`. You need libcurl `>= 7.40` for that.

**Comment by giper45** [comment]
Thanks it works perfectly ! Now I just have to try it on Windows to see if can use it without installing curl cmd line, so I can use it in my module with no external curl dependencies ! Thanks very much
