### ISSUE TITLE
Use curl_multi_socket_action

### ISSUE THREAD

**Issue by DemiMarie** [JCMais/node-libcurl#90]
libcurl supports an event-driven API (`curl_multi_socket_action` and friends).  This API allows for much better performance than the blocking API.

**Comment by JCMais** [comment]
Hi, the `Multi` interface API is supported, there is an example here: https://github.com/JCMais/node-libcurl/blob/develop/examples/multi-interface.js

The `Curl` wrapper is also asynchronous (it uses the `Multi` interface), the only blocking API is the `Easy` one.

**Comment by DemiMarie** [comment]
Does it use curl_multi_socket_action internally though?  That's the most
efficient way to use libcurl.  Other ways are slower.

**Comment by JCMais** [comment]
See https://github.com/JCMais/node-libcurl/blob/develop/src/Multi.cc#L178
