### ISSUE TITLE
i can't install it

### ISSUE THREAD

**Issue by shikar** [JCMais/node-libcurl#93]
https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v57-darwin-x64.tar.gz  this file is not found

node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@8.0.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Users/shikar/Works/GIT/M_EBAY_TAE/taeRest/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.1.0 and node@8.0.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v57-darwin-x64.tar.gz

**Comment by JCMais** [comment]
It should compile just fine, put the whole log.

**Comment by JCMais** [comment]
timing out
