### ISSUE TITLE
incompatible node library version

### ISSUE THREAD

**Issue by gutasaputra** [JCMais/node-libcurl#95]
hey there i this library looks awesome, i want to use it in my project.
when i try to run the file node index.js it gives me an error msg.

<img width="645" alt="screen shot 2017-06-06 at 1 33 04 pm" src="https://cloud.githubusercontent.com/assets/1556126/26816614/b63832d0-4abc-11e7-8faa-158fab84884c.png">

i knew that there is an incompatible library version. but idk how to fix it. 

ohya, btw i read the installation page, but i cant install libcurl4-openssl-dev package.
i tried brew install libcurl4-openssl-dev. 
but the result is " Error: No formulae found in taps. "

can you pls help me?

many thanks

**Comment by JCMais** [comment]
See https://github.com/JCMais/node-libcurl/issues/43 and https://github.com/JCMais/node-libcurl/issues/63
