### ISSUE TITLE
Error: node_curl package.json is not node-pre-gyp ready:

### ISSUE THREAD

**Issue by gutasaputra** [JCMais/node-libcurl#98]
hello again,

i tried to post some data with libcurl.
but i got this error msg.

> Error: node_curl package.json is not node-pre-gyp ready:

btw, i already install this packages, i saw it in your package.json

    "debug": "^2.2",
    "nan": "~2.5.0",
    "node-gyp": "~3.5.0",
    "node-pre-gyp": "~0.6",
    "npmlog": "~4.0.2"

but the error still coming up.
can you tell me pls what i can do to fix this?

thank you.

**Comment by JCMais** [comment]
This is not the `node_curl` package.

**Comment by gutasaputra** [comment]
sorry bro. what do you mean?
i tried use one of your example code.
https://github.com/JCMais/node-libcurl/blob/develop/examples/post-data.js

then it throw me an error 
Error: node_curl package.json is not node-pre-gyp ready

can you help me to fix it?

thanks

**Comment by JCMais** [comment]
how did you installed the addon?

Also, what is your `OS` and Node.js version.

**Comment by gutasaputra** [comment]
i used mac. osx.

npm install node-pre-gyp --save
npm install node-gyp --save

i tried the global parameter too. 
sadly, i still got the same error msg.

**Comment by JCMais** [comment]
You should use `npm install node-libcurl`

**Comment by gutasaputra** [comment]
oh yes, i did that thing in the beginning bro.
then i got the error like this : 
node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! stack Error: node_curl package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host

**Comment by JCMais** [comment]
Idk why you are receiving those, the mentioned lines are in there, check
https://github.com/JCMais/node-libcurl/blob/develop/package.json#L29

Also, the package name is wrong, this package is not named `node_curl`, but `node_libcurl`, that is why I think your error is unrelated to this project. Are you cloning the repo?

**Comment by gutasaputra** [comment]
hmm actually im not cloning the repo.
i follow the instruction from the homepage.

let me explain from the beginning.
i installed your library with npm install node-libcurl --save

but, it goes wrong. because i got the error msg like this : 

> Incompatible library version: node_libcurl.node requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0

you can check the issue #95 

i fixed it with the

>  npm install node-libcurl --build-from-source

then i tried one of your example, to check how post data handled in your lib.
then it throw me an error
Error: node_curl package.json is not node-pre-gyp ready

what should i do bro?
should i start it over with cloning the repo? or what?

**Comment by JCMais** [comment]
are you running the example from the `node_modules` folder?

They are not supposed to be ran from there.

Create the following file on your project instead:

`post-data.js`
```javascript
var Curl = require( 'node-libcurl' ).Curl,
    querystring = require( 'querystring' );

var curl = new Curl(),
    url  = 'http://posttestserver.com/post.php',
    data = { //Data to send, inputName : value
        'input-arr[0]' : 'input-arr-val0',
        'input-arr[1]' : 'input-arr-val1',
        'input-arr[2]' : 'input-arr-val2',
        'input-name' : 'input-val'
    };

//You need to build the query string,
// node has this helper function, but it's limited for real use cases (no support for array values for example)
data = querystring.stringify( data );

curl.setOpt( Curl.option.URL, url );
curl.setOpt( Curl.option.POSTFIELDS, data );
curl.setOpt( Curl.option.HTTPHEADER, ['User-Agent: node-libcurl/1.0'] );
curl.setOpt( Curl.option.VERBOSE, true );

console.log( querystring.stringify( data ) );

curl.perform();

curl.on( 'end', function( statusCode, body ) {

    console.log( body );

    this.close();
});

curl.on( 'error', curl.close.bind( curl ) );
```

Run with `node post-data.js`

**Comment by gutasaputra** [comment]
got it. thanks mate.
