### ISSUE TITLE
Response header parsing breaks when value contains ": "

### ISSUE THREAD

**Issue by gschier** [JCMais/node-libcurl#99]
See https://github.com/JCMais/node-libcurl/blob/fddc66f1996fa3c3c2e2c3fcd3a37a7e2b254d88/lib/Curl.js#L761

If `headers[i] === "foo: bar: baz"`, it gets parsed to `['foo', 'bar', 'baz']` and `baz` is thrown away. This should only split on the first instance of `: `.

**Comment by JCMais** [comment]
I will be able to make a new release this weekend.

**Comment by gschier** [comment]
Awesome, thanks for the quick turnaround 😄
